apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectors-worker-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: connectors-worker
  template:
    metadata:
      labels:
        app: connectors-worker
        name: connectors-worker-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "connectors-worker","service": "connectors-worker","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/connectors-image:latest
          command: ["npm", "run", "start:worker"]
          args:
            [
              "--",
              "--workers",
              "confluence",
              "github",
              "intercom",
              "slack",
              "microsoft",
              "snowflake",
            ]
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: connectors-worker-config
            - secretRef:
                name: connectors-secrets

          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: private-key-volume
              mountPath: /etc/private-keys

          resources:
            requests:
              cpu: 3000m
              memory: 8Gi
              ephemeral-storage: 10Gi

            limits:
              cpu: 3000m
              memory: 8Gi
              ephemeral-storage: 10Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-cert

        - name: private-key-volume
          secret:
            secretName: github-app-private-key
