apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-worker
  template:
    metadata:
      labels:
        app: front-worker
        name: front-worker-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "front-worker","service": "front-worker","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/front-image:latest
          command: ["npm", "run", "start:worker"]
          args:
            [
              "--",
              "--workers",
              "hard_delete",
              "labs",
              "mentions_count",
              "poke",
              "post_upsert_hooks",
              "production_checks",
              "scrub_workspace_queue",
              "update_workspace_usage",
              "upsert_queue",
            ]
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: front-worker-config
            - secretRef:
                name: front-secrets
            - secretRef:
                name: front-worker-secrets

          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: service-account-volume
              mountPath: /etc/service-accounts

          resources:
            requests:
              cpu: 2000m
              memory: 10Gi

            limits:
              cpu: 2000m
              memory: 10Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-front-cert
        - name: service-account-volume
          secret:
            secretName: gcp-service-account-secret
