apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodbox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prodbox
  template:
    metadata:
      labels:
        app: prodbox
        name: prodbox-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "prodbox","service": "prodbox","tags": ["env:prod"]}]'
    spec:
      terminationGracePeriodSeconds: 180
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/prodbox-image:latest
          command: ["/bin/sh", "-c", "/dust/prodbox/init.sh"]
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: prodbox-config
            - secretRef:
                name: core-secrets
            - secretRef:
                name: connectors-secrets
            - secretRef:
                name: front-secrets

          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: private-key-volume
              mountPath: /etc/private-keys
            - name: service-account-volume
              mountPath: /etc/service-accounts
            - name: github-deploykey-deploybox
              mountPath: /etc/github-deploykey-deploybox

          resources:
            requests:
              cpu: 4000m
              memory: 8Gi
              ephemeral-storage: 10Gi
            limits:
              cpu: 4000m
              memory: 8Gi
              ephemeral-storage: 10Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-cert

        - name: private-key-volume
          secret:
            secretName: github-app-private-key

        - name: service-account-volume
          secret:
            secretName: gcp-service-account-secret

        - name: github-deploykey-deploybox
          secret:
            secretName: github-deploykey-deploybox
