import { build } from "esbuild";
import path from "path";

const frontRoot = path.resolve(import.meta.dirname, "..");
const skillRoot = path.join(
  frontRoot,
  "lib/resources/skill/code_defined/global/frames"
);

await build({
  absWorkingDir: frontRoot,
  entryPoints: [path.join(skillRoot, "document/check.ts")],
  outfile: path.join(skillRoot, "assets/document/check.mjs"),
  alias: { "@app": frontRoot },
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  minify: true,
  legalComments: "eof",
  logLevel: "info",
  banner: {
    js: "// Generated by npm run build:document-skill. Do not edit directly.",
  },
});
