/**
 * Build-time script to fetch custom model configurations.
 * Run with: npx tsx scripts/fetch-custom-models.ts
 *
 * Priority:
 * 1. Local JSON file (downloaded by CI before Docker build)
 * 2. GCS bucket (for local dev with credentials)
 * 3. Committed empty file (fallback when no file is found; an invalid file fails the build)
 */

import { validateCustomModelEndpoint } from "@app/lib/llms/stream/custom_endpoints";
import { CustomModelsFileSchema } from "@app/types/assistant/models/custom_models";
import * as fs from "fs";
import * as path from "path";
import type { z } from "zod";

// Local file path (downloaded by GH action before Docker build).
const LOCAL_JSON_PATH = path.join(__dirname, "../custom-models.json");
const OUTPUT_PATH = path.join(
  __dirname,
  "../types/assistant/models/custom_models.generated.ts"
);

type CustomModelFileEntry = z.infer<
  typeof CustomModelsFileSchema
>["models"][number];

// Throws, failing the build: a file that is present but invalid must not silently ship
// without its models.
function parseModelsFile(content: string): CustomModelFileEntry[] {
  const result = CustomModelsFileSchema.safeParse(JSON.parse(content));
  if (!result.success) {
    throw new Error(
      `Invalid custom models file: ${JSON.stringify(result.error.format())}`
    );
  }
  return result.data.models;
}

function readLocalFile(): CustomModelFileEntry[] | null {
  if (!fs.existsSync(LOCAL_JSON_PATH)) {
    return null;
  }
  console.log("Reading from local JSON file...");
  return parseModelsFile(fs.readFileSync(LOCAL_JSON_PATH, "utf-8"));
}

async function fetchFromGCS(): Promise<CustomModelFileEntry[] | null> {
  let content: string;
  try {
    // Dynamic import to avoid errors when GCS deps aren't available.
    const { getPrivateUploadBucket } = await import("@app/lib/file_storage");
    content = await getPrivateUploadBucket().fetchFileContent(
      "model-configs/custom.json"
    );
  } catch (err) {
    console.warn("Failed to fetch from GCS:", err);
    return null;
  }
  return parseModelsFile(content);
}

// Throws, failing the build: an entry the router cannot serve must not reach startup.
function assertEndpointsSupported(models: CustomModelFileEntry[]): void {
  const errors = models.flatMap(({ modelConfig, endpoint }) => {
    const validation = validateCustomModelEndpoint(endpoint);
    return validation.isErr()
      ? [`${modelConfig.modelId}: ${validation.error}`]
      : [];
  });

  if (errors.length > 0) {
    throw new Error(
      `Unsupported custom model endpoints:\n${errors.join("\n")}`
    );
  }
}

// The committed file is this function's output for an empty list.
/**
 * @cc [owner:pmilliotte,label:security] custom-model-endpoints-stay-out-of-browser-bundles
 * The output embeds every `endpoint`, `hostModel` included, and is imported by browser code through
 * `models.ts`. This script MUST NOT run in the `front-spa` build, and the committed
 * `custom_models.generated.ts` MUST stay the output for an empty list.
 */
function generateTypeScript(models: CustomModelFileEntry[]): string {
  const ids = JSON.stringify(
    models.map(({ modelConfig }) => modelConfig.modelId)
  );

  return `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/fetch-custom-models.ts at build time.
import type { CustomModelType } from "@app/types/assistant/models/custom_models";
import type { ModelConfigurationType } from "@app/types/assistant/models/types";

// Literal ids, so custom models extend the \`ModelIdType\` and \`Model\` unions.
export const CUSTOM_MODEL_IDS = ${ids} as const;

// Cast needed because \`ModelConfigurationType.modelId\` is the model id union.
export const CUSTOM_MODELS = ${JSON.stringify(models, null, 2)} as unknown as CustomModelType[];

export const CUSTOM_MODEL_CONFIGS: ModelConfigurationType[] = CUSTOM_MODELS.map(
  ({ modelConfig }) => modelConfig
);
`;
}

async function main() {
  // Try local file first (CI environment).
  let models = readLocalFile();

  // Try GCS if no local file (local dev with credentials).
  if (models === null) {
    console.log("No local file, trying GCS...");
    models = await fetchFromGCS();
  }

  if (models === null) {
    console.log("No custom models file found, using committed empty file");
    return;
  }

  assertEndpointsSupported(models);

  console.log(`Generating TypeScript for ${models.length} custom model(s)...`);
  fs.writeFileSync(OUTPUT_PATH, generateTypeScript(models));
  console.log("Done");
}

main().catch((err) => {
  console.error("Failed to generate custom models:", err);
  process.exit(1);
});
