apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: connectors-backendconfig
spec:
  timeoutSec: 300
  customResponseHeaders:
    headers:
    - "Strict-Transport-Security: max-age=31536000; includeSubDomains"
    - "X-Content-Type-Options: nosniff"
    - "Referrer-Policy: strict-origin-when-cross-origin"
    - "Permissions-Policy: geolocation=(), microphone=(), camera=()"
