import { makeInitialMessageStreamState } from "@app/components/assistant/conversation/types";
import { useAutoOpenSidePanel } from "@app/components/assistant/conversation/useAutoOpenSidePanel";
import type { ClientType } from "@app/lib/context/clientType";
import { mockAgentMessage } from "@app/tests/utils/conversation_test_factories";
import { frameContentType, frameV2ContentType } from "@app/types/files";
import { renderHook, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

const { closePanel, openPanel, surface, panelState } = vi.hoisted(() => {
  const surface: { clientType: ClientType; isMobile: boolean } = {
    clientType: "web",
    isMobile: false,
  };
  const panelState: { currentPanel: string | null } = { currentPanel: null };
  return { closePanel: vi.fn(), openPanel: vi.fn(), surface, panelState };
});

vi.mock(
  "@app/components/assistant/conversation/ConversationSidePanelContext",
  () => ({
    useConversationSidePanelContext: () => ({
      closePanel,
      currentPanel: panelState.currentPanel,
      openPanel,
    }),
  })
);

vi.mock("@app/hooks/conversations", () => ({
  useConversationMessageAction: () => ({ action: null }),
}));

vi.mock("@app/hooks/useActiveConversationId", () => ({
  useActiveConversationId: () => "conversation-1",
}));

vi.mock("@app/lib/auth/AuthContext", () => ({
  useAuth: () => ({ workspace: { sId: "workspace-1" } }),
}));

vi.mock("@app/lib/context/clientType", () => ({
  useClientType: () => surface.clientType,
}));

vi.mock("@app/lib/swr/useIsMobile", () => ({
  useIsMobile: () => surface.isMobile,
}));

const regularFile = {
  contentType: "text/csv",
  fileId: "fil_regular",
  title: "report.csv",
  hidden: false,
};

function renderWithRegularFile() {
  const agentMessage = makeInitialMessageStreamState({
    ...mockAgentMessage({ content: "Done." }),
    sId: "agent-message-1",
    generatedFiles: [regularFile],
  });

  return renderHook(() =>
    useAutoOpenSidePanel({ agentMessage, isLastMessage: true })
  );
}

describe("useAutoOpenSidePanel", () => {
  beforeEach(() => {
    closePanel.mockClear();
    openPanel.mockClear();
    surface.clientType = "web";
    surface.isMobile = false;
    panelState.currentPanel = null;
  });

  it("opens the files panel for a generated file on the desktop web app", async () => {
    renderWithRegularFile();

    await waitFor(() => {
      expect(openPanel).toHaveBeenCalledWith({ type: "files" });
    });
  });

  it("does not open any panel in the extension, where the panel covers the conversation", async () => {
    surface.clientType = "extension";

    const { result } = renderWithRegularFile();

    expect(result.current.interactiveFiles).toEqual([]);
    await waitFor(() => {
      expect(openPanel).not.toHaveBeenCalled();
      expect(closePanel).not.toHaveBeenCalled();
    });
  });

  it("does not open any panel on mobile", async () => {
    surface.isMobile = true;

    renderWithRegularFile();

    await waitFor(() => {
      expect(openPanel).not.toHaveBeenCalled();
      expect(closePanel).not.toHaveBeenCalled();
    });
  });

  it("classifies a completed Frames v2 file as a Frame and opens it", async () => {
    const frame = {
      contentType: frameV2ContentType,
      fileId: "fil_frame_v2",
      title: "Hello Frame",
      hidden: false,
    };
    const agentMessage = makeInitialMessageStreamState({
      ...mockAgentMessage({ content: "Done." }),
      sId: "agent-message-1",
      generatedFiles: [frame],
    });

    const { result } = renderHook(() =>
      useAutoOpenSidePanel({ agentMessage, isLastMessage: true })
    );

    expect(result.current.interactiveFiles).toEqual([frame]);
    await waitFor(() => {
      expect(openPanel).toHaveBeenCalledWith({
        type: "interactive_content",
        fileId: frame.fileId,
      });
    });
  });

  it("deduplicates completed Frames generated by multiple actions", () => {
    const frame = {
      contentType: frameContentType,
      fileId: "fil_frame_v1",
      title: "Hello Frame",
      hidden: false,
    };
    const agentMessage = makeInitialMessageStreamState({
      ...mockAgentMessage({ content: "Done." }),
      sId: "agent-message-1",
      generatedFiles: [frame, { ...frame }],
    });

    const { result } = renderHook(() =>
      useAutoOpenSidePanel({ agentMessage, isLastMessage: true })
    );

    expect(result.current.interactiveFiles).toEqual([frame]);
  });

  it("opens a Frame from progress when the panel is closed", async () => {
    const agentMessage = makeInitialMessageStreamState({
      ...mockAgentMessage({ content: "Publishing..." }),
      sId: "agent-message-1",
    });
    agentMessage.streaming.actionProgress.set(1, {
      action: {} as never,
      progress: {
        progress: 1,
        total: 1,
        progressToken: 1,
        _meta: {
          data: {
            label: "Publishing Frame...",
            output: {
              type: "interactive_content_file",
              fileId: "fil_frame",
              mimeType: frameV2ContentType,
              title: "Hello",
              updatedAt: "pub-1",
              autoOpen: false,
            },
          },
        },
      },
    });

    renderHook(() =>
      useAutoOpenSidePanel({ agentMessage, isLastMessage: true })
    );

    await waitFor(() => {
      expect(openPanel).toHaveBeenCalledWith({
        type: "interactive_content",
        fileId: "fil_frame",
        timestamp: "pub-1",
      });
    });
  });

  it("does not steal the file explorer for soft-open publish notifications", async () => {
    panelState.currentPanel = "files";
    const agentMessage = makeInitialMessageStreamState({
      ...mockAgentMessage({ content: "Publishing..." }),
      sId: "agent-message-1",
    });
    agentMessage.streaming.actionProgress.set(1, {
      action: {} as never,
      progress: {
        progress: 1,
        total: 1,
        progressToken: 1,
        _meta: {
          data: {
            label: "Publishing Frame...",
            output: {
              type: "interactive_content_file",
              fileId: "fil_frame",
              mimeType: frameV2ContentType,
              title: "Hello",
              updatedAt: "pub-1",
              autoOpen: false,
            },
          },
        },
      },
    });

    renderHook(() =>
      useAutoOpenSidePanel({ agentMessage, isLastMessage: true })
    );

    await waitFor(() => {
      expect(openPanel).not.toHaveBeenCalled();
    });
  });

  it("still opens Frame over the file explorer for explicit open_frame", async () => {
    panelState.currentPanel = "files";
    const agentMessage = makeInitialMessageStreamState({
      ...mockAgentMessage({ content: "Opening..." }),
      sId: "agent-message-1",
    });
    agentMessage.streaming.actionProgress.set(1, {
      action: {} as never,
      progress: {
        progress: 1,
        total: 1,
        progressToken: 1,
        _meta: {
          data: {
            label: "Opening Frame...",
            output: {
              type: "interactive_content_file",
              fileId: "fil_frame",
              mimeType: frameV2ContentType,
              title: "Hello",
              updatedAt: "1710000000000",
            },
          },
        },
      },
    });

    renderHook(() =>
      useAutoOpenSidePanel({ agentMessage, isLastMessage: true })
    );

    await waitFor(() => {
      expect(openPanel).toHaveBeenCalledWith({
        type: "interactive_content",
        fileId: "fil_frame",
        timestamp: "1710000000000",
      });
    });
  });
});
