name: 'Slack Check Deployment Blocked'
description: 'Check the Slack #deployments channel title if deployment should be blocked'

inputs:
  component:
    description: 'Component being deployed'
    required: true
  channel:
    description: 'Slack channel'
    required: true
  slack_token:
    description: 'Slack bot token'
    required: true
outputs:
  blocked:
    description: "Is deployment blocked?"
    value: ${{ steps.parse_channel_topic.outputs.blocked }}

runs:
  using: "composite"
  steps:
    - name: Get channel info
      id: slack_channel_info
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: conversations.info
        token: ${{ inputs.slack_token }}
        payload: |
          channel: ${{ inputs.channel }}

    - name: Get channel topic
      if: steps.slack_channel_info.outputs.ok == 'true'
      id: slack_channel_topic
      shell: bash
      run: |
        RESPONSE='${{ steps.slack_channel_info.outputs.response }}'
        if ! TOPIC=$(echo "$RESPONSE" | jq -r '.channel.topic.value' | sed 's/cc.*$//'); then
          echo "Failed to extract Slack channel topic" >&2
          exit 0
        fi
      
        echo "topic=$TOPIC" >> $GITHUB_OUTPUT

    - name: Parse channel topic for blocked deployments
      if: steps.slack_channel_topic.outputs.topic != ''
      id: parse_channel_topic
      shell: bash
      run: |
        is_blocked() {
            local raw_component="$1"
            local component=$(printf '%s' "$raw_component" | sed 's/[][\.*^$/]/\\&/g')

            local status_string="$2"
            
            if echo "$status_string" | grep -q ":x:[ ]*${component}[ ]" || echo "$status_string" | grep -q ":x:[ ]*${component}\$" ; then
                return 0 # Success
            else
                return 1 # Failure
            fi
        }

        if is_blocked "${{ inputs.component }}" "${{ steps.slack_channel_topic.outputs.topic }}"; then
            echo "${{ inputs.component}} is blocked based on channel topic"
            echo "blocked=true" >> $GITHUB_OUTPUT
            exit 1
        else
            echo "${{ inputs.component}} is not blocked based on channel topic"
            echo "blocked=false" >> $GITHUB_OUTPUT
            exit 0
        fi