import {
  BookOpenIcon,
  Button,
  Chip,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  ContentMessage,
  Markdown,
  Page,
  Spinner,
  Tooltip,
} from "@dust-tt/sparkle";
import React, { useState } from "react";

import {
  useGenerateUserProjectDigest,
  useUserProjectDigests,
} from "@app/lib/swr/spaces";
import type { LightWorkspaceType, SpaceType } from "@app/types";

interface SpaceUserProjectDigestProps {
  owner: LightWorkspaceType;
  space: SpaceType;
}

export function SpaceUserProjectDigest({
  owner,
  space,
}: SpaceUserProjectDigestProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { latestDigest, isDigestsLoading, mutateDigests } =
    useUserProjectDigests({
      workspaceId: owner.sId,
      spaceId: space.sId,
      limit: 1,
    });

  const doGenerate = useGenerateUserProjectDigest({
    owner,
    spaceId: space.sId,
  });

  const handleGenerate = async () => {
    setIsGenerating(true);
    const result = await doGenerate();
    setIsGenerating(false);
    if (result) {
      void mutateDigests();
    }
  };

  if (isDigestsLoading || isGenerating) {
    return (
      <div className="flex h-32 items-center justify-center">
        <Spinner size="sm" variant="color" />
      </div>
    );
  }

  if (!latestDigest) {
    return (
      <Page.Vertical gap="none" align="stretch">
        <ContentMessage
          variant="outline"
          size="lg"
          title="Project Digest"
          icon={BookOpenIcon}
          action={
            <Button
              label="Generate"
              variant="primary"
              size="sm"
              onClick={handleGenerate}
            />
          }
        >
          <div className="text-element-700 text-sm">
            No project digest yet. Click Generate to create an AI summary of
            recent project activity.
          </div>
        </ContentMessage>
      </Page.Vertical>
    );
  }

  const formattedDate = new Date(latestDigest.updatedAt).toLocaleDateString(
    "en-US",
    {
      month: "long",
      day: "numeric",
      year: "numeric",
    }
  );

  // Extract preview content (first 3 lines).
  const lines = latestDigest.digest.split("\n");
  const previewLines = lines.slice(0, 3);
  const previewContent = previewLines.join("\n");
  const remainingContent = lines.slice(3).join("\n");
  const isLongContent = lines.length > 3;

  return (
    <Page.Vertical gap="none" align="stretch">
      <ContentMessage
        variant="outline"
        size="lg"
        title="Project Digest"
        icon={BookOpenIcon}
        className="[&>div]:!items-start"
      >
        <div className="flex flex-col py-2 ">
          <div className="flex items-center gap-2">
            <Tooltip
              trigger={<Chip color="golden" size="xs" label={formattedDate} />}
              label="Generated by the AI butler of this project"
              tooltipTriggerAsChild={false}
            />
            <Button
              label="Generate"
              variant="ghost"
              size="sm"
              onClick={handleGenerate}
            />
          </div>

          {isLongContent ? (
            <Collapsible>
              <div>
                <Markdown content={previewContent} />
                <CollapsibleTrigger
                  label="Show more"
                  variant="secondary"
                  className="mt-2"
                />
              </div>
              <CollapsibleContent className="mt-2">
                <Markdown content={remainingContent} />
              </CollapsibleContent>
            </Collapsible>
          ) : (
            <Markdown content={latestDigest.digest} />
          )}
        </div>
      </ContentMessage>
    </Page.Vertical>
  );
}
