import {
  BookOpenIcon,
  Chip,
  ContentMessage,
  Markdown,
  Page,
  Spinner,
  Tooltip,
} from "@dust-tt/sparkle";
import React from "react";

import { useProjectJournalEntries } from "@app/lib/swr/spaces";
import type { LightWorkspaceType, SpaceType } from "@app/types";

interface SpaceJournalEntryProps {
  owner: LightWorkspaceType;
  space: SpaceType;
}

export function SpaceJournalEntry({ owner, space }: SpaceJournalEntryProps) {
  const { latestJournalEntry, isJournalEntriesLoading } =
    useProjectJournalEntries({
      workspaceId: owner.sId,
      spaceId: space.sId,
      limit: 1,
    });

  if (isJournalEntriesLoading) {
    return (
      <div className="flex h-32 items-center justify-center">
        <Spinner size="sm" variant="color" />
      </div>
    );
  }

  if (!latestJournalEntry) {
    return null;
  }

  const formattedDate = new Date(
    latestJournalEntry.updatedAt
  ).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <Page.Vertical gap="none" align="stretch">
      <ContentMessage
        variant="outline"
        size="lg"
        title="Journal Entry"
        icon={BookOpenIcon}
        action={
          <Tooltip
            trigger={<Chip color="golden" size="xs" label={formattedDate} />}
            label="Generated by the AI butler of this project"
            tooltipTriggerAsChild={false}
          />
        }
      >
        <Markdown content={latestJournalEntry.journalEntry} />
      </ContentMessage>
    </Page.Vertical>
  );
}
