// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  card_grid: dynamic(() => import("./CardGrid")),
  featured_article_hero: dynamic(() => import("./FeaturedArticleHero")),
  featured_card_list: dynamic(() => import("./FeaturedCardList")),
  rich_text: dynamic(() => import("./RichText")),
};
