import type { Model } from "sequelize";

export type WithoutSequelizeAttributes<T extends Model> = Omit<
  T,
  | "_attributes"
  | "sequelize"
  | "dataValues"
  | "_creationAttributes"
  | "isNewRecord"
  | "_model"
  | "where"
  | "getDataValue"
  | "setDataValue"
  | "get"
  | "set"
  | "setAttributes"
  | "changed"
  | "previous"
  | "save"
  | "reload"
  | "validate"
  | "update"
  | "destroy"
  | "restore"
  | "increment"
  | "decrement"
  | "equals"
  | "equalsOneOf"
  | "toJSON"
  | "isSoftDeleted"
  | "addHook"
  | "removeHook"
  | "hasHook"
  | "hasHooks"
>;
