/**
 * Data Source configuration
 */

import { ModelId } from "@app/lib/databases";

export type TimeFrame = {
  count: number;
  duration: "hour" | "day" | "week" | "month" | "year";
};

export type DataSourceFilter = {
  tags: { in: string[]; not: string[] } | null;
  parents: { in: string[]; not: string[] } | null;
};

export type DataSourceConfiguration = {
  workspaceId: string;
  dataSourceId: string;
  filter: DataSourceFilter;
};

/**
 * Retrieval configuration
 */

export type TemplatedQuery = {
  template: string;
};

// Retrieval specifies a list of data sources (with possible parent / tags filtering, possible "all"
// data sources), a query ("auto" generated by the model "none", no query, `TemplatedQuery`, fixed
// query), a relative time frame ("auto" generated by the model, "none" no time filtering
// `TimeFrame`) which applies to all data sources, and a top_k parameter.
//
// `query` and `relativeTimeFrame` will be used to generate the inputs specification for the model
// in charge of generating the action inputs. The results will be used along with `topK` and
// `dataSources` to query the data.
export type RetrievalConfigurationType = {
  type: "retrieval_configuration";
  dataSources: "all" | DataSourceConfiguration[];
  query: "auto" | "none" | TemplatedQuery;
  relativeTimeFrame: "auto" | "none" | TimeFrame;
  topK: number;

  // Dynamically decide to skip, if needed in the future
  // autoSkip: boolean;
};

/**
 * Retrieval action
 */

export type RetrievalDocumentType = {
  id: ModelId;
  dataSourceId: string;
  sourceUrl: string | null;
  documentId: string;
  timestamp: number;
  tags: string[];
  score: number;
  chunks: {
    text: string;
    offset: number;
    score: number;
  }[];
};

export type RetrievalActionType = {
  id: ModelId; // AssistantAgentRetrieval.
  params: {
    relativeTimeFrame: TimeFrame | null;
    query: string | null;
    topK: number;
  };
  documents: RetrievalDocumentType[];
};
