name: 'Setup Node Dependencies'
description: 'Setup Node.js and cache dependencies for SDK/JS and Front'
outputs:
  cache-hit-sdkjs:
    description: 'Whether SDK/JS cache was hit'
    value: ${{ steps.cache-sdkjs.outputs.cache-hit }}
  cache-hit-front:
    description: 'Whether Front cache was hit'
    value: ${{ steps.cache-front.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.13.0
        cache: "npm"
        cache-dependency-path: |
          package-lock.json

    - name: Cache workspaces node_modules
      id: cache-workspaces
      uses: actions/cache@v3
      with:
        path: sdks/js/node_modules
        key: workspaces-node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          workspaces-node-modules-${{ runner.os }}-

    - name: Install workspaces dependencies
      if: steps.cache-workspaces.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: Build SDK/JS
      working-directory: sdks/js
      shell: bash
      run: npm run build

    - name: Build Sparkle
      working-directory: sparkle
      shell: bash
      run: npm run build

