name: "Setup Node Dependencies"
description: "Setup Node.js and cache dependencies for SDK/JS and Front"
inputs:
  build-sdks:
    description: "Build SDK/JS"
    required: false
    default: "false"
  build-sparkle:
    description: "Build Sparkle"
    required: false
    default: "false"
outputs:
  cache-hit-node-modules:
    description: "Whether node_modules cache was hit"
    value: ${{ steps.cache-node-modules.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.22.0

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          front/node_modules
          connectors/node_modules
          sparkle/node_modules
          cli/node_modules
          extension/node_modules
          viz/node_modules
          eslint-plugin-dust/node_modules
          sdks/js/node_modules
        key: workspaces-node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          workspaces-node-modules-${{ runner.os }}-

    - name: Install workspaces dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci

    - name: Build SDK/JS
      if: inputs.build-sdks == 'true'
      working-directory: sdks/js
      shell: bash
      run: npm run build

    - name: Build Sparkle
      if: inputs.build-sparkle == 'true'
      working-directory: sparkle
      shell: bash
      run: npm run build
