name: "Setup Node Dependencies"
description: "Setup Node.js and cache dependencies for monorepo workspace"
outputs:
  cache-hit:
    description: "Whether workspace cache was hit"
    value: ${{ steps.cache-workspace.outputs.cache-hit }}
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.13.0
        cache: "npm"
        cache-dependency-path: package-lock.json

    - name: Cache workspace node_modules
      id: cache-workspace
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          front/node_modules
          sparkle/node_modules
          sdks/js/node_modules
          connectors/node_modules
          cli/node_modules
          extension/node_modules
          viz/node_modules
          common/node_modules
          eslint-plugin-dust/node_modules
        key: workspace-node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          workspace-node-modules-${{ runner.os }}-

    - name: Install workspace dependencies
      if: steps.cache-workspace.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --legacy-peer-deps

    - name: Build Sparkle
      working-directory: sparkle
      shell: bash
      run: npm run build

    - name: Build SDK/JS
      working-directory: sdks/js
      shell: bash
      run: npm run build
