apiVersion: v1
kind: Service
metadata:
  name: apache-tika-service
  namespace: apache-tika
  annotations:
    cloud.google.com/backend-config: '{"default": "apache-tika-backendconfig"}'
spec:
  selector:
    app: apache-tika
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9998
  type: ClusterIP
