apiVersion: v1
kind: Service
metadata:
  name: connectors-worker-service
spec:
  selector:
    app: connectors-worker
    name: connectors-worker-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
