apiVersion: v1
kind: Service
metadata:
  name: core-service
  annotations:
    cloud.google.com/backend-config: '{"default": "core-backendconfig"}'
spec:
  selector:
    app: core
    name: core-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
