apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dust-frontendconfig
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
  sslPolicy: dust-front-ssl-policy
  additionalHeaders:
    Strict-Transport-Security: "max-age=31536000; includeSubDomains"
    X-Content-Type-Options: "nosniff"
    Referrer-Policy: "strict-origin-when-cross-origin"
