import { isDevelopment } from "@app/types/shared/env";

// Metronome product and billable metric IDs per environment.
// Generated by metronome_setup.ts, stable across runs.

// --- DEV (sandbox) ---

// Metrics
const DEV_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC =
  "8bd72d3e-e338-46b9-bf9d-60f7ae6a8fa6";
const DEV_METRIC_LLM_PROVIDER_COST_USER =
  "eab9a2d9-c76f-4647-a7fe-623790296f27";
const DEV_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC =
  "23b1b4dd-1766-4974-88d9-aacbe22437be";
const DEV_METRIC_TOOL_INVOCATIONS_USER = "96226d69-0f02-42bd-a2d1-9f5d0c4015cb";
const DEV_METRIC_REGISTERED_USERS = "85c130a1-afc2-4135-8dae-72427b173aef";
const DEV_METRIC_MAU_1_MESSAGES = "5b6d92b6-6cf1-4348-809e-93dd751666d7";
const DEV_METRIC_MAU_5_MESSAGES = "3c264b7d-5437-4f19-abcc-3a9e9a4204e1";
const DEV_METRIC_MAU_10_MESSAGES = "152837b9-c662-4b86-bb4f-afabf18d4a40";

// Products
const DEV_PRODUCT_PROGRAMMATIC_USAGE = "61a2b400-04ca-4939-b706-5c6c9859b2c6";
const DEV_PRODUCT_AI_USAGE_USER = "00418a5c-1053-423c-97da-1ba0ea2ec0cd";
const DEV_PRODUCT_AI_USAGE_PROGRAMMATIC =
  "9c1cc7c6-2b59-4c49-ba6b-143c3930cdd7";
const DEV_PRODUCT_TOOL_USAGE_PROGRAMMATIC =
  "584fa254-0a31-47cf-8107-1ce50bce8586";
const DEV_PRODUCT_TOOL_USAGE_USER = "0a90d9d4-453f-464d-9472-14993c93e292";
const DEV_PRODUCT_WORKSPACE_SEAT = "e1532e1d-4964-4656-b6db-070fafafc44c";
// const DEV_PRODUCT_MAU_BILLING_1 = "06868f2b-f519-48c6-95e9-e28579306b2d";
// const DEV_PRODUCT_MAU_BILLING_5 = "7193add5-a895-4f40-aaa3-80e49603355c";
// const DEV_PRODUCT_MAU_BILLING_10 = "972dcb2f-0909-4444-8f29-ac26e042dbbc";
const DEV_PRODUCT_FREE_MONTHLY_CREDITS = "04f41dd1-ba27-42e3-93d5-6121712a4b67";
const DEV_PRODUCT_PREPAID_COMMIT = "5f4331b7-4bf6-488b-9a0c-51bd139ac91c";
const DEV_PRODUCT_PAYG_OVERAGE = "f4583c77-d226-48bb-97a3-46a8087b97fe";

// Rate Cards
// const DEV_RATE_CARD_LEGACY_PRO_29 = "16e39785-9e74-4c01-bca0-e1d52dd77798";
// const DEV_RATE_CARD_LEGACY_BUSINESS_45 = "89727fbf-ddea-40b4-bad7-46b6398dd201";
// const DEV_RATE_CARD_LEGACY_PRO_27_ANNUAL =
//   "6044555b-e223-40ab-ac30-e922d44fc9d6";

// Packages
const DEV_PACKAGE_LEGACY_PRO_29 = "f55ceaeb-56c6-4007-b3bc-01cbb9a458b4";
const DEV_PACKAGE_LEGACY_BUSINESS_45 = "bec4b726-252f-4ae1-bf2b-c848c2119648";
const DEV_PACKAGE_LEGACY_PRO_27_ANNUAL = "1b458342-3f7f-4103-a08f-8ceeb68e23bd";

// --- PROD (production) — TODO: update after running setup script in production ---

// Metrics
const PROD_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC =
  "3c4093e7-d429-4501-95d1-c51798969fbb";
const PROD_METRIC_LLM_PROVIDER_COST_USER =
  "b728ffa8-be00-406d-8054-25c1a94c7fe5";
const PROD_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC =
  "f3b12e98-e831-408a-a648-79d2cb1577a5";
const PROD_METRIC_TOOL_INVOCATIONS_USER =
  "3cf46f70-6bcd-4835-a6da-5a9dbe3235e2";
const PROD_METRIC_REGISTERED_USERS = "c5bfae56-8336-4ef1-9168-a4428fc92b32";
const PROD_METRIC_MAU_1_MESSAGES = "a98fb854-ab6b-4797-82ec-d7f576785ee7";
const PROD_METRIC_MAU_5_MESSAGES = "44b58b51-7a1d-4694-9e40-89e3c48566b8";
const PROD_METRIC_MAU_10_MESSAGES = "d347a6b3-5e74-4f8f-a756-1a4f6ee7c776";

// Products
const PROD_PRODUCT_PROGRAMMATIC_USAGE = "df7b4114-ca38-40bb-8812-1eb7787a6870";
const PROD_PRODUCT_AI_USAGE_USER = "add05755-6c13-4f38-97ba-4085022401ec";
const PROD_PRODUCT_AI_USAGE_PROGRAMMATIC =
  "fd5fd3e4-a7f8-46ad-86a8-20b4a90e35df";
const PROD_PRODUCT_TOOL_USAGE_PROGRAMMATIC =
  "109097e2-ed2d-4848-ba53-c4cbfa94cbdc";
const PROD_PRODUCT_TOOL_USAGE_USER = "0edd3afa-f89f-44c0-9e5d-dbace04cb133";
const PROD_PRODUCT_WORKSPACE_SEAT = "5c2e2986-1305-4406-96a2-2296e66b5a25";
// const PROD_PRODUCT_MAU_BILLING_1 = "4135a928-9447-42a5-9b66-bb35b57c7155";
// const PROD_PRODUCT_MAU_BILLING_5 = "565bef07-0348-4da8-8d4e-22de0ce856fe";
// const PROD_PRODUCT_MAU_BILLING_10 = "c34f8b46-68e0-43d3-833e-753e3150ff07";
const PROD_PRODUCT_FREE_MONTHLY_CREDITS =
  "7379999c-5492-4e68-968f-345a26f6da63";
const PROD_PRODUCT_PREPAID_COMMIT = "1408c9fc-dea1-4269-bd6d-1bc0aa1f1218";
const PROD_PRODUCT_PAYG_OVERAGE = "f6b27a6e-86fc-4964-8076-371a912cee09";

// Rate Cards
// const PROD_RATE_CARD_LEGACY_PRO_29 = "ab1ecdac-67b0-4803-8d17-13e3415d3e1d";
// const PROD_RATE_CARD_LEGACY_BUSINESS_45 =
//   "db5cea19-6421-4912-8511-9f514fc0ece2";
// const PROD_RATE_CARD_LEGACY_PRO_27_ANNUAL =
//   "7042405c-c89e-4538-80e6-e42ead7087e8";

// Packages
const PROD_PACKAGE_LEGACY_PRO_29 = "a8d782ea-b8e4-460d-99eb-393536254a01";
const PROD_PACKAGE_LEGACY_BUSINESS_45 = "c362bd20-43a1-4c1f-957d-d889dfe34704";
const PROD_PACKAGE_LEGACY_PRO_27_ANNUAL =
  "e52b9a0e-f151-4284-aa4a-87d0bddf23d0";

// --- Accessors ---

function devOrProd<T>(dev: T, prod: T): T {
  return isDevelopment() ? dev : prod;
}

// Metrics
export const getMetricLlmProviderCostProgrammaticId = () =>
  devOrProd(
    DEV_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC,
    PROD_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC
  );
export const getMetricLlmProviderCostUserId = () =>
  devOrProd(
    DEV_METRIC_LLM_PROVIDER_COST_USER,
    PROD_METRIC_LLM_PROVIDER_COST_USER
  );
export const getMetricToolInvocationsProgrammaticId = () =>
  devOrProd(
    DEV_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC,
    PROD_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC
  );
export const getMetricToolInvocationsUserId = () =>
  devOrProd(
    DEV_METRIC_TOOL_INVOCATIONS_USER,
    PROD_METRIC_TOOL_INVOCATIONS_USER
  );
export const getMetricRegisteredUsersId = () =>
  devOrProd(DEV_METRIC_REGISTERED_USERS, PROD_METRIC_REGISTERED_USERS);
export const getMetricMau1Id = () =>
  devOrProd(DEV_METRIC_MAU_1_MESSAGES, PROD_METRIC_MAU_1_MESSAGES);
export const getMetricMau5Id = () =>
  devOrProd(DEV_METRIC_MAU_5_MESSAGES, PROD_METRIC_MAU_5_MESSAGES);
export const getMetricMau10Id = () =>
  devOrProd(DEV_METRIC_MAU_10_MESSAGES, PROD_METRIC_MAU_10_MESSAGES);

// Products
export const getProductProgrammaticUsageId = () =>
  devOrProd(DEV_PRODUCT_PROGRAMMATIC_USAGE, PROD_PRODUCT_PROGRAMMATIC_USAGE);
export const getProductAiUsageUserId = () =>
  devOrProd(DEV_PRODUCT_AI_USAGE_USER, PROD_PRODUCT_AI_USAGE_USER);
export const getProductAiUsageProgrammaticId = () =>
  devOrProd(
    DEV_PRODUCT_AI_USAGE_PROGRAMMATIC,
    PROD_PRODUCT_AI_USAGE_PROGRAMMATIC
  );
export const getProductToolUsageProgrammaticId = () =>
  devOrProd(
    DEV_PRODUCT_TOOL_USAGE_PROGRAMMATIC,
    PROD_PRODUCT_TOOL_USAGE_PROGRAMMATIC
  );
export const getProductToolUsageUserId = () =>
  devOrProd(DEV_PRODUCT_TOOL_USAGE_USER, PROD_PRODUCT_TOOL_USAGE_USER);
export const getProductWorkspaceSeatId = () =>
  devOrProd(DEV_PRODUCT_WORKSPACE_SEAT, PROD_PRODUCT_WORKSPACE_SEAT);
export const getProductFreeMonthlyCreditId = () =>
  devOrProd(
    DEV_PRODUCT_FREE_MONTHLY_CREDITS,
    PROD_PRODUCT_FREE_MONTHLY_CREDITS
  );
export const getProductPrepaidCommitId = () =>
  devOrProd(DEV_PRODUCT_PREPAID_COMMIT, PROD_PRODUCT_PREPAID_COMMIT);
export const getProductPaygOverageId = () =>
  devOrProd(DEV_PRODUCT_PAYG_OVERAGE, PROD_PRODUCT_PAYG_OVERAGE);

// Packages
export const getPackageLegacyPro29Id = () =>
  devOrProd(DEV_PACKAGE_LEGACY_PRO_29, PROD_PACKAGE_LEGACY_PRO_29);
export const getPackageLegacyBusiness45Id = () =>
  devOrProd(DEV_PACKAGE_LEGACY_BUSINESS_45, PROD_PACKAGE_LEGACY_BUSINESS_45);
export const getPackageLegacyPro27AnnualId = () =>
  devOrProd(
    DEV_PACKAGE_LEGACY_PRO_27_ANNUAL,
    PROD_PACKAGE_LEGACY_PRO_27_ANNUAL
  );
