import { isDevelopment } from "@app/types/shared/env";

// Metronome product and billable metric IDs per environment.
// Generated by metronome_setup.ts, stable across runs.

// --- DEV (sandbox) ---

// Metrics
const DEV_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC =
  "2251e7d7-0a02-45ee-8bc3-edc0961a97ac";
const DEV_METRIC_LLM_PROVIDER_COST_USER =
  "7c9d1949-f221-4c16-9810-de4ca34e9fc6";
const DEV_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC =
  "9266a43d-8615-4df4-9ff3-3501c474d889";
const DEV_METRIC_TOOL_INVOCATIONS_USER = "c4558ec4-6d47-4246-aadc-9a0e74ca9393";
const DEV_METRIC_REGISTERED_USERS = "85c130a1-afc2-4135-8dae-72427b173aef";
const DEV_METRIC_MAU_1_MESSAGES = "5b6d92b6-6cf1-4348-809e-93dd751666d7";
const DEV_METRIC_MAU_5_MESSAGES = "3c264b7d-5437-4f19-abcc-3a9e9a4204e1";
const DEV_METRIC_MAU_10_MESSAGES = "152837b9-c662-4b86-bb4f-afabf18d4a40";

// Products
const DEV_PRODUCT_PROGRAMMATIC_USAGE = "8797d133-8301-4282-b3f2-fd811c9aa5b1";
const DEV_PRODUCT_AI_USAGE_USER = "4804c415-ec80-4125-9cb1-e71b0f268ca3";
const DEV_PRODUCT_AI_USAGE_PROGRAMMATIC =
  "80712396-3ffe-4471-901b-64730f8acf0f";
const DEV_PRODUCT_TOOL_USAGE_PROGRAMMATIC =
  "715493fd-8480-4755-a0b6-6e3c6cb4e156";
const DEV_PRODUCT_TOOL_USAGE_USER = "0a25bc30-4fb4-49f7-94e3-2b2a95c30bdd";
const DEV_PRODUCT_WORKSPACE_SEAT = "e1532e1d-4964-4656-b6db-070fafafc44c";
const DEV_PRODUCT_MAU_BILLING_1 = "06868f2b-f519-48c6-95e9-e28579306b2d";
const DEV_PRODUCT_MAU_BILLING_5 = "7193add5-a895-4f40-aaa3-80e49603355c";
const DEV_PRODUCT_MAU_BILLING_10 = "972dcb2f-0909-4444-8f29-ac26e042dbbc";
const DEV_PRODUCT_FREE_MONTHLY_CREDITS = "04f41dd1-ba27-42e3-93d5-6121712a4b67";
const DEV_PRODUCT_PREPAID_COMMIT = "5f4331b7-4bf6-488b-9a0c-51bd139ac91c";
const DEV_PRODUCT_PAYG_OVERAGE = "f4583c77-d226-48bb-97a3-46a8087b97fe";

// --- PROD (production) — TODO: update after running setup script in production ---

// Metrics
const PROD_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC =
  "3c4093e7-d429-4501-95d1-c51798969fbb";
const PROD_METRIC_LLM_PROVIDER_COST_USER =
  "b728ffa8-be00-406d-8054-25c1a94c7fe5";
const PROD_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC =
  "f3b12e98-e831-408a-a648-79d2cb1577a5";
const PROD_METRIC_TOOL_INVOCATIONS_USER =
  "3cf46f70-6bcd-4835-a6da-5a9dbe3235e2";
const PROD_METRIC_REGISTERED_USERS = "c5bfae56-8336-4ef1-9168-a4428fc92b32";
const PROD_METRIC_MAU_1_MESSAGES = "a98fb854-ab6b-4797-82ec-d7f576785ee7";
const PROD_METRIC_MAU_5_MESSAGES = "44b58b51-7a1d-4694-9e40-89e3c48566b8";
const PROD_METRIC_MAU_10_MESSAGES = "d347a6b3-5e74-4f8f-a756-1a4f6ee7c776";

// Products
const PROD_PRODUCT_PROGRAMMATIC_USAGE = "df7b4114-ca38-40bb-8812-1eb7787a6870";
const PROD_PRODUCT_AI_USAGE_USER = "add05755-6c13-4f38-97ba-4085022401ec";
const PROD_PRODUCT_AI_USAGE_PROGRAMMATIC =
  "fd5fd3e4-a7f8-46ad-86a8-20b4a90e35df";
const PROD_PRODUCT_TOOL_USAGE_PROGRAMMATIC =
  "109097e2-ed2d-4848-ba53-c4cbfa94cbdc";
const PROD_PRODUCT_TOOL_USAGE_USER = "0edd3afa-f89f-44c0-9e5d-dbace04cb133";
const PROD_PRODUCT_WORKSPACE_SEAT = "5c2e2986-1305-4406-96a2-2296e66b5a25";
const PROD_PRODUCT_MAU_BILLING_1 = "4135a928-9447-42a5-9b66-bb35b57c7155";
const PROD_PRODUCT_MAU_BILLING_5 = "565bef07-0348-4da8-8d4e-22de0ce856fe";
const PROD_PRODUCT_MAU_BILLING_10 = "c34f8b46-68e0-43d3-833e-753e3150ff07";
const PROD_PRODUCT_FREE_MONTHLY_CREDITS =
  "7379999c-5492-4e68-968f-345a26f6da63";
const PROD_PRODUCT_PREPAID_COMMIT = "1408c9fc-dea1-4269-bd6d-1bc0aa1f1218";
const PROD_PRODUCT_PAYG_OVERAGE = "f6b27a6e-86fc-4964-8076-371a912cee09";

// --- Credit type IDs (stable across envs unless noted) ---

// USD and EUR are the same in sandbox and production.
export const CREDIT_TYPE_USD_ID = "2714e483-4ff1-48e4-9e25-ac732e8f24f2";
export const CREDIT_TYPE_EUR_ID = "58f0be15-cc47-4220-bdaf-072ab0e44f96";

// AWU (Agentic Work Units) differs per environment.
const DEV_CREDIT_TYPE_AWU_ID = "1ad632f0-4e5a-44d6-a1bf-aa6f6bc550d8";
const PROD_CREDIT_TYPE_AWU_ID = "e53a841e-b741-4bc3-8148-f377c1fb2501";

/** Map Stripe currency code to Metronome credit type ID. */
export const CURRENCY_TO_CREDIT_TYPE_ID: Record<string, string> = {
  usd: CREDIT_TYPE_USD_ID,
  eur: CREDIT_TYPE_EUR_ID,
};

// --- Accessors ---

function devOrProd<T>(dev: T, prod: T): T {
  return isDevelopment() ? dev : prod;
}

export const getCreditTypeAwuId = () =>
  devOrProd(DEV_CREDIT_TYPE_AWU_ID, PROD_CREDIT_TYPE_AWU_ID);

// Metrics
export const getMetricLlmProviderCostProgrammaticId = () =>
  devOrProd(
    DEV_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC,
    PROD_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC
  );
export const getMetricLlmProviderCostUserId = () =>
  devOrProd(
    DEV_METRIC_LLM_PROVIDER_COST_USER,
    PROD_METRIC_LLM_PROVIDER_COST_USER
  );
export const getMetricToolInvocationsProgrammaticId = () =>
  devOrProd(
    DEV_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC,
    PROD_METRIC_TOOL_INVOCATIONS_PROGRAMMATIC
  );
export const getMetricToolInvocationsUserId = () =>
  devOrProd(
    DEV_METRIC_TOOL_INVOCATIONS_USER,
    PROD_METRIC_TOOL_INVOCATIONS_USER
  );
export const getMetricRegisteredUsersId = () =>
  devOrProd(DEV_METRIC_REGISTERED_USERS, PROD_METRIC_REGISTERED_USERS);
export const getMetricMau1Id = () =>
  devOrProd(DEV_METRIC_MAU_1_MESSAGES, PROD_METRIC_MAU_1_MESSAGES);
export const getMetricMau5Id = () =>
  devOrProd(DEV_METRIC_MAU_5_MESSAGES, PROD_METRIC_MAU_5_MESSAGES);
export const getMetricMau10Id = () =>
  devOrProd(DEV_METRIC_MAU_10_MESSAGES, PROD_METRIC_MAU_10_MESSAGES);

// Products
export const getProductProgrammaticUsageId = () =>
  devOrProd(DEV_PRODUCT_PROGRAMMATIC_USAGE, PROD_PRODUCT_PROGRAMMATIC_USAGE);
export const getProductAiUsageUserId = () =>
  devOrProd(DEV_PRODUCT_AI_USAGE_USER, PROD_PRODUCT_AI_USAGE_USER);
export const getProductAiUsageProgrammaticId = () =>
  devOrProd(
    DEV_PRODUCT_AI_USAGE_PROGRAMMATIC,
    PROD_PRODUCT_AI_USAGE_PROGRAMMATIC
  );
export const getProductToolUsageProgrammaticId = () =>
  devOrProd(
    DEV_PRODUCT_TOOL_USAGE_PROGRAMMATIC,
    PROD_PRODUCT_TOOL_USAGE_PROGRAMMATIC
  );
export const getProductToolUsageUserId = () =>
  devOrProd(DEV_PRODUCT_TOOL_USAGE_USER, PROD_PRODUCT_TOOL_USAGE_USER);
export const getProductWorkspaceSeatId = () =>
  devOrProd(DEV_PRODUCT_WORKSPACE_SEAT, PROD_PRODUCT_WORKSPACE_SEAT);
export const getProductFreeMonthlyCreditId = () =>
  devOrProd(
    DEV_PRODUCT_FREE_MONTHLY_CREDITS,
    PROD_PRODUCT_FREE_MONTHLY_CREDITS
  );
export const getProductPrepaidCommitId = () =>
  devOrProd(DEV_PRODUCT_PREPAID_COMMIT, PROD_PRODUCT_PREPAID_COMMIT);
export const getProductPaygOverageId = () =>
  devOrProd(DEV_PRODUCT_PAYG_OVERAGE, PROD_PRODUCT_PAYG_OVERAGE);
export const getProductMauBilling1Id = () =>
  devOrProd(DEV_PRODUCT_MAU_BILLING_1, PROD_PRODUCT_MAU_BILLING_1);
export const getProductMauBilling5Id = () =>
  devOrProd(DEV_PRODUCT_MAU_BILLING_5, PROD_PRODUCT_MAU_BILLING_5);
export const getProductMauBilling10Id = () =>
  devOrProd(DEV_PRODUCT_MAU_BILLING_10, PROD_PRODUCT_MAU_BILLING_10);
