import type { MembershipSeatType } from "@app/types/memberships";
import { isDevelopment } from "@app/types/shared/env";
import { assertNever } from "@app/types/shared/utils/assert_never";
import type { Subscription } from "@metronome/sdk/resources";

// Metronome product and billable metric IDs per environment.
// Generated by metronome_setup.ts, stable across runs.

// --- DEV (sandbox) ---

// Metrics
const DEV_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC =
  "e02846b3-956c-48bc-9fd1-162061aed624";
const DEV_METRIC_TOOL_INVOCATIONS = "79af757d-e4cf-4313-ab55-8d5a22cd9aa1";
const DEV_METRIC_LLM_PROVIDER_COST_AWU = "98a768d3-e3dd-423b-a97e-5ee348dc55b8";

// Products
const DEV_PRODUCT_PROGRAMMATIC_USAGE = "daaf92ec-d0a7-444d-972e-a2d48c7edd0c";
const DEV_PRODUCT_AI_USAGE = "8b2baf8c-5edc-451d-877f-0eeef554afa9";
const DEV_PRODUCT_TOOL_USAGE = "e2028c42-ce77-4712-b08e-12f50d3e90f2";
const DEV_PRODUCT_WORKSPACE_SEAT = "e1532e1d-4964-4656-b6db-070fafafc44c";
const DEV_PRODUCT_PRO_SEAT = "db03586f-9e8d-4978-9a62-f51193182be3";
const DEV_PRODUCT_MAX_SEAT = "51b4ea2f-c4ed-4903-aba6-486d0bf61ac0";
const DEV_PRODUCT_MAU = "43db7690-939d-4a70-b4a4-b8ade43431f9";
const DEV_PRODUCT_MAU_TIER_1 = "efe2988a-4f84-4857-a716-0185c28f3e92";
const DEV_PRODUCT_MAU_TIER_2 = "a3ca48b5-8187-43ec-a692-eb45bb3f932e";
const DEV_PRODUCT_MAU_TIER_3 = "291e1da9-dc34-485c-af82-0b4ceb55ad38";
const DEV_PRODUCT_MAU_TIER_4 = "259e1c57-db52-4c58-aa13-c720f6894456";
const DEV_PRODUCT_MAU_TIER_5 = "05c1195a-a482-4101-a060-7579ba704936";
const DEV_PRODUCT_MAU_TIER_6 = "d617ee64-c74a-4a25-88ab-8be1bb6c780a";
const DEV_PRODUCT_MAU_COMMIT = "ababd7de-376d-41c6-a7da-40088af94433";
const DEV_PRODUCT_FREE_CREDITS = "04f41dd1-ba27-42e3-93d5-6121712a4b67";
const DEV_PRODUCT_EXCESS_CREDITS = "7e74d48b-44be-4e9c-9543-7136e6da8d96";
const DEV_PRODUCT_PREPAID_COMMIT = "5f4331b7-4bf6-488b-9a0c-51bd139ac91c";
const DEV_PRODUCT_PAYG_OVERAGE = "f4583c77-d226-48bb-97a3-46a8087b97fe";
const DEV_PRODUCT_SEAT_SUBSCRIPTION_CREDITS =
  "92f3466b-2423-4f2a-a8d1-0f6e9f7f0140";

// --- PROD (production) — TODO: update after running setup script in production ---

// Metrics
const PROD_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC =
  "3ad68bfb-7a59-49ad-b29e-54700fa0e6fa";
const PROD_METRIC_TOOL_INVOCATIONS = "e4597e40-6d3e-4002-b6a9-6df3e1eec643";
const PROD_METRIC_LLM_PROVIDER_COST_AWU =
  "162e09b0-a40b-4b09-b7b1-97bb057e901e";

// Products
const PROD_PRODUCT_PROGRAMMATIC_USAGE = "cb21a6da-9790-4ab4-bb2d-0a82d5fdf4f3";
const PROD_PRODUCT_AI_USAGE = "24f8b558-5ad1-4c41-890a-0e6ccf3ba0ea";
const PROD_PRODUCT_TOOL_USAGE = "079aeeba-becc-4013-ae1a-25cd56228f6e";
const PROD_PRODUCT_WORKSPACE_SEAT = "5c2e2986-1305-4406-96a2-2296e66b5a25";
const PROD_PRODUCT_PRO_SEAT = "19934ee2-fcf4-40a2-a57a-24f75b0c2b22";
const PROD_PRODUCT_MAX_SEAT = "8a92cf6a-8e0b-416c-9b46-9c715eff0c89";
const PROD_PRODUCT_MAU = "7715e34d-3ec3-475e-b0eb-3d04578a958b";
const PROD_PRODUCT_MAU_TIER_1 = "d35bf462-98a8-4d3b-8e01-876c7bf6fc57";
const PROD_PRODUCT_MAU_TIER_2 = "829f5d32-d2ae-4a3a-bb64-0e2630857abc";
const PROD_PRODUCT_MAU_TIER_3 = "b6e53edc-0d60-43b3-8398-25ce277b276f";
const PROD_PRODUCT_MAU_TIER_4 = "c6a30c0b-e4e9-4433-a7fa-380dd80da245";
const PROD_PRODUCT_MAU_TIER_5 = "d4298ee0-7cb6-4bb2-9e3a-a26c19b93b22";
const PROD_PRODUCT_MAU_TIER_6 = "fea4cf80-90ee-499d-85d1-4c9ea8a48224";
const PROD_PRODUCT_MAU_COMMIT = "3f6f42d2-149a-4d9c-bbd1-5add7e7ee5c2";
const PROD_PRODUCT_FREE_CREDITS = "7379999c-5492-4e68-968f-345a26f6da63";
const PROD_PRODUCT_EXCESS_CREDITS = "26f0023b-e123-4154-a82d-104451fba068";
const PROD_PRODUCT_PREPAID_COMMIT = "1408c9fc-dea1-4269-bd6d-1bc0aa1f1218";
const PROD_PRODUCT_PAYG_OVERAGE = "f6b27a6e-86fc-4964-8076-371a912cee09";
const PROD_PRODUCT_SEAT_SUBSCRIPTION_CREDITS =
  "03faa744-c1ab-4b94-aaf1-5fdaec89e11a";

// --- Credit type IDs (stable across envs unless noted) ---

// USD and EUR are the same in sandbox and production.
export const CREDIT_TYPE_USD_ID = "2714e483-4ff1-48e4-9e25-ac732e8f24f2";
export const CREDIT_TYPE_EUR_ID = "58f0be15-cc47-4220-bdaf-072ab0e44f96";

export const PLAN_CODE_CUSTOM_FIELD_KEY = "DUST_PLAN_CODE";

export const PRO_SEAT_CREDIT_NAME = "Pro Seat Credits";
export const MAX_SEAT_CREDIT_NAME = "Max Seat Credits";
export const PRO_SEAT_PRODUCT_NAME = "Pro Seat";
export const MAX_SEAT_PRODUCT_NAME = "Max Seat";

// AWU (Agentic Work Units) differs per environment.
export const DEV_CREDIT_TYPE_AWU_ID = "eb003cc7-4935-467d-a41c-c1738c1c9dc2";
export const PROD_CREDIT_TYPE_AWU_ID = "8dfc9846-a38e-44f8-a625-bd9372af681c";

// Programmatic USD differs per environment.
export const DEV_CREDIT_TYPE_PROG_USD_ID =
  "713dda3d-4e9c-456f-91cf-c79cf5b71412";
export const PROD_CREDIT_TYPE_PROG_USD_ID =
  "db4b2912-4dfc-43ee-a910-1a894b89fe60";

/** Map Stripe currency code to Metronome credit type ID. */
export const CURRENCY_TO_CREDIT_TYPE_ID: Record<string, string> = {
  usd: CREDIT_TYPE_USD_ID,
  eur: CREDIT_TYPE_EUR_ID,
};

// --- Accessors ---

function devOrProd<T>(dev: T, prod: T): T {
  return isDevelopment() ? dev : prod;
}

export const getCreditTypeAwuId = () =>
  devOrProd(DEV_CREDIT_TYPE_AWU_ID, PROD_CREDIT_TYPE_AWU_ID);

export const getCreditTypeProgrammaticUsdId = () =>
  devOrProd(DEV_CREDIT_TYPE_PROG_USD_ID, PROD_CREDIT_TYPE_PROG_USD_ID);

// Metrics
export const getMetricLlmProviderCostProgrammaticId = () =>
  devOrProd(
    DEV_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC,
    PROD_METRIC_LLM_PROVIDER_COST_PROGRAMMATIC
  );
export const getMetricToolInvocationsId = () =>
  devOrProd(DEV_METRIC_TOOL_INVOCATIONS, PROD_METRIC_TOOL_INVOCATIONS);
export const getMetricLlmProviderCostAwuId = () =>
  devOrProd(
    DEV_METRIC_LLM_PROVIDER_COST_AWU,
    PROD_METRIC_LLM_PROVIDER_COST_AWU
  );

// Products
export const getProductProgrammaticUsageId = () =>
  devOrProd(DEV_PRODUCT_PROGRAMMATIC_USAGE, PROD_PRODUCT_PROGRAMMATIC_USAGE);
export const getProductAiUsageId = () =>
  devOrProd(DEV_PRODUCT_AI_USAGE, PROD_PRODUCT_AI_USAGE);
export const getProductToolUsageId = () =>
  devOrProd(DEV_PRODUCT_TOOL_USAGE, PROD_PRODUCT_TOOL_USAGE);
export const getProductWorkspaceSeatId = () =>
  devOrProd(DEV_PRODUCT_WORKSPACE_SEAT, PROD_PRODUCT_WORKSPACE_SEAT);
export const getProductProSeatId = () =>
  devOrProd(DEV_PRODUCT_PRO_SEAT, PROD_PRODUCT_PRO_SEAT);
export const getProductMaxSeatId = () =>
  devOrProd(DEV_PRODUCT_MAX_SEAT, PROD_PRODUCT_MAX_SEAT);
export const getProductMauId = () =>
  devOrProd(DEV_PRODUCT_MAU, PROD_PRODUCT_MAU);
export const getProductMauCommitId = () =>
  devOrProd(DEV_PRODUCT_MAU_COMMIT, PROD_PRODUCT_MAU_COMMIT);
export const getProductFreeCreditId = () =>
  devOrProd(DEV_PRODUCT_FREE_CREDITS, PROD_PRODUCT_FREE_CREDITS);
export const getProductExcessCreditsId = () =>
  devOrProd(DEV_PRODUCT_EXCESS_CREDITS, PROD_PRODUCT_EXCESS_CREDITS);
export const getProductPrepaidCommitId = () =>
  devOrProd(DEV_PRODUCT_PREPAID_COMMIT, PROD_PRODUCT_PREPAID_COMMIT);
export const getProductPaygOverageId = () =>
  devOrProd(DEV_PRODUCT_PAYG_OVERAGE, PROD_PRODUCT_PAYG_OVERAGE);
export const getProductSeatSubscriptionCreditsId = () =>
  devOrProd(
    DEV_PRODUCT_SEAT_SUBSCRIPTION_CREDITS,
    PROD_PRODUCT_SEAT_SUBSCRIPTION_CREDITS
  );

export const PRO_SEAT_MONTHLY_AWU_CREDITS = 8000;
export const MAX_SEAT_MONTHLY_AWU_CREDITS = 40000;

// AWU commit priorities — lower number is consumed first.
// Seat allocations are consumed before purchased top-ups.
export const AWU_PRIORITY_SEAT_ALLOCATION = 200;
export const AWU_PRIORITY_PURCHASED_COMMIT = 300;

export function getAwuAllocationForSeatType(
  seatType: MembershipSeatType | null
): number {
  if (seatType === null) {
    return 0;
  }
  switch (seatType) {
    case "max":
      return MAX_SEAT_MONTHLY_AWU_CREDITS;
    case "pro":
      return PRO_SEAT_MONTHLY_AWU_CREDITS;
    case "workspace":
    case "free":
      return 0;
    default:
      return assertNever(seatType);
  }
}

export const getSeatProductIds = (): Set<string> =>
  new Set([
    getProductSeatSubscriptionCreditsId(),
    getProductWorkspaceSeatId(),
    getProductProSeatId(),
    getProductMaxSeatId(),
  ]);

// tier product accessors — ordered array for indexed access.
export const MAX_MAU_TIERS = 6;

export const getProductMauTierIds = (): string[] => [
  devOrProd(DEV_PRODUCT_MAU_TIER_1, PROD_PRODUCT_MAU_TIER_1),
  devOrProd(DEV_PRODUCT_MAU_TIER_2, PROD_PRODUCT_MAU_TIER_2),
  devOrProd(DEV_PRODUCT_MAU_TIER_3, PROD_PRODUCT_MAU_TIER_3),
  devOrProd(DEV_PRODUCT_MAU_TIER_4, PROD_PRODUCT_MAU_TIER_4),
  devOrProd(DEV_PRODUCT_MAU_TIER_5, PROD_PRODUCT_MAU_TIER_5),
  devOrProd(DEV_PRODUCT_MAU_TIER_6, PROD_PRODUCT_MAU_TIER_6),
];

/**
 * Map a membership seat type to the Metronome product that bills it.
 * Returns `undefined` for seat types that are not billed (e.g. "free").
 */
export function getProductIdForSeatType(
  seatType: MembershipSeatType
): string | undefined {
  switch (seatType) {
    case "free":
      return undefined;
    case "workspace":
      return getProductWorkspaceSeatId();
    case "pro":
      return getProductProSeatId();
    case "max":
      return getProductMaxSeatId();
    default:
      return assertNever(seatType);
  }
}

/**
 * Reverse of `getProductIdForSeatType`: returns the seat type that a Metronome
 * seat product bills. Returns `undefined` if the product is not a known seat
 * product.
 */
export function getSeatTypeForProductId(
  product: Subscription.SubscriptionRate.Product
): MembershipSeatType | undefined {
  // Compare on product name as it's more stable than the id, changing across products redeplpyments.
  if (product.name === "Workspace Seat") {
    return "workspace";
  }
  if (product.name === "Pro Seat") {
    return "pro";
  }
  if (product.name === "Max Seat") {
    return "max";
  }
  return undefined;
}
