POST /_aliases
{
  "actions": [
    { "remove": { "index": "front.agent_document_outputs*", "alias": "front.agent_document_outputs" } },
    { "add":    { "index": "front.agent_document_outputs_1", "alias": "front.agent_document_outputs", "is_write_index": true } }
  ]
}

