PUT /front.agent_message_analytics_2/_mapping
{
  "properties": {
    "cost": {
      "type": "object",
      "properties": {
        "billable_awu": {
          "type": "integer"
        }
      }
    }
  }
}
