import { useCallback, useEffect, useRef } from "react";

import { isEmptyString } from "@app/types";

interface UseAutoGenerateOnBlurOptions {
  /**
   * Current value of the field being auto-generated.
   */
  fieldValue: string | null | undefined;
  /**
   * Function to trigger the auto-generation. Return true if generation succeeded.
   */
  onGenerate: () => boolean | Promise<boolean>;
  /**
   * Event names to listen for that should trigger auto-generation.
   */
  blurEventNames: string[];
}

interface UseAutoGenerateOnBlurResult {
  /**
   * Call this when the field value is programmatically set via auto-generation.
   */
  markAsAutoGenerated: () => void;
  /**
   * Call this when the user manually changes the field value.
   */
  markAsUserEdited: () => void;
  /**
   * Trigger generation manually (e.g., from a button click).
   */
  generate: () => Promise<void>;
}

/**
 * Hook to auto-generate a field value on blur of related fields.
 *
 * Only triggers generation if:
 * - The field was previously auto-generated, OR
 * - The field is empty
 *
 * This prevents overwriting user-entered values while allowing
 * re-generation when the user hasn't manually edited the field.
 */
export function useAutoGenerateOnBlur({
  fieldValue,
  onGenerate,
  blurEventNames,
}: UseAutoGenerateOnBlurOptions): UseAutoGenerateOnBlurResult {
  const fieldWasAutoGeneratedRef = useRef(false);

  const markAsAutoGenerated = useCallback(() => {
    fieldWasAutoGeneratedRef.current = true;
  }, []);

  const markAsUserEdited = useCallback(() => {
    fieldWasAutoGeneratedRef.current = false;
  }, []);

  const generate = useCallback(async () => {
    const success = await onGenerate();
    if (success) {
      markAsAutoGenerated();
    }
  }, [onGenerate, markAsAutoGenerated]);

  const handleBlur = useCallback(() => {
    if (fieldWasAutoGeneratedRef.current || isEmptyString(fieldValue)) {
      void generate();
    }
  }, [generate, fieldValue]);

  useEffect(() => {
    for (const eventName of blurEventNames) {
      window.addEventListener(eventName, handleBlur);
    }

    return () => {
      for (const eventName of blurEventNames) {
        window.removeEventListener(eventName, handleBlur);
      }
    };
  }, [handleBlur, blurEventNames]);

  return {
    markAsAutoGenerated,
    markAsUserEdited,
    generate,
  };
}
