import type { ModelIdType } from "@app/types";
import {
  CLAUDE_3_5_HAIKU_DEFAULT_MODEL_CONFIG,
  CLAUDE_3_OPUS_DEFAULT_MODEL_CONFIG,
  CLAUDE_4_5_HAIKU_DEFAULT_MODEL_CONFIG,
  CLAUDE_4_5_SONNET_DEFAULT_MODEL_CONFIG,
  CLAUDE_4_OPUS_DEFAULT_MODEL_CONFIG,
  CLAUDE_4_SONNET_DEFAULT_MODEL_CONFIG,
} from "@app/types";

export const ANTHROPIC_WHITELISTED_NON_REASONING_MODEL_IDS: ModelIdType[] = [
  CLAUDE_3_OPUS_DEFAULT_MODEL_CONFIG.modelId,
  CLAUDE_3_5_HAIKU_DEFAULT_MODEL_CONFIG.modelId,
];

export const ANTHROPIC_WHITELISTED_REASONING_MODEL_IDS: ModelIdType[] = [
  CLAUDE_4_OPUS_DEFAULT_MODEL_CONFIG.modelId,
  CLAUDE_4_SONNET_DEFAULT_MODEL_CONFIG.modelId,
  CLAUDE_4_5_SONNET_DEFAULT_MODEL_CONFIG.modelId,
  CLAUDE_4_5_HAIKU_DEFAULT_MODEL_CONFIG.modelId,
];

export const ANTHROPIC_WHITELISTED_MODEL_IDS: ModelIdType[] = [
  ...ANTHROPIC_WHITELISTED_NON_REASONING_MODEL_IDS,
  ...ANTHROPIC_WHITELISTED_REASONING_MODEL_IDS,
];

export function isAnthropicWhitelistedModelId(
  modelId: ModelIdType
): modelId is AnthropicWhitelistedModelId {
  return new Set<string>(ANTHROPIC_WHITELISTED_MODEL_IDS).has(modelId);
}

export type AnthropicWhitelistedModelId =
  (typeof ANTHROPIC_WHITELISTED_MODEL_IDS)[number];
