import { describe, expect, it } from "bun:test";
import { removeDirenvBlock } from "../../src/lib/direnv";

describe("direnv", () => {
  describe("removeDirenvBlock", () => {
    it("removes only the matching dust-hive block", () => {
      const content = [
        "use flake",
        "",
        "# >>> dust-hive adopted >>>",
        "# Auto-generated by dust-hive - sources environment for this worktree",
        'source "/Users/me/.dust-hive/envs/adopted/env.sh"',
        "# <<< dust-hive adopted <<<",
        "",
        "layout node",
        "",
      ].join("\n");

      expect(removeDirenvBlock(content, "adopted")).toBe("use flake\n\nlayout node\n");
    });

    it("leaves unrelated content unchanged when the block is absent", () => {
      expect(removeDirenvBlock("use flake\n", "adopted")).toBe("use flake\n");
    });
  });
});
