import { describe, expect, it } from "bun:test";
import { generateEnvSh } from "../../src/lib/envgen";
import { calculatePorts } from "../../src/lib/ports";

describe("envgen", () => {
  describe("generateEnvSh", () => {
    const ports = calculatePorts(10000);

    it("includes shebang and header comment", () => {
      const content = generateEnvSh("test", ports);
      expect(content.startsWith("#!/bin/bash")).toBe(true);
      expect(content).toContain("Generated by dust-hive for environment: test");
    });

    it("sources global config.env", () => {
      const content = generateEnvSh("test", ports);
      // Uses absolute path from CONFIG_ENV_PATH constant
      expect(content).toContain("source");
      expect(content).toContain(".dust-hive/config.env");
    });

    it("exports correct port values", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain("export PORT=10000");
      expect(content).toContain("export CORE_PORT=10001");
      expect(content).toContain("export CONNECTORS_PORT=10002");
      expect(content).toContain("export OAUTH_PORT=10006");
    });

    it("exports temporal namespaces", () => {
      const content = generateEnvSh("my-feature", ports);
      expect(content).toContain("export TEMPORAL_NAMESPACE=dust-hive-my-feature");
      expect(content).toContain("export TEMPORAL_AGENT_NAMESPACE=dust-hive-my-feature-agent");
      expect(content).toContain(
        "export TEMPORAL_CONNECTORS_NAMESPACE=dust-hive-my-feature-connectors"
      );
      expect(content).toContain(
        "export TEMPORAL_RELOCATION_NAMESPACE=dust-hive-my-feature-relocation"
      );
    });

    it("exports init script variables", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain("export POSTGRES_PORT=10432");
      expect(content).toContain("export POSTGRES_HOST=localhost");
      expect(content).toContain("export QDRANT_URL=http://localhost:10333");
      expect(content).toContain("export ELASTICSEARCH_INIT_URL=http://localhost:10200");
    });

    it("exports inter-service URLs", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain("export CORE_API=http://localhost:10001");
      expect(content).toContain("export CONNECTORS_API=http://localhost:10002");
      expect(content).toContain("export OAUTH_API=http://localhost:10006");
      expect(content).toContain("export DUST_FRONT_API=http://localhost:10000");
      expect(content).toContain("export DUST_CLIENT_FACING_URL=http://localhost:10000");
      expect(content).toContain("export NEXT_PUBLIC_DUST_CLIENT_FACING_URL=http://localhost:10000");
      expect(content).toContain("export DUST_AUTH_REDIRECT_BASE_URL=http://localhost:3000");
      expect(content).toContain("export CONNECTORS_PUBLIC_URL=http://localhost:10002");
    });

    it("exports database URIs with correct port", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain(
        "export FRONT_DATABASE_URI=postgres://dev:dev@localhost:10432/dust_front"
      );
      expect(content).toContain(
        "export CORE_DATABASE_URI=postgres://dev:dev@localhost:10432/dust_api"
      );
      expect(content).toContain(
        "export CONNECTORS_DATABASE_URI=postgres://dev:dev@localhost:10432/dust_connectors"
      );
      expect(content).toContain(
        "export OAUTH_DATABASE_URI=postgres://dev:dev@localhost:10432/dust_oauth"
      );
    });

    it("exports read replica URIs", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain("export FRONT_DATABASE_READ_REPLICA_URI=");
      expect(content).toContain("export CORE_DATABASE_READ_REPLICA_URI=");
      expect(content).toContain("export CONNECTORS_DATABASE_READ_REPLICA_URI=");
    });

    it("exports service URIs", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain("export REDIS_URI=redis://localhost:10379");
      expect(content).toContain("export REDIS_CACHE_URI=redis://localhost:10379");
      expect(content).toContain("export QDRANT_CLUSTER_0_URL=http://127.0.0.1:10334");
      expect(content).toContain("export ELASTICSEARCH_URL=http://localhost:10200");
      expect(content).toContain("export TEXT_EXTRACTION_URL=http://localhost:10998");
    });

    it("uses different ports for second environment", () => {
      const secondEnvPorts = calculatePorts(11000);
      const content = generateEnvSh("second", secondEnvPorts);

      expect(content).toContain("export PORT=11000");
      expect(content).toContain("export CORE_PORT=11001");
      expect(content).toContain("export POSTGRES_PORT=11432");
      expect(content).toContain("export REDIS_URI=redis://localhost:11379");
      expect(content).toContain("FRONT_DATABASE_URI=postgres://dev:dev@localhost:11432/dust_front");
    });

    it("uses environment name in temporal namespaces", () => {
      const content1 = generateEnvSh("env-a", ports);
      const content2 = generateEnvSh("env-b", ports);

      expect(content1).toContain("TEMPORAL_NAMESPACE=dust-hive-env-a");
      expect(content2).toContain("TEMPORAL_NAMESPACE=dust-hive-env-b");
    });

    it("includes section comments for organization", () => {
      const content = generateEnvSh("test", ports);
      expect(content).toContain("# === Ports");
      expect(content).toContain("# === Temporal namespaces");
      expect(content).toContain("# === Init script vars");
      expect(content).toContain("# === Inter-service URLs");
      expect(content).toContain("# === Database URIs");
      expect(content).toContain("# === Service URIs");
    });

    it("ends with newline", () => {
      const content = generateEnvSh("test", ports);
      expect(content.endsWith("\n")).toBe(true);
    });
  });
});
