apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-tika-config
data:
  DD_ENV: "prod"
  DD_SERVICE: "apache-tika"
  DD_LOGS_INJECTION: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
  JAVA_OPTS: "-Xms2g -Xmx3g -XX:MaxMetaspaceSize=256m"
