apiVersion: v1
kind: ConfigMap
metadata:
  name: front-qa-config
data:
  DD_ENV: "prod"
  DD_SERVICE: "front-qa"
  NODE_OPTIONS: "-r dd-trace/init"
  DD_LOGS_INJECTION: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
  NODE_ENV: "production"
