import { PROCESS_ACTION_TOP_K } from "@app/lib/actions/constants";
import { MCPError } from "@app/lib/actions/mcp_errors";
import type { DataSourcesToolConfigurationType } from "@app/lib/actions/mcp_internal_actions/input_schemas";
import type { ToolHandlers } from "@app/lib/actions/mcp_internal_actions/tool_definition";
import { buildTools } from "@app/lib/actions/mcp_internal_actions/tool_definition";
import { shouldAutoGenerateTags } from "@app/lib/actions/mcp_internal_actions/tools/tags/utils";
import type { ToolContextType } from "@app/lib/actions/types";
import {
  isLightServerSideMCPToolConfiguration,
  isServerSideMCPServerConfiguration,
} from "@app/lib/actions/types/guards";
import type { ProcessActionOutputsType } from "@app/lib/api/actions/servers/extract_data/helpers";
import {
  generateProcessToolOutput,
  getCoreDataSourceSearchCriterias,
  getPromptForProcessDustApp,
} from "@app/lib/api/actions/servers/extract_data/helpers";
import {
  EXTRACT_DATA_MAIN_TOOL_NAME,
  makeExtractDataBaseToolsMetadata,
  makeExtractDataToolsWithTagsMetadata,
} from "@app/lib/api/actions/servers/extract_data/metadata";
import { executeFindTags } from "@app/lib/api/actions/tools/find_tags";
import { processDataSources } from "@app/lib/api/assistant/process_data_sources";
import type { Authenticator } from "@app/lib/auth";
import {
  isJSONSchemaObject,
  validateJsonSchema,
} from "@app/lib/utils/json_schemas";
import { Err, Ok } from "@app/types/shared/result";
import type { TimeFrame } from "@app/types/shared/utils/time_frame";
import assert from "assert";
import type { JSONSchema7 as JSONSchema } from "json-schema";

function hasConfiguredJsonSchema(toolContext?: ToolContextType) {
  if (
    toolContext?.listToolsContext &&
    isServerSideMCPServerConfiguration(
      toolContext.listToolsContext.agentActionConfiguration
    )
  ) {
    return (
      toolContext.listToolsContext.agentActionConfiguration.jsonSchema !== null
    );
  }

  if (
    toolContext?.runContext &&
    isLightServerSideMCPToolConfiguration(
      toolContext.runContext.toolConfiguration
    )
  ) {
    return toolContext.runContext.toolConfiguration.jsonSchema !== null;
  }

  return false;
}

function hasConfiguredTimeFrame(toolContext?: ToolContextType) {
  if (
    toolContext?.listToolsContext &&
    isServerSideMCPServerConfiguration(
      toolContext.listToolsContext.agentActionConfiguration
    )
  ) {
    return (
      toolContext.listToolsContext.agentActionConfiguration.timeFrame !== null
    );
  }

  if (
    toolContext?.runContext &&
    isLightServerSideMCPToolConfiguration(
      toolContext.runContext.toolConfiguration
    )
  ) {
    return toolContext.runContext.toolConfiguration.timeFrame !== null;
  }

  return false;
}

// Create tools with access to auth via closure
export function createExtractDataTools(
  auth: Authenticator,
  toolContext?: ToolContextType
) {
  const areTagsDynamic = toolContext
    ? shouldAutoGenerateTags(toolContext)
    : false;
  const isJsonSchemaConfigured = hasConfiguredJsonSchema(toolContext);
  const isTimeFrameConfigured = hasConfiguredTimeFrame(toolContext);

  async function extractFunction({
    dataSources,
    objective,
    jsonSchema,
    timeFrame,
    tagsIn,
    tagsNot,
  }: {
    dataSources: DataSourcesToolConfigurationType;
    objective: string;
    jsonSchema: JSONSchema;
    timeFrame?: TimeFrame;
    tagsIn?: string[];
    tagsNot?: string[];
  }) {
    // Unwrap and prepare variables.
    assert(
      toolContext?.runContext,
      "agentLoopContext is required to run the extract_data tool"
    );
    const { agentConfiguration, conversation } = toolContext.runContext;
    const { model } = agentConfiguration;

    // Defensive handling: parse jsonSchema if it arrives as a JSON string.
    // This can happen when the LLM generates a stringified JSON schema instead of an object,
    // or when the schema is stored as a string in the database.
    if (typeof jsonSchema === "string") {
      try {
        jsonSchema = JSON.parse(jsonSchema);
      } catch {
        return new Err(
          new MCPError(
            `Invalid jsonSchema: expected a valid JSON object but received a malformed string`,
            { tracked: false }
          )
        );
      }
    }

    const jsonSchemaForExtraction =
      "mimeType" in jsonSchema
        ? Object.fromEntries(
            Object.entries(jsonSchema).filter(([key]) => key !== "mimeType")
          )
        : jsonSchema;

    const timeFrameForExtraction =
      timeFrame && "mimeType" in timeFrame
        ? {
            duration: timeFrame.duration,
            unit: timeFrame.unit,
          }
        : timeFrame;

    // Validate the jsonSchema structure regardless of whether it was pre-configured
    // or generated by the LLM at runtime, to catch malformed schemas early before
    // sending them to the LLM.
    const validationResult = validateJsonSchema(jsonSchemaForExtraction, {
      // LLMs often do this mistake which Mistral considers as invalid JSON schema.
      enforceRequiredFields: true,
    });
    if (!validationResult.isValid) {
      return new Err(
        new MCPError(
          `Invalid jsonSchema: ${validationResult.error ?? "unknown error"}`,
          { tracked: false }
        )
      );
    }

    const prompt = await getPromptForProcessDustApp({
      auth,
      agentConfiguration,
      conversation,
    });

    const coreDataSourceSearchCriteriasResult =
      await getCoreDataSourceSearchCriterias(auth, dataSources, {
        timeFrame: timeFrameForExtraction,
        tagsIn,
        tagsNot,
      });
    if (coreDataSourceSearchCriteriasResult.isErr()) {
      return new Err(
        new MCPError(
          `Error getting search criteria in extract data action: ${coreDataSourceSearchCriteriasResult.error.message}`
        )
      );
    }

    const res = await processDataSources({
      auth,
      coreDataSourceSearchCriterias: coreDataSourceSearchCriteriasResult.value,
      model,
      prompt,
      objective,
      jsonSchema: jsonSchemaForExtraction,
      topK: PROCESS_ACTION_TOP_K,
    });

    if (res.isErr()) {
      return new Err(
        new MCPError(`Error running extract data action: ${res.error.message}`)
      );
    }

    const outputs: ProcessActionOutputsType = {
      data: res.value.data,
      total_documents: res.value.totalDocuments,
    };

    const result = await generateProcessToolOutput({
      auth,
      conversation,
      outputs,
      jsonSchema: jsonSchemaForExtraction,
      timeFrame: timeFrameForExtraction ?? null,
      objective,
    });
    if (result.isErr()) {
      return new Err(new MCPError(result.error.message));
    }

    return new Ok(result.value.processToolOutput);
  }

  if (!areTagsDynamic) {
    const toolsMetadata = makeExtractDataBaseToolsMetadata({
      isJsonSchemaConfigured,
      isTimeFrameConfigured,
    });

    // Return base tools without tags
    const handlers: ToolHandlers<typeof toolsMetadata> = {
      [EXTRACT_DATA_MAIN_TOOL_NAME]: async (params) => {
        return extractFunction(params);
      },
    };
    return buildTools(toolsMetadata, handlers);
  }

  const toolsMetadata = makeExtractDataToolsWithTagsMetadata({
    isJsonSchemaConfigured,
    isTimeFrameConfigured,
  });

  // Return tools with tags support
  const handlers: ToolHandlers<typeof toolsMetadata> = {
    [EXTRACT_DATA_MAIN_TOOL_NAME]: async (params) => {
      return extractFunction(params);
    },
    find_tags: async ({ query, dataSources }) => {
      return executeFindTags(auth, query, dataSources);
    },
  };
  return buildTools(toolsMetadata, handlers);
}
