-- Migration created on Nov 07, 2024
ALTER TABLE "zendesk_tickets" ALTER COLUMN "brandId" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "brandId" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "brandId" TYPE BIGINT;
ALTER TABLE "zendesk_tickets" ALTER COLUMN "groupId" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "groupId" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "groupId" TYPE BIGINT;
ALTER TABLE "zendesk_tickets" ALTER COLUMN "assigneeId" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "assigneeId" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "assigneeId" TYPE BIGINT;
ALTER TABLE "zendesk_tickets" ALTER COLUMN "organizationId" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "organizationId" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "organizationId" TYPE BIGINT;
ALTER TABLE "zendesk_tickets" ALTER COLUMN "name" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "name" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "name" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "satisfactionScore" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "satisfactionScore" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "satisfactionScore" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "satisfactionComment" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "satisfactionComment" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "satisfactionComment" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "subject" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "subject" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "subject" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "description" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "description" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "description" TYPE TEXT;
ALTER TABLE "zendesk_tickets" ALTER COLUMN "requesterMail" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "requesterMail" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "requesterMail" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "status" SET NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "status" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "status" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "tags" SET NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "tags" SET DEFAULT ARRAY[]::VARCHAR(255)[];ALTER TABLE "zendesk_tickets" ALTER COLUMN "tags" TYPE VARCHAR(255)[];
ALTER TABLE "zendesk_tickets" ALTER COLUMN "url" SET NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "url" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "url" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "type" DROP NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "type" DROP DEFAULT;ALTER TABLE "zendesk_tickets" ALTER COLUMN "type" TYPE VARCHAR(255);
ALTER TABLE "zendesk_tickets" ALTER COLUMN "customFields" SET NOT NULL;ALTER TABLE "zendesk_tickets" ALTER COLUMN "customFields" SET DEFAULT ARRAY[]::VARCHAR(255)[];ALTER TABLE "zendesk_tickets" ALTER COLUMN "customFields" TYPE VARCHAR(255)[];