steps:
  - id: "Build Container Image"
    name: "ghcr.io/depot/cli:latest"
    script: |
      #!/usr/bin/env bash
      
      # determine config suffix based on image name
      if [[ ${_IMAGE_NAME} == *"qa"* ]]; then
        CONFIG_SUFFIX="qa"
      elif [[ ${_IMAGE_NAME} == *"edge"* ]]; then
        CONFIG_SUFFIX="edge"
      else
        CONFIG_SUFFIX="prod"
      fi
      
      CONFIG_FILE=".github/configs/${_REGION}/.env.${CONFIG_SUFFIX}"
      
      build_args=()
      while IFS='=' read -r key value; do
        if [[ -n "$key" ]]; then
          key=$(echo "$key" | xargs)
          value=$(echo "$value" | xargs)
          build_args+=("--build-arg" "${key}=${value}")
        fi
      done < "$CONFIG_FILE"
      
      depot build \
        --project 3vz0lnf16v \
        --provenance=false \
        --platform linux/amd64 \
        --cache-from type=gha,scope=${_IMAGE_NAME} \
        --cache-to type=gha,mode=max,scope=${_IMAGE_NAME} \
        --build-context platform=linux/amd64 \
        --progress=plain \
        -t ${_REGION}-docker.pkg.dev/${_PROJECT_ID}/dust-images/${_IMAGE_NAME}:${SHORT_SHA}-test \
        -f ${_DOCKERFILE_PATH} \
        --build-arg COMMIT_HASH=${SHORT_SHA} \
        ${build_args[@]} \
        --push \
        .

    secretEnv:
      - "DEPOT_TOKEN"

timeout: 1200s
serviceAccount: "projects/${_PROJECT_ID}/serviceAccounts/cloudbuild-runtime@${_PROJECT_ID}.iam.gserviceaccount.com"

availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT_ID/secrets/DEPOT_TOKEN/versions/latest
      env: DEPOT_TOKEN

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8