steps:
  - name: ghcr.io/depot/cli:latest
    args:
      - build
      - --project
      - 3vz0lnf16v
      - -t
      - gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest
      - --push
      - -f
      - ${_DOCKERFILE_PATH}
      - .
    secretEnv: ["DEPOT_TOKEN", "SENTRY_AUTH_TOKEN"]

timeout: 600s

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/DEPOT_TOKEN/versions/latest"
      env: DEPOT_TOKEN
    - versionName: "projects/$PROJECT_ID/secrets/SENTRY_AUTH_TOKEN/versions/latest"
      env: SENTRY_AUTH_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
