steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA",
        "-f",
        "Dockerfile",
        "--cache-from",
        "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA"]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA",
        "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest"]
images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest"
