steps:
  - name: ghcr.io/depot/cli:latest
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA
      - -t
      - gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest
      - --push
      - .
    secretEnv: ["DEPOT_TOKEN"]

availableSecrets:
  secretManager:
    - versionName: "projects/$PROJECT_ID/secrets/DEPOT_TOKEN/versions/latest"
      env: DEPOT_TOKEN

options:
  logging: CLOUD_LOGGING_ONLY
