steps:
  - name: ghcr.io/depot/cli:latest
    args:
      [
        "build",
        "--project",
        "3vz0lnf16v",
        "-t",
        "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest",
        "--push",
        "-f",
        "Dockerfile",
        ".",
      ]
    secretEnv: ["DEPOT_TOKEN"]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DEPOT_TOKEN/versions/latest
      env: DEPOT_TOKEN

images:
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/${_IMAGE_NAME}-image:latest"

options:
  logging: CLOUD_LOGGING_ONLY
