steps:
  - id: 'Build Container Image'
    name: 'ghcr.io/depot/cli:latest'
    script: |
      #!/usr/bin/env bash

      # determine config suffix based on image name
      if [[ ${_IMAGE_NAME} == *"qa"* ]]; then
        CONFIG_SUFFIX="qa"
      elif [[ ${_IMAGE_NAME} == *"edge"* ]]; then
        CONFIG_SUFFIX="edge"
      else
        CONFIG_SUFFIX="prod"
      fi

      CONFIG_FILE=".github/configs/${_REGION}/.env.${CONFIG_SUFFIX}"

      build_args=()
      while IFS='=' read -r key value; do
        if [[ -n "$key" ]]; then
          # Trim any whitespace from key and value
          key=$(echo "$key" | xargs)
          value=$(echo "$value" | xargs)
          build_args+=("--build-arg" "${key}=${value}")
        fi
      done < "$CONFIG_FILE"

      depot build \
        --project 3vz0lnf16v \
        --provenance=false \
        -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/dust-images/${_IMAGE_NAME}:${SHORT_SHA} \
        -t ${_REGION}-docker.pkg.dev/${PROJECT_ID}/dust-images/${_IMAGE_NAME}:latest \
        -f ${_DOCKERFILE_PATH} \
        --build-arg COMMIT_HASH=${SHORT_SHA} \
        ${build_args[@]} \
        --push \
        .

    secretEnv:
      - "DEPOT_TOKEN"

timeout: 1200s

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/DEPOT_TOKEN/versions/latest
      env: DEPOT_TOKEN

options:
  automapSubstitutions: true
  logging: CLOUD_LOGGING_ONLY