PUT /front.skills_1/_mapping
{
  "properties": {
    "name": {
      "type": "text",
      "analyzer": "exact_analyzer",
      "fields": {
        "english": {
          "type": "text",
          "analyzer": "english"
        },
        "french": {
          "type": "text",
          "analyzer": "french"
        }
      }
    },
    "description": {
      "type": "text",
      "analyzer": "icu_analyzer",
      "fields": {
        "english": {
          "type": "text",
          "analyzer": "english"
        },
        "french": {
          "type": "text",
          "analyzer": "french"
        }
      }
    }
  }
}
