PUT /front.skills_1/_settings
{
  "analysis": {
    "char_filter": {
      "name_word_boundaries": {
        "type": "pattern_replace",
        "pattern": "(?<=\\p{Ll})(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}\\p{Ll})",
        "replacement": " "
      }
    },
    "analyzer": {
      "name_words_analyzer": {
        "type": "custom",
        "char_filter": [
          "name_word_boundaries"
        ],
        "tokenizer": "icu_tokenizer",
        "filter": [
          "icu_folding"
        ]
      }
    }
  }
}
