apiVersion: v1
kind: Service
metadata:
  name: socks-proxy-service
spec:
  type: ClusterIP
  selector:
    app: socks-proxy
  ports:
    - name: socks5
      port: 1080
      targetPort: 1080
  
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: socks-proxy-service