apiVersion: v1
kind: Service
metadata:
  name: socks-proxy-service
spec:
  type: ClusterIP
  ports:
  - port: 1080
    targetPort: 1080
  selector:
    app: socks-proxy
---
apiVersion: net.gke.io/v1
kind: ServiceExport
metadata:
  name: socks-proxy-service