apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-config
data:
  DD_ENV: "prod"
  DD_SERVICE: "blog"
  NODE_OPTIONS: "-r dd-trace/init --max-old-space-size=6000"
  DD_LOGS_INJECTION: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
  NODE_ENV: "production"
  NEXT_PUBLIC_SITE_URL: "https://blog.dust.tt"
