apiVersion: v1
kind: ConfigMap
metadata:
  name: core-sqlite-worker-config
data:
  DD_ENV: "prod"
  DD_SERVICE: "core-sqlite-worker"
  DD_LOGS_INJECTION: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
  CORE_API: "http://core-service"
