# fly.toml file generated for dust-api on 2023-04-02T22:15:21+08:00

app = "dust-api"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "nrt"
processes = []

[env]
  DUST_FRONT_API = "https://dust-front.fly.dev"

