import { useConversationAttachments } from "@app/hooks/conversations/useConversationAttachments";
import { isFileAttachmentType } from "@app/lib/api/assistant/conversation/attachments";
import type {
  ConversationAttachmentType,
  FileAttachmentType,
} from "@app/types/api/assistant/conversation/attachments";
import type { LightAgentMessageType } from "@app/types/assistant/conversation";
import type { InteractiveContentFileContentType } from "@app/types/files";
import {
  INTERACTIVE_CONTENT_FILE_FORMATS,
  isInteractiveContentType,
} from "@app/types/files";
import type { LightWorkspaceType } from "@app/types/user";
import { useMemo } from "react";

export interface ResolvedInteractiveFile {
  fileId: string;
  contentType: InteractiveContentFileContentType;
}

const INTERACTIVE_CONTENT_EXTENSIONS = [
  ...new Set(
    Object.values(INTERACTIVE_CONTENT_FILE_FORMATS).flatMap(
      (format) => format.exts
    )
  ),
];

// True when the file name alone could denote an interactive file (Frame). Needed
// because `:preview_file` directives may omit `contentType`, in which case the
// filename-derived type is a generic code type rather than the frame type.
export function hasInteractiveContentExtension(fileName: string): boolean {
  const lowerCaseFileName = fileName.toLowerCase();
  return INTERACTIVE_CONTENT_EXTENSIONS.some((ext) =>
    lowerCaseFileName.endsWith(ext)
  );
}

function pickLatest<T extends { createdAt?: number; updatedAt?: number }>(
  candidates: T[]
): T | null {
  let latest: T | null = null;
  let latestTimestamp = -1;
  for (const candidate of candidates) {
    const timestamp = candidate.updatedAt ?? candidate.createdAt ?? 0;
    if (timestamp > latestTimestamp) {
      latest = candidate;
      latestTimestamp = timestamp;
    }
  }
  return latest;
}

// All matchers pre-filter on isInteractiveContentType; this re-check exists to
// narrow contentType to InteractiveContentFileContentType (filtering an object
// array does not narrow a property's type).
function toResolvedFile(
  candidate: { fileId: string | null; contentType: string } | null
): ResolvedInteractiveFile | null {
  if (!candidate?.fileId || !isInteractiveContentType(candidate.contentType)) {
    return null;
  }
  return { fileId: candidate.fileId, contentType: candidate.contentType };
}

// Files generated by the message being rendered carry no scoped path, so the
// match is on the file name (frame file names are unique within a conversation
// file system).
export function findInteractiveGeneratedFile(
  generatedFiles: LightAgentMessageType["generatedFiles"],
  fileName: string
): ResolvedInteractiveFile | null {
  const candidates = generatedFiles.filter(
    (file) =>
      file.fileId !== null &&
      isInteractiveContentType(file.contentType) &&
      file.title === fileName
  );

  return toResolvedFile(pickLatest(candidates));
}

function interactiveFileAttachments(
  attachments: ConversationAttachmentType[]
): FileAttachmentType[] {
  return attachments
    .filter(isFileAttachmentType)
    .filter((attachment) => isInteractiveContentType(attachment.contentType));
}

// Conversation attachments aggregate the generated files of every message in
// the conversation. Exact scoped-path match; agent-generated attachments have
// `path: null`, so most resolutions go through the name fallback below.
export function findInteractiveAttachmentByPath(
  attachments: ConversationAttachmentType[],
  path: string
): ResolvedInteractiveFile | null {
  const candidates = interactiveFileAttachments(attachments).filter(
    (attachment) => attachment.path === path
  );

  return toResolvedFile(pickLatest(candidates));
}

// Name fallback for attachments without a path. Less precise than the exact
// path match, so it must run after it.
export function findInteractiveAttachmentByName(
  attachments: ConversationAttachmentType[],
  fileName: string
): ResolvedInteractiveFile | null {
  const candidates = interactiveFileAttachments(attachments).filter(
    (attachment) => attachment.title === fileName
  );

  return toResolvedFile(pickLatest(candidates));
}

interface UseInteractiveFileResolutionParams {
  owner: LightWorkspaceType;
  conversationId: string | null;
  // Files generated by the message being rendered; resolves without a fetch.
  generatedFiles: LightAgentMessageType["generatedFiles"];
  // Canonical scoped path from the directive, e.g. `conversation-<id>/Frame.tsx`.
  path: string;
  fileName: string;
  contentType: string;
}

/**
 * Resolve an inline scoped-path file reference to its interactive-content
 * FileResource, so callers can open it in the interactive side panel (the file
 * preview dialog cannot render frames).
 *
 * Resolution order: the message's own generated files (in memory, covers files
 * created by this message), then the conversation attachments (covers files
 * created by earlier messages) — exact path match before the name fallback.
 * The attachments lookup is SWR-cached and only fetched when the reference
 * could denote an interactive file and the in-memory match missed. Returns
 * null for non-interactive files and unresolvable references.
 */
export function useInteractiveFileResolution({
  owner,
  conversationId,
  generatedFiles,
  path,
  fileName,
  contentType,
}: UseInteractiveFileResolutionParams): ResolvedInteractiveFile | null {
  const fromMessage = useMemo(
    () => findInteractiveGeneratedFile(generatedFiles, fileName),
    [generatedFiles, fileName]
  );

  const isPossiblyInteractive =
    isInteractiveContentType(contentType) ||
    hasInteractiveContentExtension(fileName);
  const needsLookup = isPossiblyInteractive && fromMessage === null;

  const { attachments } = useConversationAttachments({
    conversationId,
    options: { disabled: !needsLookup || !conversationId },
    owner,
  });

  return useMemo(() => {
    if (fromMessage) {
      return fromMessage;
    }
    if (!needsLookup) {
      return null;
    }
    return (
      findInteractiveAttachmentByPath(attachments, path) ??
      findInteractiveAttachmentByName(attachments, fileName)
    );
  }, [fromMessage, needsLookup, attachments, fileName, path]);
}
