apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socks-proxy
  template:
    metadata:
      labels:
        app: socks-proxy
        name: socks-proxy-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "dante","service": "sock5-proxy","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: socks-proxy
          image: vimagick/dante
          ports:
            - containerPort: 1080

          envFrom:
            - configMapRef:
                name: socks-proxy-config
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
