apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks-proxy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: socks-proxy
  template:
    metadata:
      labels:
        app: socks-proxy
        name: socks-proxy-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "dante","service": "socks-proxy","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: socks-proxy
          image: gcr.io/or1g1n-186209/dante-image:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: dante-config
            mountPath: /etc/sockd.conf
            subPath: sockd.conf
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
      - name: dante-config
        configMap:
          name: socks-proxy-config
