PUT _ingest/pipeline/tag_filter
{
  "description": "Filter out unwanted tag values",
  "processors": [
    {
      "script": {
        "lang": "painless",
        "source": "def tags = ctx.tags;if (tags != null) {ctx.tags = tags.stream().filter(tag -> !tag.startsWith(\"createdAt:\")).filter(tag -> !tag.startsWith(\"updatedAt:\")).filter(tag -> !tag.startsWith(\"title:\")).collect(Collectors.toList());}",
        "if": "ctx.tags != null && ctx.tags.length > 0"
      }
    }
  ]
}
