PUT core.data_sources/_settings?reopen=true
{
  "analysis": {
    "analyzer": {
      "edge_analyzer": {
        "type": "custom",
        "tokenizer": "icu_tokenizer",
        "filter": ["preserve_word_delimiter", "lowercase", "edge_ngram_filter"]
      }
    },
    "filter": {
      "preserve_word_delimiter": {
        "type": "word_delimiter",
        "split_on_numerics": false,
        "split_on_case_change": true,
        "preserve_original": true,
        "stem_english_possessive": false
      }
    }
  }
}