PUT core.data_sources_nodes_4/_mapping
{
  "properties": {
    "title": {
      "type": "text",
      "fields": {
        "edge": {
          "type": "text",
          "analyzer": "edge_analyzer",
          "search_analyzer": "standard"
        },
        "keyword": {
          "type": "keyword"
        }
      },
      "analyzer": "standard"
    },
    "tags": {
      "type": "text",
      "fields": {
        "edge": {
          "type": "text",
          "analyzer": "tag_edge_analyzer",
          "search_analyzer": "standard"
        },
        "keyword": {
          "type": "keyword",
          "normalizer": "tag_normalizer"
        }
      },
      "analyzer": "standard"
    }
  }
}
