[package]
name = "dfs-protocol"
version = "0.5.0"
edition.workspace = true
publish.workspace = true

[dependencies]
prost = "0.14"
serde = { version = "1", features = ["derive"] }
tonic = { version = "0.14", features = ["tls-ring", "tls-native-roots"] }
tonic-prost = "0.14"
uuid = { version = "1", features = ["v4"] }
mime = "0.3"
percent-encoding = "2"

[build-dependencies]
tonic-prost-build = "0.14"

[dev-dependencies]
postcard = { version = "1", default-features = false, features = ["use-std"] }
serde_json = "1"

[lints]
workspace = true
