name = "app-dust-tt"
compatibility_date = "2025-01-01"
main = "./worker/app.ts"

[assets]
directory = "./dist/app"
not_found_handling = "none"
binding = "ASSETS"

# Custom domain bleeding-edge.dust.tt (bound via Cloudflare dashboard).
[env.bleeding-edge]
name = "app-bleeding-edge-dust-tt"

[env.bleeding-edge.assets]
directory = "./dist/app"
not_found_handling = "none"
binding = "ASSETS"
