#!/usr/bin/env bash
# Shared helpers for Dust Cloud Agent dev scripts.

DUST_REPO_ROOT="${DUST_REPO_ROOT:-$(
  cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd
)}"
export DUST_REPO_ROOT

DUST_INFRA_LOG_DIR="${DUST_INFRA_LOG_DIR:-/tmp/dust-infra}"
mkdir -p "$DUST_INFRA_LOG_DIR"

log() {
  echo "[${DUST_DEV_SCRIPT_NAME:-cursor-dev}] $*"
}

install_cursor_runtime_config() {
  if [ -f "${DUST_REPO_ROOT}/.cursor/config/mprocs.yaml" ]; then
    mkdir -p "${HOME}/.config/mprocs"
    cp "${DUST_REPO_ROOT}/.cursor/config/mprocs.yaml" "${HOME}/.config/mprocs/mprocs.yaml"
  fi
}

ensure_node_path() {
  if command -v node >/dev/null 2>&1; then
    return 0
  fi
  log "node not found on PATH"
  return 1
}

resolve_temporal_bin() {
  if command -v temporal >/dev/null 2>&1; then
    command -v temporal
    return 0
  fi
  for candidate in /usr/local/bin/temporal /root/.temporalio/bin/temporal; do
    if [ -x "$candidate" ]; then
      echo "$candidate"
      return 0
    fi
  done
  log "temporal CLI not found (rebuild .cursor/Dockerfile or install to /usr/local/bin)"
  return 1
}

# Migrations and seed scripts import @dust-tt/client (main: sdks/js/dist/index.js).
ensure_workspace_deps() {
  ensure_node_path
  cd "$DUST_REPO_ROOT"

  if [ ! -f node_modules/@dust-tt/client/package.json ]; then
    log "Installing npm workspaces (required before migrations)..."
    npm install
  fi

  if [ ! -f sdks/js/dist/index.js ]; then
    log "Building @dust-tt/client (sdks/js)..."
    npm -w @dust-tt/client run build
  fi
}

write_gcp_service_account_file() {
  if [ -n "${GCP_SERVICE_ACCOUNT:-}" ]; then
    printf '%s' "$GCP_SERVICE_ACCOUNT" >"${SERVICE_ACCOUNT:-/tmp/dust-dev-sa.json}"
    export SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-/tmp/dust-dev-sa.json}"
  fi
}

# Materialized 1Password + local-dev env for every shell (see BASH_ENV / .cursor/bashrc).
# Prefer these over wrapping commands in `op run` (which masks TTY output and is easy to forget).
DUST_OP_ENV_FILE="${DUST_OP_ENV_FILE:-/tmp/dust-op-environment.env}"
DUST_LOCAL_ENV_FILE="${DUST_LOCAL_ENV_FILE:-/tmp/dust-local-dev.env}"
DUST_SHELL_ENV_FILE="${DUST_SHELL_ENV_FILE:-/tmp/dust-shell-env.sh}"

# `op environment read` requires 1Password CLI >= 2.33.0-beta.02 (Environments feature).
op_cli_supports_environments() {
  local current="${1:-$(op --version 2>/dev/null | head -1 | tr -d '[:space:]')}"
  local minimum="2.33.0-beta.02"

  if [ -z "$current" ]; then
    return 1
  fi

  # sort -V: if minimum sorts first, current is >= minimum.
  [ "$(printf '%s\n' "$minimum" "$current" | sort -V | head -1)" = "$minimum" ]
}

require_op_credentials() {
  if [ -z "${OP_SERVICE_ACCOUNT_TOKEN:-}" ]; then
    log "OP_SERVICE_ACCOUNT_TOKEN is not set (add it as a Cursor runtime secret)"
    return 1
  fi
  if [ -z "${OP_ENVIRONMENT_ID:-}" ]; then
    log "OP_ENVIRONMENT_ID is not set"
    return 1
  fi
  if ! op_cli_supports_environments; then
    log "op CLI is too old ($(op --version 2>/dev/null || echo unknown)); need >= 2.33.0-beta.02 with op environment read (rebuild .cursor/Dockerfile)"
    return 1
  fi
  return 0
}

# Escape a value for KEY=VALUE dotenv assignment (double-quoted).
dotenv_quote() {
  local value="${1-}"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//\$/\\\$}"
  value="${value//\`/\\\`}"
  printf '"%s"' "$value"
}

write_shell_env_loader() {
  cat >"$DUST_SHELL_ENV_FILE" <<EOF
# Auto-generated by Dust Cursor start scripts. Sourced via BASH_ENV and .cursor/bashrc.
# Secrets live in ${DUST_OP_ENV_FILE} / ${DUST_LOCAL_ENV_FILE}; this file only loads them.
if [ -n "\${DUST_SHELL_ENV_LOADING:-}" ]; then
  return 0 2>/dev/null || true
fi
DUST_SHELL_ENV_LOADING=1
_dust_bash_env_saved="\${BASH_ENV-}"
unset BASH_ENV

if [ -f "${DUST_OP_ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1091
  . "${DUST_OP_ENV_FILE}"
  set +a
fi
if [ -f "${DUST_LOCAL_ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1091
  . "${DUST_LOCAL_ENV_FILE}"
  set +a
fi

if [ -n "\${_dust_bash_env_saved}" ]; then
  export BASH_ENV="\${_dust_bash_env_saved}"
fi
unset _dust_bash_env_saved DUST_SHELL_ENV_LOADING
EOF
  chmod 644 "$DUST_SHELL_ENV_FILE"
}

# Host-injected / in-container infra must win over cloud URIs from the 1Password Environment.
export_local_dev_infra() {
  export POSTGRES_HOST="${POSTGRES_HOST:-localhost}"
  export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
  export REDIS_HOST="${REDIS_HOST:-localhost}"
  export REDIS_PORT="${REDIS_PORT:-6379}"

  export FRONT_DATABASE_URI="postgres://dev:dev@${POSTGRES_HOST}:${POSTGRES_PORT}/dust_front"
  export FRONT_DATABASE_READ_REPLICA_URI="$FRONT_DATABASE_URI"
  export CORE_DATABASE_URI="postgres://dev:dev@${POSTGRES_HOST}:${POSTGRES_PORT}/dust_api"
  export CORE_DATABASE_READ_REPLICA_URI="$CORE_DATABASE_URI"
  export CONNECTORS_DATABASE_URI="postgres://dev:dev@${POSTGRES_HOST}:${POSTGRES_PORT}/dust_connectors"
  export CONNECTORS_DATABASE_READ_REPLICA_URI="$CONNECTORS_DATABASE_URI"
  export OAUTH_DATABASE_URI="postgres://dev:dev@${POSTGRES_HOST}:${POSTGRES_PORT}/dust_oauth"

  export REDIS_URI="redis://${REDIS_HOST}:${REDIS_PORT}"
  export REDIS_CACHE_URI="$REDIS_URI"
  export ELASTICSEARCH_URL="http://${ELASTICSEARCH_HOST:-localhost}:${ELASTICSEARCH_PORT:-9200}"
  export ELASTICSEARCH_USERNAME="${ELASTICSEARCH_USERNAME:-elastic}"
  export ELASTICSEARCH_PASSWORD="${ELASTICSEARCH_PASSWORD:-}"
  export TEMPORAL_ADDRESS="${DUST_LOCAL_TEMPORAL_ADDRESS:-127.0.0.1:7233}"

  export CORE_API="http://localhost:3001"
  export DUST_FRONT_API="http://localhost:3000"
  export DUST_FRONT_INTERNAL_API="http://localhost:3000"
  export DUST_INTERNAL_API_URL="http://localhost:3000"
  export DUST_CLIENT_FACING_URL="http://localhost:3000"
  export DUST_PUBLIC_URL="http://localhost:3000"
  export DUST_AUTH_REDIRECT_BASE_URL="http://localhost:3000"
  export NEXT_PUBLIC_DUST_API_URL="http://localhost:3000"
  export NEXT_PUBLIC_DUST_APP_URL="http://localhost:3011"
  export NEXT_PUBLIC_DUST_STATIC_WEBSITE_URL="http://localhost:3000"
}

write_local_dev_env_file() {
  export_local_dev_infra
  export NODE_ENV="development"
  export SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-/tmp/dust-dev-sa.json}"

  local tmp
  tmp="$(mktemp /tmp/dust-local-dev.XXXXXX)"
  {
    printf 'DUST_REPO_ROOT=%s\n' "$(dotenv_quote "$DUST_REPO_ROOT")"
    printf 'NODE_ENV=%s\n' "$(dotenv_quote "development")"
    printf 'SERVICE_ACCOUNT=%s\n' "$(dotenv_quote "$SERVICE_ACCOUNT")"
    printf 'POSTGRES_HOST=%s\n' "$(dotenv_quote "$POSTGRES_HOST")"
    printf 'POSTGRES_PORT=%s\n' "$(dotenv_quote "$POSTGRES_PORT")"
    printf 'REDIS_HOST=%s\n' "$(dotenv_quote "$REDIS_HOST")"
    printf 'REDIS_PORT=%s\n' "$(dotenv_quote "$REDIS_PORT")"
    printf 'FRONT_DATABASE_URI=%s\n' "$(dotenv_quote "$FRONT_DATABASE_URI")"
    printf 'FRONT_DATABASE_READ_REPLICA_URI=%s\n' "$(dotenv_quote "$FRONT_DATABASE_READ_REPLICA_URI")"
    printf 'CORE_DATABASE_URI=%s\n' "$(dotenv_quote "$CORE_DATABASE_URI")"
    printf 'CORE_DATABASE_READ_REPLICA_URI=%s\n' "$(dotenv_quote "$CORE_DATABASE_READ_REPLICA_URI")"
    printf 'CONNECTORS_DATABASE_URI=%s\n' "$(dotenv_quote "$CONNECTORS_DATABASE_URI")"
    printf 'CONNECTORS_DATABASE_READ_REPLICA_URI=%s\n' "$(dotenv_quote "$CONNECTORS_DATABASE_READ_REPLICA_URI")"
    printf 'OAUTH_DATABASE_URI=%s\n' "$(dotenv_quote "$OAUTH_DATABASE_URI")"
    printf 'REDIS_URI=%s\n' "$(dotenv_quote "$REDIS_URI")"
    printf 'REDIS_CACHE_URI=%s\n' "$(dotenv_quote "$REDIS_CACHE_URI")"
    printf 'ELASTICSEARCH_URL=%s\n' "$(dotenv_quote "$ELASTICSEARCH_URL")"
    printf 'ELASTICSEARCH_USERNAME=%s\n' "$(dotenv_quote "$ELASTICSEARCH_USERNAME")"
    printf 'ELASTICSEARCH_PASSWORD=%s\n' "$(dotenv_quote "${ELASTICSEARCH_PASSWORD:-}")"
    printf 'TEMPORAL_ADDRESS=%s\n' "$(dotenv_quote "$TEMPORAL_ADDRESS")"
    printf 'CORE_API=%s\n' "$(dotenv_quote "$CORE_API")"
    printf 'DUST_FRONT_API=%s\n' "$(dotenv_quote "$DUST_FRONT_API")"
    printf 'DUST_FRONT_INTERNAL_API=%s\n' "$(dotenv_quote "$DUST_FRONT_INTERNAL_API")"
    printf 'DUST_INTERNAL_API_URL=%s\n' "$(dotenv_quote "$DUST_INTERNAL_API_URL")"
    printf 'DUST_CLIENT_FACING_URL=%s\n' "$(dotenv_quote "$DUST_CLIENT_FACING_URL")"
    printf 'DUST_PUBLIC_URL=%s\n' "$(dotenv_quote "$DUST_PUBLIC_URL")"
    printf 'DUST_AUTH_REDIRECT_BASE_URL=%s\n' "$(dotenv_quote "$DUST_AUTH_REDIRECT_BASE_URL")"
    printf 'NEXT_PUBLIC_DUST_API_URL=%s\n' "$(dotenv_quote "$NEXT_PUBLIC_DUST_API_URL")"
    printf 'NEXT_PUBLIC_DUST_APP_URL=%s\n' "$(dotenv_quote "$NEXT_PUBLIC_DUST_APP_URL")"
    printf 'NEXT_PUBLIC_DUST_STATIC_WEBSITE_URL=%s\n' "$(dotenv_quote "$NEXT_PUBLIC_DUST_STATIC_WEBSITE_URL")"
    # Cursor runtime secrets when present in this process (e.g. mprocs terminal).
    if [ -n "${GCP_SERVICE_ACCOUNT:-}" ]; then
      printf 'GCP_SERVICE_ACCOUNT=%s\n' "$(dotenv_quote "$GCP_SERVICE_ACCOUNT")"
    fi
    if [ -n "${DEV_WORKOS_USER_EMAIL:-}" ]; then
      printf 'DEV_WORKOS_USER_EMAIL=%s\n' "$(dotenv_quote "$DEV_WORKOS_USER_EMAIL")"
    fi
    if [ -n "${DEV_WORKOS_USER_PASSWORD:-}" ]; then
      printf 'DEV_WORKOS_USER_PASSWORD=%s\n' "$(dotenv_quote "$DEV_WORKOS_USER_PASSWORD")"
    fi
    if [ -n "${DEV_WORKOS_USER_ID:-}" ]; then
      printf 'DEV_WORKOS_USER_ID=%s\n' "$(dotenv_quote "$DEV_WORKOS_USER_ID")"
    fi
  } >"$tmp"
  chmod 600 "$tmp"
  mv "$tmp" "$DUST_LOCAL_ENV_FILE"
}

# Ensure BASH_ENV is set for child bash processes even on images built before the
# Dockerfile ENV landed. start-infra persists this for login shells too.
ensure_bash_env_global() {
  export BASH_ENV="${DUST_SHELL_ENV_FILE}"

  if [ -f /root/.profile ] && ! grep -qF "BASH_ENV=${DUST_SHELL_ENV_FILE}" /root/.profile 2>/dev/null; then
    printf '\n# Dust materialized secrets for non-interactive bash\nexport BASH_ENV=%s\n' \
      "$DUST_SHELL_ENV_FILE" >>/root/.profile
  fi

  # Prepend a source hook for interactive bash that may not inherit Docker ENV.
  if [ -f /root/.bashrc ] && ! grep -qF "export BASH_ENV=${DUST_SHELL_ENV_FILE}" /root/.bashrc 2>/dev/null; then
    local tmp
    tmp="$(mktemp)"
    {
      printf '# Dust: ensure child bash processes load materialized secrets\n'
      printf 'export BASH_ENV=%s\n' "$DUST_SHELL_ENV_FILE"
      cat /root/.bashrc
    } >"$tmp"
    mv "$tmp" /root/.bashrc
  fi
}

# Fetch the full 1Password Environment once and persist it for all shells/commands.
# New secrets added in 1Password appear on the next materialize (start / refresh) with no script edits.
materialize_dev_environment() {
  write_shell_env_loader

  if require_op_credentials; then
    local tmp
    tmp="$(mktemp /tmp/dust-op-env.XXXXXX)"
    if ! op environment read "$OP_ENVIRONMENT_ID" >"$tmp"; then
      rm -f "$tmp"
      log "Failed to read 1Password environment $OP_ENVIRONMENT_ID"
      write_local_dev_env_file
      ensure_bash_env_global
      return 1
    fi
    chmod 600 "$tmp"
    mv "$tmp" "$DUST_OP_ENV_FILE"
    log "Materialized 1Password env ($(wc -l <"$DUST_OP_ENV_FILE" | tr -d ' ') vars) -> ${DUST_OP_ENV_FILE}"
  else
    log "Skipping 1Password materialize (credentials missing); local overrides only"
    rm -f "$DUST_OP_ENV_FILE"
  fi

  write_local_dev_env_file
  write_gcp_service_account_file
  ensure_bash_env_global
  return 0
}

# Source materialized env into the current shell (materialize first if missing).
load_op_environment() {
  if [ ! -f "$DUST_SHELL_ENV_FILE" ]; then
    materialize_dev_environment || return 1
  fi
  # shellcheck disable=SC1090
  source "$DUST_SHELL_ENV_FILE"
  return 0
}

export_op_runtime_secrets() {
  export DUST_REPO_ROOT="$DUST_REPO_ROOT"
  export SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-}"
  export GCP_SERVICE_ACCOUNT="${GCP_SERVICE_ACCOUNT:-}"
  export DEV_WORKOS_USER_EMAIL="${DEV_WORKOS_USER_EMAIL:-}"
  export DEV_WORKOS_USER_PASSWORD="${DEV_WORKOS_USER_PASSWORD:-}"
  export DEV_WORKOS_USER_ID="${DEV_WORKOS_USER_ID:-}"
  # Local Cursor dev always uses in-container infra. 1Password envs often point at cloud
  # Postgres/Temporal/staging NODE_ENV which breaks init_plans, workers, and seed SQL.
  export NODE_ENV="development"
  export_local_dev_infra
}

# If env was already materialized (start-infra), pull it into any script that sources common.sh.
if [ -f "${DUST_SHELL_ENV_FILE:-/tmp/dust-shell-env.sh}" ] && [ -z "${DUST_SHELL_ENV_LOADING:-}" ] && [ -z "${DUST_COMMON_SKIP_SHELL_ENV:-}" ]; then
  # shellcheck disable=SC1090
  source "${DUST_SHELL_ENV_FILE:-/tmp/dust-shell-env.sh}"
fi
