/**
 * Legacy `Action*Icon` names mapped to their v2-stroke replacement.
 *
 * The legacy names are persisted (resource icons, skill and MCP server `icon`
 * strings), so they stay part of the public API and only the glyph behind them
 * changes. Mapping source: Figma "Sparkle Icons" / OldIcons page.
 *
 * `src/icons/actions/index.ts` re-exports the targets listed here, and the
 * playground `ActionIconMapping` page renders this map next to the pre-v2
 * glyphs still living in `src/icons/actions/*.tsx`.
 */
type ActionIconName = keyof typeof import("./actions");
type V2IconName = keyof typeof import("./v2-stroke");

export const ACTION_ICON_ALIASES = {
  ActionArmchairIcon: "Armchair",
  ActionArrowDownOnSquareIcon: "Download01",
  ActionArrowUpOnSquareIcon: "Upload01",
  ActionAtomIcon: "Atom01",
  ActionAttachmentIcon: "Attachment01",
  ActionBankIcon: "Bank",
  ActionBarcodeIcon: "QrCode01",
  ActionBeerIcon: "Beer",
  ActionBookOpenIcon: "BookOpen01",
  ActionBracesIcon: "Brackets",
  ActionBrainIcon: "Brain",
  ActionBriefcaseIcon: "Briefcase01",
  ActionBuildingIcon: "Building04",
  ActionCalculatorIcon: "Calculator",
  ActionCalendarCheckIcon: "CalendarCheck01",
  ActionCalendarIcon: "Calendar",
  ActionCameraIcon: "Camera01",
  ActionCardIcon: "CreditCard01",
  ActionCarIcon: "Car01",
  ActionChatBubbleBottomCenterTextIcon: "MessageCircle01",
  ActionChatBubbleThoughtIcon: "MessageDotsCircle",
  ActionCheckCircleIcon: "CheckCircle",
  ActionClipboardIcon: "Clipboard",
  ActionCloudArrowDownIcon: "DownloadCloud01",
  ActionCloudArrowLeftRightIcon: "CloudArrowLeftRight",
  ActionCloudArrowUpIcon: "UploadCloud02",
  ActionCodeBlockIcon: "CodeBrowser",
  ActionCodeBoxIcon: "CodeSquare01",
  ActionCommand1Icon: "Command",
  ActionCommandIcon: "TerminalSquare",
  ActionCommunityIcon: "Building06",
  ActionCompanyIcon: "Building04",
  ActionCreditCoinsIcon: "CoinsStacked01",
  ActionCubeIcon: "Cube01",
  ActionCupIcon: "Cup",
  ActionCustomerServiceIcon: "Headphones01",
  ActionDashboardIcon: "Speedometer03",
  ActionDatabaseIcon: "Database01",
  ActionDocumentIcon: "File04",
  ActionDocumentPileIcon: "DocumentPile",
  ActionDocumentPlusIcon: "FilePlus03",
  ActionDocumentTextIcon: "File06",
  ActionDoubleQuotesIcon: "DoubleQuotes",
  ActionEmotionLaughIcon: "FaceHappy",
  ActionExternalLinkIcon: "LinkExternal01",
  ActionEyeIcon: "Eye",
  ActionEyeSlashIcon: "EyeOff",
  ActionFilmIcon: "Film01",
  ActionFilterIcon: "FilterLines",
  ActionFireIcon: "Fire",
  ActionFlagIcon: "Flag01",
  ActionFlightLandIcon: "Plane",
  ActionFlightTakeoffIcon: "Plane",
  ActionFolderAddIcon: "FolderPlus",
  ActionFolderIcon: "Folder",
  ActionFolderOpenIcon: "Folder",
  ActionFrameIcon: "ActionFrame",
  ActionFullscreenExitIcon: "Minimize01",
  ActionFullscreenIcon: "Maximize01",
  ActionGamepadIcon: "GamingPad02",
  ActionGitBranchIcon: "Dataflow02",
  ActionGitForkIcon: "Dataflow01",
  ActionGlobeAltIcon: "Globe01",
  ActionGlobeIcon: "Globe05",
  ActionGraduationCapIcon: "GraduationHat01",
  ActionHandHeartIcon: "HeartHand",
  ActionHandThumbDownIcon: "ThumbsDown",
  ActionHandThumbUpIcon: "ThumbsUp",
  ActionHashtagIcon: "Hash01",
  ActionHeartIcon: "Heart",
  ActionHomeIcon: "Home01",
  ActionHospitalIcon: "MedicalCircle",
  ActionIdentityIcon: "Fingerprint03",
  ActionImageIcon: "Image01",
  ActionInboxIcon: "Inbox01",
  ActionIncludeIcon: "ArrowCircleBrokenRight",
  ActionLayoutIcon: "Columns03",
  ActionLightbulbIcon: "Lightbulb01",
  ActionListCheckIcon: "ListSelect",
  ActionListIcon: "List",
  ActionLockIcon: "Lock01",
  ActionLogoutIcon: "LogOut01",
  ActionMagicIcon: "MagicWand02",
  ActionMagnifyingGlassIcon: "SearchMd",
  ActionMailAiIcon: "MailAi",
  ActionMailCloseIcon: "MailClose",
  ActionMailIcon: "Mail01",
  ActionMapIcon: "Map01",
  ActionMapPinIcon: "MarkerPin01",
  ActionMarkPenIcon: "PencilLine",
  ActionMedalIcon: "Award01",
  ActionMegaphoneIcon: "Announcement01",
  ActionMenuIcon: "Menu01",
  ActionMicIcon: "Microphone01",
  ActionMoonIcon: "Moon01",
  ActionMovieIcon: "Clapperboard",
  ActionNoiseIcon: "VolumeMax",
  ActionNumbersIcon: "BarChart12",
  ActionPaintIcon: "Paint",
  ActionPencilSquareIcon: "Edit04",
  ActionPieChartIcon: "PieChart01",
  ActionPinDistanceIcon: "Route",
  ActionPingPongIcon: "PingPong",
  ActionPlanetIcon: "Planet",
  ActionPlusCircleIcon: "PlusCircle",
  ActionPlusIcon: "Plus",
  ActionPrinterIcon: "Printer",
  ActionPushpinIcon: "Pin02",
  ActionRainbowIcon: "Rainbow",
  ActionRobotIcon: "Robot",
  ActionRocketIcon: "Rocket02",
  ActionSafeIcon: "Safe",
  ActionSaveIcon: "Save01",
  ActionScalesIcon: "Scales01",
  ActionScanIcon: "ScanFile",
  ActionSeedlingIcon: "Seedling",
  ActionServerIcon: "Server03",
  ActionShakeHandsIcon: "ShakeHands",
  ActionShipIcon: "Anchor",
  ActionShirtIcon: "Shirt",
  ActionShoppingBasketIcon: "ShoppingBag01",
  ActionSlideshowIcon: "PresentationChart01",
  ActionSparklesIcon: "Stars02",
  ActionSpeakIcon: "MessageSmileCircle",
  ActionSquare3Stack3DIcon: "LayersThree01",
  ActionStopSignIcon: "SlashCircle01",
  ActionStoreIcon: "ActionStore",
  ActionSunIcon: "Sun",
  ActionSwordIcon: "Sword",
  ActionTableIcon: "LayoutGrid02",
  ActionTagIcon: "Tag01",
  ActionTestTubeIcon: "Beaker02",
  ActionTimeIcon: "Clock",
  ActionTrainIcon: "Train",
  ActionTranslateIcon: "Translate01",
  ActionTrashIcon: "Trash01",
  ActionTrophyIcon: "Trophy01",
  ActionTShirtIcon: "TShirt",
  ActionUmbrellaIcon: "Umbrella01",
  ActionUserGroupIcon: "Users01",
  ActionUserIcon: "User01",
  ActionVidiconIcon: "VideoRecorder",
  ActionVolumeUpIcon: "VolumeMax",
  ActionXCircleIcon: "XCircle",
  // `satisfies` keeps this map and the barrel in lockstep: a legacy name
  // missing here, or one that no longer exists, fails to compile.
} as const satisfies Record<ActionIconName, V2IconName>;

export type ActionIconAliasName = keyof typeof ACTION_ICON_ALIASES;
