apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectors-edge-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connectors-edge
  template:
    metadata:
      labels:
        app: connectors-edge
        name: connectors-edge-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "connectors","service": "connectors-edge","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/connectors-image:latest
          command: ["sh", "-c", "tsx ./src/start_server.ts -p 3002"]
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: connectors-edge-config
            - secretRef:
                name: connectors-secrets

          # override env vars from configmap/secret
          env:
            # we override--max-old-space-size for edge as pods
            # don't have the same memory limits as the regular connectors pods
            - name: NODE_OPTIONS
              value: "-r dd-trace/init --max-old-space-size=600"

            - name: DUST_FRONT_API
              value: http://front-edge-service

            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: private-key-volume
              mountPath: /etc/private-keys

          resources:
            requests:
              cpu: 200m
              memory: 1Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-cert

        - name: private-key-volume
          secret:
            secretName: github-app-private-key
