apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectors-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: connectors
  template:
    metadata:
      labels:
        app: connectors
        name: connectors-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "connectors","service": "connectors","tags": ["env:prod"]}]'
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/connectors-image:latest
          command: ["npm", "run", "start:web"]
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5

          envFrom:
            - configMapRef:
                name: connectors-config
            - secretRef:
                name: connectors-secrets
          env:
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs
            - name: private-key-volume
              mountPath: /etc/private-keys

          resources:
            requests:
              cpu: 1000m
              memory: 2.5Gi
            limits:
              cpu: 1000m
              memory: 2.5Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-cert

        - name: private-key-volume
          secret:
            secretName: github-app-private-key
