apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectors-worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connectors-worker
  template:
    metadata:
      labels:
        app: connectors-worker
        name: connectors-worker-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "connectors-worker","service": "connectors","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: worker
          image: gcr.io/or1g1n-186209/connectors-image:latest
          command: ["npm", "run", "start:worker"]
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: connectors-config
            - secretRef:
                name: connectors-secrets

          volumeMounts:
            - name: cert-volume
              mountPath: /etc/certs

          resources:
            requests:
              cpu: 2000m
              memory: 8Gi

            limits:
              cpu: 2000m
              memory: 8Gi

      volumes:
        - name: cert-volume
          secret:
            secretName: temporal-cert
