apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-edge-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-edge
  template:
    metadata:
      labels:
        app: front-edge
        name: front-edge-pod
        admission.datadoghq.com/enabled: "true"
      annotations:
        ad.datadoghq.com/web.logs: '[{"source": "front","service": "front-edge","tags": ["env:prod"]}]'
    spec:
      containers:
        - name: web
          image: gcr.io/or1g1n-186209/front-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: front-edge-config
            - secretRef:
                name: front-secrets

          # override env vars from configmap/secret
          env:
            - name: CONNECTORS_API
              value: http://connectors-edge-service
            - name: NEXTAUTH_URL
              value: https://front-edge.dust.tt
            - name: URL
              value: https://front-edge.dust.tt

            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          resources:
            requests:
              cpu: 200m
              memory: 512Mi

      imagePullSecrets:
        - name: gcr-json-key
