import type { CreationOptional } from "sequelize";
import { DataTypes, Op } from "sequelize";

import { frontSequelize } from "@app/lib/resources/storage";
import { WorkspaceAwareModel } from "@app/lib/resources/storage/wrappers/workspace_models";
import type { CreditType } from "@app/types/credits";
import { CREDIT_TYPES } from "@app/types/credits";

/**
 * CreditModel stores consumable monetary credits for programmatic API usage.
 * Amounts are expressed in integer cents (USD).
 */
export class CreditModel extends WorkspaceAwareModel<CreditModel> {
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare type: CreditType;
  // When credit becomes active (null = not yet paid/active).
  declare startDate: Date | null;
  declare expirationDate: Date | null;
  // Amount in cents (immutable after creation).
  declare initialAmountCents: number;
  declare consumedAmountCents: number; // in cents
  // Discount percentage (0-100), nullable
  declare discount: number | null;
  // Stripe invoice ID or line item ID for idempotency.
  declare invoiceOrLineItemId: string | null;
}

CreditModel.init(
  {
    createdAt: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    updatedAt: {
      type: DataTypes.DATE,
      allowNull: false,
      defaultValue: DataTypes.NOW,
    },
    type: {
      type: DataTypes.STRING(16),
      allowNull: false,
      validate: {
        isIn: [CREDIT_TYPES],
      },
    },
    startDate: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: null,
    },
    expirationDate: {
      type: DataTypes.DATE,
      allowNull: true,
      defaultValue: null,
    },
    initialAmountCents: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    consumedAmountCents: {
      type: DataTypes.INTEGER,
      allowNull: false,
    },
    discount: {
      type: DataTypes.INTEGER,
      allowNull: true,
      defaultValue: null,
      validate: {
        min: 0,
        max: 100,
      },
    },
    invoiceOrLineItemId: {
      type: DataTypes.STRING,
      allowNull: true,
      defaultValue: null,
    },
  },
  {
    modelName: "credit",
    sequelize: frontSequelize,
    indexes: [
      { fields: ["workspaceId"] },
      { fields: ["workspaceId", "expirationDate"] },
      // Partial index equivalent: optimize lookups for credits with remaining balance.
      // Named index to avoid clashing with the autogenerated name for the one above.
      {
        fields: ["workspaceId", "expirationDate"],
        name: "credits_nonzero_remaining_idx",
        where: {
          consumedAmountCents: {
            [Op.lt]: frontSequelize.col("initialAmountCents"),
          },
        },
      },
      // Unique constraint on (workspaceId, invoiceOrLineItemId) to prevent duplicate credit purchases
      {
        fields: ["invoiceOrLineItemId"],
        unique: true,
        name: "credits_invoice_unique_idx",
        where: { invoiceOrLineItemId: { [Op.ne]: null } },
      },
      // Composite index for efficient queries on active credits
      {
        fields: ["workspaceId", "startDate", "expirationDate"],
        name: "credits_workspace_start_expiration_idx",
      },
      // Unique constraint on (type, workspaceId, startDate, expirationDate) for active credits
      {
        fields: ["type", "workspaceId", "startDate", "expirationDate"],
        unique: true,
        name: "credits_type_workspace_dates_unique_idx",
        where: { startDate: { [Op.ne]: null } },
      },
    ],
  }
);
