name: "Slack Notification"
description: "Send deployment notifications to Slack"

inputs:
  step:
    description: "Deployment step (start/build_success/failure)"
    required: true
  component:
    description: "Component being deployed"
    required: true
  image_tag:
    description: "Image tag being deployed"
    required: true
  channel:
    description: "Slack channel"
    required: true
  thread_ts:
    description: "Slack thread timestamp"
    required: false
  slack_token:
    description: "Slack bot token"
    required: true
  blocked:
    description: "Is deployment blocked?"
    required: false
  region:
    description: "Region being deployed to"
    required: false
  is_revert:
    description: "Whether reverting or deploying"
    required: false
    default: "false"
  current_version:
    description: "Current deployed version for comparison"
    required: false
  commit_diff:
    description: "Commit diff information"
    required: false
  commit_count:
    description: "Number of commits in the diff"
    required: false

outputs:
  thread_ts:
    description: "Slack thread timestamp from the initial message"
    value: ${{ steps.start_notification.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Get author info
      if: inputs.step == 'start'
      id: author
      shell: bash
      run: |
        AUTHOR_NAME="${{ github.actor }}"

        if ! EMAIL=$(grep "^$AUTHOR_NAME: " .authors | cut -d' ' -f2); then
          echo "GitHub handle $AUTHOR_NAME not found in authors file" >&2
          exit 1
        fi
        echo "email=$EMAIL" >> $GITHUB_OUTPUT

    - name: Lookup by email
      if: inputs.step == 'start'
      id: email
      uses: slackapi/slack-github-action@v2.0.0
      with:
        errors: false
        method: users.lookupByEmail
        token: ${{ inputs.slack_token }}
        payload: |
          email: "${{ steps.author.outputs.email }}"

    - name: Get Slack user ID
      if: inputs.step == 'start' && steps.email.outputs.ok == 'true'
      id: slack_user
      shell: bash
      run: |
        RESPONSE='${{ steps.email.outputs.response }}'
        if ! SLACK_ID=$(echo "$RESPONSE" | jq -r '.user.id'); then
          echo "Failed to extract Slack user ID" >&2
          exit 0
        fi
        echo "id=$SLACK_ID" >> $GITHUB_OUTPUT

    - name: Notify Build And Deploy Start
      if: inputs.step == 'start'
      id: start_notification
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_token }}
        payload: |
          channel: ${{ inputs.channel }}
          text: |
            ${{ inputs.is_revert == 'true' && '⏮️' || '🚀' }} ${{ inputs.is_revert == 'true' && 'Starting revert of' || 'Starting deployment of' }} ${{ inputs.component }} `${{ inputs.image_tag }}`
            • Region: `${{ inputs.region }}`
            • Commit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ inputs.image_tag }}>
            • Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View build>
            • Author: ${{ steps.slack_user.outputs.id != '' && format('<@{0}>', steps.slack_user.outputs.id) || format('`{0}`', steps.author.outputs.name) }}

    - name: Format commit message
      if: inputs.step == 'build_success'
      id: format_message
      shell: bash
      run: |
        MESSAGE="🔨 Build completed in ${{ inputs.region }} region\\n• Image: ${{ inputs.image_tag }}"
        
        # Add changes info if available
        if [ -n "${{ inputs.current_version }}" ]; then
          MESSAGE="$MESSAGE\\n• Changes: ${{ inputs.current_version }} → ${{ inputs.image_tag }} (${{ inputs.commit_count }} commits)"
        fi
        
        # Add formatted commits if available
        if [ -n "${{ inputs.commit_diff }}" ]; then
          COMMITS_RAW="${{ inputs.commit_diff }}"
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              COMMIT_HASH=$(echo "$line" | cut -d' ' -f1)
              AUTHOR=$(echo "$line" | sed 's/^[^ ]* //')
              MESSAGE="$MESSAGE\\n• <${{ github.server_url }}/${{ github.repository }}/commit/$COMMIT_HASH|$COMMIT_HASH> $AUTHOR"
            fi
          done <<< "$COMMITS_RAW"
        fi
        
        echo "message<<EOF" >> $GITHUB_OUTPUT
        echo "$MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Notify Build Success
      if: inputs.step == 'build_success'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_token }}
        payload: |
          channel: ${{ inputs.channel }}
          thread_ts: ${{ inputs.thread_ts }}
          text: ${{ steps.format_message.outputs.message }}

    - name: Notify Deploy Failure
      if: inputs.step == 'failure'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_token }}
        payload: |
          channel: ${{ inputs.channel }}
          thread_ts: "${{ inputs.thread_ts }}"
          text: |
            ❌ ${{ inputs.is_revert == 'true' && 'Revert' || 'Build' }} pipeline failed
            ${{ inputs.blocked == 'true' && format('Is blocked by channel topic: {0}', inputs.blocked) }}
            • Check logs: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View details>
