name: "Slack Notification"
description: "Send deployment notifications to Slack"

inputs:
  step:
    description: "Deployment step (start/build_success/failure)"
    required: true
  component:
    description: "Component being deployed"
    required: true
  image_tag:
    description: "Image tag being deployed"
    required: true
  channel:
    description: "Slack channel"
    required: true
  thread_ts:
    description: "Slack thread timestamp"
    required: false
  slack_token:
    description: "Slack bot token"
    required: true
  blocked:
    description: "Is deployment blocked?"
    required: false
  region:
    description: "Region being deployed to"
    required: false
  is_revert:
    description: "Whether reverting or deploying"
    required: false
    default: "false"
  current_version:
    description: "Current deployed version for comparison"
    required: false
  commit_diff:
    description: "Commit diff information"
    required: false
  commit_count:
    description: "Number of commits in the diff"
    required: false

outputs:
  thread_ts:
    description: "Slack thread timestamp from the initial message"
    value: ${{ steps.start_notification.outputs.ts }}

runs:
  using: "composite"
  steps:
    - name: Get author info
      if: inputs.step == 'start'
      id: author
      shell: bash
      run: |
        AUTHOR_NAME="${{ github.actor }}"

        if ! EMAIL=$(grep "^$AUTHOR_NAME: " .authors | cut -d' ' -f2); then
          echo "GitHub handle $AUTHOR_NAME not found in authors file" >&2
          exit 1
        fi
        echo "email=$EMAIL" >> $GITHUB_OUTPUT

    - name: Lookup by email
      if: inputs.step == 'start'
      id: email
      uses: slackapi/slack-github-action@v2.0.0
      with:
        errors: false
        method: users.lookupByEmail
        token: ${{ inputs.slack_token }}
        payload: |
          email: "${{ steps.author.outputs.email }}"

    - name: Get Slack user ID
      if: inputs.step == 'start' && steps.email.outputs.ok == 'true'
      id: slack_user
      shell: bash
      run: |
        RESPONSE='${{ steps.email.outputs.response }}'
        if ! SLACK_ID=$(echo "$RESPONSE" | jq -r '.user.id'); then
          echo "Failed to extract Slack user ID" >&2
          exit 0
        fi
        echo "id=$SLACK_ID" >> $GITHUB_OUTPUT

    - name: Notify Build And Deploy Start
      if: inputs.step == 'start'
      id: start_notification
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_token }}
        payload: |
          channel: ${{ inputs.channel }}
          text: |
            ${{ inputs.is_revert == 'true' && '⏮️' || '🚀' }} ${{ inputs.is_revert == 'true' && 'Starting revert of' || 'Starting deployment of' }} ${{ inputs.component }} `${{ inputs.image_tag }}`
            • Region: `${{ inputs.region }}`
            • Commit: <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|${{ inputs.image_tag }}>
            • Workflow: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View build>
            • Author: ${{ steps.slack_user.outputs.id != '' && format('<@{0}>', steps.slack_user.outputs.id) || format('`{0}`', steps.author.outputs.name) }}

    - name: Format and Build Payload
      if: inputs.step == 'build_success'
      id: build_payload
      shell: bash
      run: |
        # 1. Build Text Content
        HEADER="🔨 *Build completed in ${{ inputs.region }} region*"
        DETAILS="• Image: \`${{ inputs.image_tag }}\`"

        if [ -n "${{ inputs.current_version }}" ]; then
          DETAILS="${DETAILS}
        • Changes: ${{ inputs.current_version }} → ${{ inputs.image_tag }} (${{ inputs.commit_count }} commits)"
        fi

        # Combine Header and Details
        MAIN_TEXT="$HEADER
        $DETAILS"

        # 2. Build Changelog Content
        CHANGELOG=""
        if [ -n "${{ inputs.commit_diff }}" ]; then
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              COMMIT_HASH=$(echo "$line" | cut -d' ' -f1)
              AUTHOR=$(echo "$line" | sed 's/^[^ ]* //')
              CHANGELOG="${CHANGELOG}• <${{ github.server_url }}/${{ github.repository }}/commit/${COMMIT_HASH}|${COMMIT_HASH}> ${AUTHOR}
        "
            fi
          done <<< "${{ inputs.commit_diff }}"
        fi

        # 3. Construct JSON using simplified jq logic
        # We create the two block objects first

        # Block 1: Main Info
        BLOCK1=$(jq -c -n --arg text "$MAIN_TEXT" '{type: "section", text: {type: "mrkdwn", text: $text}}')

        # Block 2: Changelog (only if exists)
        if [ -n "$CHANGELOG" ]; then
           BLOCK2=$(jq -c -n --arg text "$CHANGELOG" '{type: "section", text: {type: "mrkdwn", text: $text}}')
           # Combine into array
           BLOCKS="[$BLOCK1, $BLOCK2]"
        else
           BLOCKS="[$BLOCK1]"
        fi

        # 4. Create Final Payload
        # We pass the pre-built JSON array 'blocks' directly into the final object
        # utilizing --argjson to interpret it as JSON, not a string.
        JSON_PAYLOAD=$(jq -c -n \
          --arg channel "${{ inputs.channel }}" \
          --arg ts "${{ inputs.thread_ts }}" \
          --argjson blocks "$BLOCKS" \
          '{channel: $channel, thread_ts: $ts, blocks: $blocks}')

        echo "json_payload=$JSON_PAYLOAD" >> $GITHUB_OUTPUT

    - name: Notify Build Success
      if: inputs.step == 'build_success'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_token }}
        payload: ${{ steps.build_payload.outputs.json_payload }}

    - name: Notify Deploy Failure
      if: inputs.step == 'failure'
      uses: slackapi/slack-github-action@v2.0.0
      with:
        method: chat.postMessage
        token: ${{ inputs.slack_token }}
        payload: |
          channel: ${{ inputs.channel }}
          thread_ts: "${{ inputs.thread_ts }}"
          text: |
            ❌ ${{ inputs.is_revert == 'true' && 'Revert' || 'Build' }} pipeline failed
            ${{ inputs.blocked == 'true' && format('Is blocked by channel topic: {0}', inputs.blocked) }}
            • Check logs: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View details>
