export const WHITELISTABLE_FEATURES = [
  "advanced_notion_management",
  "agent_builder_v2",
  "agent_builder_v2",
  "agent_discovery",
  "agent_discovery",
  "claude_3_7_reasoning",
  "claude_4_opus_feature",
  "co_edition",
  "custom_webcrawler",
  "deepseek_feature",
  "deepseek_r1_global_agent_feature",
  "dev_mcp_actions",
  "disable_run_logs",
  "disallow_agent_creation_to_users",
  "disallow_agent_creation_to_users",
  "document_tracker",
  "exploded_tables_query",
  "extended_max_steps_per_run",
  "force_gdrive_labels_scope",
  "gmail_tool",
  "gmail_tool",
  "google_ai_studio_experimental_models_feature",
  "google_calendar_tool",
  "google_calendar_tool",
  "index_private_slack_channel",
  "labs_salesforce_personal_connections",
  "labs_trackers",
  "labs_transcripts",
  "okta_enterprise_connection",
  "openai_o1_custom_assistants_feature",
  "openai_o1_feature",
  "openai_o1_high_reasoning_custom_assistants_feature",
  "openai_o1_high_reasoning_feature",
  "openai_o1_mini_feature",
  "pro_plan_salesforce_connector",
  "salesforce_feature",
  "salesforce_tool",
  "search_knowledge_builder",
  "show_debug_tools",
  "snowflake_connector_feature",
  "usage_data_api",
  "workos",
  "xai_feature",
] as const;
export type WhitelistableFeature = (typeof WHITELISTABLE_FEATURES)[number];
export function isWhitelistableFeature(
  feature: unknown
): feature is WhitelistableFeature {
  return WHITELISTABLE_FEATURES.includes(feature as WhitelistableFeature);
}
