included:
  - Dust

excluded:
  - Dust.xcodeproj

disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_filter_count
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - modifier_order
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_first_last
  - unowned_variable_capture
  - vertical_whitespace_closing_braces

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100
