const GREETINGS = [
  "Hey [Name]! 👋",
  "Good to see you, [Name]! 😊",
  "What's up, [Name]? 🙌",
  "How's it going, [Name]? 🚀",
  "Hiya, [Name]! 🌟",
  "Yo [Name]! 😎",
  "Welcome, [Name]! 🎉",
  "Howdy, [Name]! 🤠",
  "Greetings, [Name]! 🌈",
  "Salutations, [Name]! 🎩",
  "What's new, [Name]? 💌",
  "How are you, [Name]? 🤗",
  "Ahoy, [Name]! ⚓",
  "Bonjour, [Name]! 🥖",
  "Hola, [Name]! 🌮",
  "Ciao, [Name]! 🍕",
  "Namaste, [Name]! 🕉",
  "Konnichiwa, [Name]! 🎌",
  "Aloha, [Name]! 🌺",
  "Hey there, [Name]! 💡",
  "How's everything, [Name]? 📈",
  "Good day, [Name]! 🌞",
  "Welcome back, [Name]! 🔄",
  "Long time no see, [Name]! ⏰",
  "Great to meet you, [Name]! 🤝",
  "Pleased to see you, [Name]! 😁",
  "Cheers, [Name]! 🥂",
  "Top of the morning, [Name]! 🍀",
  "Happy to chat, [Name]! 💬",
  "What's happening, [Name]? 🎈",
  "How's life treating you, [Name]? 🎠",
  "Missed you, [Name]! 💔",
  "Glad you're here, [Name]! 📍",
  "Smile, [Name]! 😄",
  "Lookin' good, [Name]! 👍",
  "What's cooking, [Name]? 🍳",
  "How's the family, [Name]? 👨‍👩‍👧‍👦",
  "Stay cool, [Name]! ❄️",
  "Keep shining, [Name]! 💎",
  "You're a star, [Name]! ⭐",
  "Rise and shine, [Name]! 🌅",
  "Keep it up, [Name]! 💪",
  "Rock on, [Name]! 🤘",
];

export function getRandomGreetingForName(firstName: string) {
  const randomIndex = Math.floor(Math.random() * GREETINGS.length);
  return GREETINGS[randomIndex].replace("[Name]", firstName);
}
