import { rm } from "node:fs/promises";
import { join } from "node:path";
import { getEnvFilePath } from "./paths";

function getDirenvBlock(name: string, envShPath: string): string {
  return [
    `# >>> dust-hive ${name} >>>`,
    "# Auto-generated by dust-hive - sources environment for this worktree",
    `source "${envShPath}"`,
    `# <<< dust-hive ${name} <<<`,
  ].join("\n");
}

export function removeDirenvBlock(content: string, name: string): string {
  const startMarker = `# >>> dust-hive ${name} >>>`;
  const endMarker = `# <<< dust-hive ${name} <<<`;
  const start = content.indexOf(startMarker);
  if (start === -1) {
    return content;
  }

  const end = content.indexOf(endMarker, start);
  if (end === -1) {
    return content;
  }

  const afterEnd = end + endMarker.length;
  const before = content.slice(0, start).trimEnd();
  const after = content.slice(afterEnd).replace(/^\s*\n/, "");

  if (!before) {
    return after.trimStart();
  }

  if (!after) {
    return `${before}\n`;
  }

  return `${before}\n\n${after}`;
}

// Setup .envrc to source the env.sh file and enable direnv.
export async function setupDirenv(
  name: string,
  worktreePath: string,
  options: { preserveExisting?: boolean } = {}
): Promise<void> {
  const envShPath = getEnvFilePath(name);
  const envrcPath = join(worktreePath, ".envrc");
  const envrcBlock = getDirenvBlock(name, envShPath);

  if (options.preserveExisting) {
    const file = Bun.file(envrcPath);
    const existing = (await file.exists()) ? await file.text() : "";
    const withoutExistingBlock = removeDirenvBlock(existing, name).trimEnd();
    const envrcContent = withoutExistingBlock
      ? `${withoutExistingBlock}\n\n${envrcBlock}\n`
      : `${envrcBlock}\n`;
    await Bun.write(envrcPath, envrcContent);
  } else {
    await Bun.write(envrcPath, `${envrcBlock}\n`);
  }

  const proc = Bun.spawn(["direnv", "allow", worktreePath], {
    cwd: worktreePath,
    stdout: "ignore",
    stderr: "ignore",
  });
  await proc.exited;
}

export async function removeDirenvIntegration(name: string, worktreePath: string): Promise<void> {
  const envrcPath = join(worktreePath, ".envrc");
  const file = Bun.file(envrcPath);
  if (!(await file.exists())) {
    return;
  }

  const existing = await file.text();
  const next = removeDirenvBlock(existing, name);
  if (next === existing) {
    return;
  }

  if (next.trim().length === 0) {
    await rm(envrcPath, { force: true });
    return;
  }

  await Bun.write(envrcPath, next);
}
