/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/conversations` | `/conversations`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/conversations/[id]` | `/conversations/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(drawer)'}/conversations/[id]/message/[messageId]` | `/conversations/[id]/message/[messageId]`, params: Router.UnknownInputParams & { id: string | number;messageId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/conversations` | `/conversations`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(drawer)'}/conversations/[id]` | `/conversations/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(drawer)'}/conversations/[id]/message/[messageId]` | `/conversations/[id]/message/[messageId]`, params: Router.UnknownOutputParams & { id: string;messageId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/conversations${`?${string}` | `#${string}` | ''}` | `/conversations${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(drawer)'}/conversations` | `/conversations`; params?: Router.UnknownInputParams; } | `${'/(drawer)'}/conversations/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/conversations/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(drawer)'}/conversations/${Router.SingleRoutePart<T>}/message/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/conversations/${Router.SingleRoutePart<T>}/message/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(drawer)'}/conversations/[id]` | `/conversations/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(drawer)'}/conversations/[id]/message/[messageId]` | `/conversations/[id]/message/[messageId]`, params: Router.UnknownInputParams & { id: string | number;messageId: string | number; } };
    }
  }
}
