#!/usr/bin/env bash
set -euo pipefail

if [ "$(id -u)" = 0 ]; then
  echo "Run Frame lint as the sandbox user, not root" >&2
  exit 1
fi

templates=$(cd -- "$(dirname -- "$0")" && pwd)
project=$(cd -- "${1:-.}" && pwd)
viz_url=${DUST_VIZ_URL:?Set DUST_VIZ_URL to the Viz origin}
cache=${DUST_FRAME_TYPES_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/dust/frame-types}
marker='// Generated by Frame lint'

if [ ! -f "$project/manifest.json" ] && [ ! -f "$project/index.tsx" ]; then
  echo "Expected a Frame folder containing manifest.json or index.tsx" >&2
  exit 1
fi
for config in tsconfig.json .oxlintrc.json; do
  if [ -L "$project/$config" ] || { [ -e "$project/$config" ] && [ "$(head -n 1 "$project/$config")" != "$marker" ]; }; then
    echo "Refusing to replace $project/$config. Frame lint requires its standard configs" >&2
    exit 1
  fi
done

manifest=$(curl --fail --silent --show-error --location --max-time 30 \
  --max-filesize 65536 "${viz_url%/}/frame-runtime/manifest.json")
id=$(jq -er 'select(.version == 1) | .id | select(test("^[a-f0-9]{64}$"))' <<< "$manifest")
checksum=$(jq -er '.tarballSha256 | select(test("^[a-f0-9]{64}$"))' <<< "$manifest")
size=$(jq -er '.sizeBytes | select(. > 0 and . <= 20971520)' <<< "$manifest")
modules=$(jq -ce '.modules | select(length > 0 and all(.[]; type == "string"))' <<< "$manifest")
mkdir -p -- "$cache"
cache=$(cd -- "$cache" && pwd)
types="$cache/$id"

if [ ! -d "$types" ]; then
  staging=$(mktemp -d "$cache/.download.XXXXXX")
  trap 'rm -rf -- "$staging"' EXIT
  archive="$staging/types.tgz"
  curl --fail --silent --show-error --location --max-time 30 \
    --max-filesize 20971520 --output "$archive" \
    "${viz_url%/}/frame-runtime/$checksum.tgz"
  if [ "$(wc -c < "$archive" | tr -d ' ')" != "$size" ]; then
    echo "Viz types archive size mismatch" >&2
    exit 1
  fi
  if command -v sha256sum >/dev/null; then
    actual=$(sha256sum "$archive")
  else
    actual=$(shasum -a 256 "$archive")
  fi
  if [ "${actual%% *}" != "$checksum" ]; then
    echo "Viz types archive checksum mismatch" >&2
    exit 1
  fi
  mkdir "$staging/$id"
  tar -xzf "$archive" -C "$staging/$id"
  test -f "$staging/$id/tsconfig.json"
  test -f "$staging/$id/index.d.ts"
  # A concurrent lint may have cached the same archive already.
  if ! mv "$staging/$id" "$cache/"; then
    test -f "$types/tsconfig.json"
  fi
  rm -rf -- "$staging"
  trap - EXIT
fi

{
  echo "$marker"
  jq --arg config "$types/tsconfig.json" '.extends = $config' "$templates/tsconfig.json"
} > "$project/tsconfig.json"
{
  echo "$marker"
  jq --argjson modules "$modules" \
    '.rules["no-restricted-imports"][1].patterns[0].group += ($modules | map("!" + .))' \
    "$templates/oxlintrc.json"
} > "$project/.oxlintrc.json"

cd -- "$project"
exec oxlint --type-aware --type-check --disable-nested-config --format unix \
  --config .oxlintrc.json .
