import "./styles/global.css";

import { SparkleContext } from "./context";
export { SparkleContext };

import { Button } from "./components/Button";
export { Button };

import { Tab } from "./components/Tab";
export { Tab };

import { Item } from "./components/Item";
export { Item };

import { Icon } from "./components/Icon";
export { Icon };

import { Logo } from "./logo";
export { Logo };

import {
  ArrowUpOnSquare as ArrowUpOnSquareIcon,
  Beaker as BeakerIcon,
  BeakerPlus as BeakerPlusIcon,
  ChatBubbleBottomCenterPlus as ChatBubbleBottomCenterPlusIcon,
  ChatBubbleBottomCenterText as ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRight as ChatBubbleLeftRightIcon,
  CheckCircle as CheckCircleIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  Clipboard as ClipboardIcon,
  CloudArrowDown as CloudArrowDownIcon,
  Cog6Tooth as Cog6ToothIcon,
  CommandLine as CommandLineIcon,
  DocumentPlus as DocumentPlusIcon,
  DocumentText as DocumentTextIcon,
  ExclamationCircle as ExclamationCircleIcon,
  FolderOpen as FolderOpenIcon,
  HandThumbDown as HandThumbDownIcon,
  HandThumbUp as HandThumbUpIcon,
  InformationCircle as InformationCircleIcon,
  Key as KeyIcon,
  MagnifyingGlass as MagnifyingGlassIcon,
  PaperAirplane as PaperAirplaneIcon,
  PencilSquare as PencilSquareIcon,
  Plus as PlusIcon,
  QuestionMarkCircle as QuestionMarkCircleIcon,
  Server as ServerIcon,
  Square3Stack3D as Square3Stack3DIcon,
  XCircle as XCircleIcon,
  XMark as XMarkIcon,
} from "./icons/mini";

export {
  ArrowUpOnSquareIcon,
  BeakerIcon,
  BeakerPlusIcon,
  ChatBubbleBottomCenterPlusIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardIcon,
  CloudArrowDownIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  ExclamationCircleIcon,
  FolderOpenIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  InformationCircleIcon,
  KeyIcon,
  MagnifyingGlassIcon,
  PaperAirplaneIcon,
  PencilSquareIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  ServerIcon,
  Square3Stack3DIcon,
  XCircleIcon,
  XMarkIcon,
};

import {
  ArrowUpOnSquare as ArrowUpOnSquareStrokeIcon,
  Beaker as BeakerStrokeIcon,
  BeakerPlus as BeakerPlusStrokeIcon,
  ChatBubbleBottomCenterPlus as ChatBubbleBottomCenterPlusStrokeIcon,
  ChatBubbleBottomCenterText as ChatBubbleBottomCenterTextStrokeIcon,
  ChatBubbleLeftRight as ChatBubbleLeftRightStrokeIcon,
  CheckCircle as CheckCircleStrokeIcon,
  ChevronDown as ChevronDownStrokeIcon,
  ChevronLeft as ChevronLeftStrokeIcon,
  ChevronRight as ChevronRightStrokeIcon,
  ChevronUp as ChevronUpStrokeIcon,
  Clipboard as ClipboardStrokeIcon,
  CloudArrowDown as CloudArrowDownStrokeIcon,
  Cog6Tooth as Cog6ToothStrokeIcon,
  CommandLine as CommandLineStrokeIcon,
  DocumentPlus as DocumentPlusStrokeIcon,
  DocumentText as DocumentTextStrokeIcon,
  ExclamationCircle as ExclamationCircleStrokeIcon,
  FolderOpen as FolderOpenStrokeIcon,
  HandThumbDown as HandThumbDownStrokeIcon,
  HandThumbUp as HandThumbUpStrokeIcon,
  InformationCircle as InformationCircleStrokeIcon,
  Key as KeyStrokeIcon,
  MagnifyingGlass as MagnifyingGlassStrokeIcon,
  PaperAirplane as PaperAirplaneStrokeIcon,
  PencilSquare as PencilSquareStrokeIcon,
  Plus as PlusStrokeIcon,
  QuestionMarkCircle as QuestionMarkCircleStrokeIcon,
  Server as ServerStrokeIcon,
  Square3Stack3D as Square3Stack3DStrokeIcon,
  XCircle as XCircleStrokeIcon,
  XMark as XMarkStrokeIcon,
} from "./icons/solid_stroke";

export {
  ArrowUpOnSquareStrokeIcon,
  BeakerPlusStrokeIcon,
  BeakerStrokeIcon,
  ChatBubbleBottomCenterPlusStrokeIcon,
  ChatBubbleBottomCenterTextStrokeIcon,
  ChatBubbleLeftRightStrokeIcon,
  CheckCircleStrokeIcon,
  ChevronDownStrokeIcon,
  ChevronLeftStrokeIcon,
  ChevronRightStrokeIcon,
  ChevronUpStrokeIcon,
  ClipboardStrokeIcon,
  CloudArrowDownStrokeIcon,
  Cog6ToothStrokeIcon,
  CommandLineStrokeIcon,
  DocumentPlusStrokeIcon,
  DocumentTextStrokeIcon,
  ExclamationCircleStrokeIcon,
  FolderOpenStrokeIcon,
  HandThumbDownStrokeIcon,
  HandThumbUpStrokeIcon,
  InformationCircleStrokeIcon,
  KeyStrokeIcon,
  MagnifyingGlassStrokeIcon,
  PaperAirplaneStrokeIcon,
  PencilSquareStrokeIcon,
  PlusStrokeIcon,
  QuestionMarkCircleStrokeIcon,
  ServerStrokeIcon,
  Square3Stack3DStrokeIcon,
  XCircleStrokeIcon,
  XMarkStrokeIcon,
};

import {
  ArrowUpOnSquare as ArrowUpOnSquareSolidIcon,
  Beaker as BeakerSolidIcon,
  BeakerPlus as BeakerPlusSolidIcon,
  ChatBubbleBottomCenterPlus as ChatBubbleBottomCenterPlusSolidIcon,
  ChatBubbleBottomCenterText as ChatBubbleBottomCenterTextSolidIcon,
  ChatBubbleLeftRight as ChatBubbleLeftRightSolidIcon,
  CheckCircle as CheckCircleSolidIcon,
  ChevronDown as ChevronDownSolidIcon,
  ChevronLeft as ChevronLeftSolidIcon,
  ChevronRight as ChevronRightSolidIcon,
  ChevronUp as ChevronUpSolidIcon,
  Clipboard as ClipboardSolidIcon,
  CloudArrowDown as CloudArrowDownSolidIcon,
  Cog6Tooth as Cog6ToothSolidIcon,
  CommandLine as CommandLineSolidIcon,
  DocumentPlus as DocumentPlusSolidIcon,
  DocumentText as DocumentTextSolidIcon,
  ExclamationCircle as ExclamationCircleSolidIcon,
  FolderOpen as FolderOpenSolidIcon,
  HandThumbDown as HandThumbDownSolidIcon,
  HandThumbUp as HandThumbUpSolidIcon,
  InformationCircle as InformationCircleSolidIcon,
  Key as KeySolidIcon,
  MagnifyingGlass as MagnifyingGlassSolidIcon,
  PaperAirplane as PaperAirplaneSolidIcon,
  PencilSquare as PencilSquareSolidIcon,
  Plus as PlusSolidIcon,
  QuestionMarkCircle as QuestionMarkCircleSolidIcon,
  Server as ServerSolidIcon,
  Square3Stack3D as Square3Stack3DSolidIcon,
  XCircle as XCircleSolidIcon,
  XMark as XMarkSolidIcon,
} from "./icons/solid";

export {
  ArrowUpOnSquareSolidIcon,
  BeakerPlusSolidIcon,
  BeakerSolidIcon,
  ChatBubbleBottomCenterPlusSolidIcon,
  ChatBubbleBottomCenterTextSolidIcon,
  ChatBubbleLeftRightSolidIcon,
  CheckCircleSolidIcon,
  ChevronDownSolidIcon,
  ChevronLeftSolidIcon,
  ChevronRightSolidIcon,
  ChevronUpSolidIcon,
  ClipboardSolidIcon,
  CloudArrowDownSolidIcon,
  Cog6ToothSolidIcon,
  CommandLineSolidIcon,
  DocumentPlusSolidIcon,
  DocumentTextSolidIcon,
  ExclamationCircleSolidIcon,
  FolderOpenSolidIcon,
  HandThumbDownSolidIcon,
  HandThumbUpSolidIcon,
  InformationCircleSolidIcon,
  KeySolidIcon,
  MagnifyingGlassSolidIcon,
  PaperAirplaneSolidIcon,
  PencilSquareSolidIcon,
  PlusSolidIcon,
  QuestionMarkCircleSolidIcon,
  ServerSolidIcon,
  Square3Stack3DSolidIcon,
  XCircleSolidIcon,
  XMarkSolidIcon,
};
