export interface TeamMember {
  name: string;
  title: string;
  image: string;
  linkedIn: string | null;
  github: string;
}

export const PEOPLE: Record<string, TeamMember> = {
  spolu: {
    name: "Stanislas Polu",
    title: "Co-founder, CTO",
    image: "https://avatars.githubusercontent.com/u/15067",
    linkedIn: "https://www.linkedin.com/in/spolu",
    github: "https://github.com/spolu",
  },
  gabhubert: {
    name: "Gabriel Hubert",
    title: "Co-founder, CEO",
    image: "https://avatars.githubusercontent.com/u/998689",
    linkedIn: "https://linkedin.com/in/gabhubert",
    github: "https://github.com/gabhubert",
  },
  fontanierh: {
    name: "Henry Fontanier",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/14199823",
    linkedIn: "https://www.linkedin.com/in/hfontanier/",
    github: "https://github.com/fontanierh",
  },
  pr: {
    name: "Philippe Rolet",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/5437393",
    linkedIn: "https://www.linkedin.com/in/philipperolet/",
    github: "https://github.com/philipperolet",
  },
  ed: {
    name: "Edouard Wautier",
    title: "Principal Designer",
    image: "https://avatars.githubusercontent.com/u/4435185",
    linkedIn: "https://www.linkedin.com/in/edouardwautier/",
    github: "https://github.com/Duncid",
  },
  popdaph: {
    name: "Daphné Popin",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/3803406",
    linkedIn: "https://www.linkedin.com/in/popdaph/",
    github: "https://github.com/popdaph",
  },
  yutcam: {
    name: "Pauline Pham",
    title: "Operations",
    image: "https://avatars.githubusercontent.com/u/33726902",
    linkedIn: "https://www.linkedin.com/in/pauline-pham1",
    github: "https://github.com/Yutcam",
  },
  flvndvd: {
    name: "Flavien David",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/7428970",
    linkedIn: "https://www.linkedin.com/in/flavien-david/",
    github: "https://github.com/flvndvd",
  },
  nchinot: {
    name: "Nicolas Chinot",
    title: "US GM",
    image: "https://avatars.githubusercontent.com/u/13472346",
    linkedIn: "https://www.linkedin.com/in/nicolaschinot/",
    github: "https://github.com/nchinot",
  },
  clementb: {
    name: "Clément Bruneau",
    title: "Sales",
    image: "https://avatars.githubusercontent.com/u/120678252?v=4",
    github: "https://github.com/clmrn",
    linkedIn: "https://www.linkedin.com/in/bruneauclement",
  },
  tmartin: {
    name: "Thibault Martin",
    title: "GTM & Operations",
    image: "https://avatars.githubusercontent.com/u/168569391?v=4",
    github: "https://github.com/thib-martin",
    linkedIn: "https://www.linkedin.com/in/thibault-martin-27b19b5a/",
  },
  jbelveze: {
    name: "Jules Belveze",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/32683010",
    github: "https://github.com/JulesBelveze",
    linkedIn: "https://www.linkedin.com/in/jules-belveze",
  },
  tdraier: {
    name: "Thomas Draier",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/729255",
    linkedIn: "https://www.linkedin.com/in/tdraier/",
    github: "https://github.com/tdraier",
  },
  fraggle: {
    name: "Sébastien Flory",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/24419?v=4",
    github: "https://github.com/Fraggle",
    linkedIn: "https://www.linkedin.com/in/fraggle/",
  },
  adugre: {
    name: "Adèle Dugré",
    title: "EMEA Customer Success",
    image: "https://avatars.githubusercontent.com/u/180963192",
    linkedIn: "https://www.linkedin.com/in/ad%C3%A8le-dugr%C3%A9-7484a120/",
    github: "https://github.com/Adugre",
  },
  atchoi: {
    name: "Aubin Tchoi",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/60398825",
    github: "https://github.com/aubin-tchoi",
    linkedIn: "https://www.linkedin.com/in/aubin-tchoi",
  },
  apinot: {
    name: "Alexandre Pinot",
    title: "Product Designer",
    image: "https://avatars.githubusercontent.com/u/32997243?v=4",
    github: "https://github.com/pinotalexandre",
    linkedIn: "https://www.linkedin.com/in/pinotalexandre/",
  },
  adeltombe: {
    name: "Amelie Deltombe",
    title: "Marketing",
    image: "https://avatars.githubusercontent.com/u/183381801?v=4",
    github: "https://github.com/ameliedrhub",
    linkedIn: "https://www.linkedin.com/in/ameliedeltombe/",
  },
  tvanneufville: {
    name: "Theo Vanneufville",
    title: "Operations",
    image: "https://avatars.githubusercontent.com/u/190379594?v=4",
    github: "https://github.com/theo-vanneufville",
    linkedIn: "https://www.linkedin.com/in/th%C3%A9o-vanneufville-aab050193/",
  },
  kevin: {
    name: "Kevin Straszburger",
    title: "Community",
    image: "https://avatars.githubusercontent.com/u/7229871?v=4",
    github: "https://github.com/k7vin",
    linkedIn: "https://www.linkedin.com/in/kevinstraszburger/",
  },
  frank: {
    name: "Frank Aloia",
    title: "Forward Deployed Engineer",
    image: "https://avatars.githubusercontent.com/u/201725577",
    github: "https://github.com/frankaloia",
    linkedIn: "https://www.linkedin.com/in/frank-aloia-39907a12b/",
  },
  gina: {
    name: "Gina Kabasakalis",
    title: "Go To Market",
    image: "https://avatars.githubusercontent.com/u/202673816?v=4",
    linkedIn: "https://www.linkedin.com/in/ginakabasakalis/",
    github: "https://github.com/gina-dust/",
  },
  adrsimon: {
    name: "Adrien Simon",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/99071153",
    github: "https://github.com/adrsimon",
    linkedIn: "https://www.linkedin.com/in/adrsimon/",
  },
  stephen: {
    name: "Stephen Bronnec",
    title: "Forward Deployed Engineer",
    image: "https://avatars.githubusercontent.com/u/11921176?v=4",
    github: "https://github.com/FlagBenett",
    linkedIn: "https://www.linkedin.com/in/stephen-bronnec-3033a02b/",
  },
  ykmsd: {
    name: "Yuka Masuda",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/3702771?v=4",
    github: "https://github.com/ykmsd",
    linkedIn: "https://www.linkedin.com/in/ykmsd/",
  },
  victor: {
    name: "Victor Pery",
    title: "Account Executive",
    image: "https://avatars.githubusercontent.com/u/205647687?v=4",
    github: "https://github.com/victorpery",
    linkedIn: "https://www.linkedin.com/in/victor-pery/",
  },
  gaelle: {
    name: "Gaëlle Caplier",
    title: "Customer Success",
    image: "https://avatars.githubusercontent.com/u/49072037?v=4",
    github: "https://github.com/gcaplier",
    linkedIn: "https://www.linkedin.com/in/gcaplier/",
  },
  lena: {
    name: "Léna Caloud",
    title: "Customer Success",
    image: "https://avatars.githubusercontent.com/u/212004840?v=4",
    github: "https://github.com/lcaloud",
    linkedIn: "https://www.linkedin.com/in/lenacaloud/",
  },
  david: {
    name: "David Ebbo",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/556238?v=4",
    github: "https://github.com/davidebbo",
    linkedIn: "https://www.linkedin.com/in/davidebbo",
  },
  edouard: {
    name: "Edouard Villette",
    title: "Senior Account Executive",
    image: "https://avatars.githubusercontent.com/u/215458058?v=4",
    github: "https://github.com/TrismoEd",
    linkedIn: "https://www.linkedin.com/in/edouard-villette",
  },
  vince: {
    name: "Vince Sarkisian",
    title: "Solutions Engineer",
    image: "https://avatars.githubusercontent.com/u/1455646?v=4",
    github: "https://github.com/vincesarkisian",
    linkedIn: "https://www.linkedin.com/in/vincesarkisian/",
  },
  louis: {
    name: "Louis Caulet",
    title: "Enterprise Account Executive",
    image: "https://avatars.githubusercontent.com/u/218741719?v=4",
    github: "https://github.com/louiscaulet",
    linkedIn: "https://www.linkedin.com/in/louiscaulet",
  },
  faateh: {
    name: "Faateh Dhillon",
    title: "Senior Account Executive",
    image: "https://ca.slack-edge.com/T050RH73H9P-U093VA8B7E0-e078a8e04a44-512",
    github: "https://github.com/faateh-dust",
    linkedIn: "https://www.linkedin.com/in/faatehalidhillon",
  },
  nicole: {
    name: "Nicole Kreider",
    title: "Account Executive",
    image: "https://avatars.githubusercontent.com/u/222190268?v=4",
    github: "https://github.com/nkreider-dot",
    linkedIn: "https://www.linkedin.com/in/nkreider",
  },
  lauriane: {
    name: "Lauriane Paour",
    title: "Solution Engineer",
    image: "https://avatars.githubusercontent.com/u/222254800?v=4",
    linkedIn: "https://www.linkedin.com/in/lauriane-paour-152760106/",
    github: "https://github.com/laurianepao",
  },
  come: {
    name: "Côme Lucien-Brun",
    title: "Account Executive",
    image: "https://avatars.githubusercontent.com/u/227444187?v=4",
    github: "https://github.com/come-lb",
    linkedIn: "https://www.linkedin.com/in/comelb",
  },
  theog: {
    name: "Théo Gantzer",
    title: "Data",
    image: "https://avatars.githubusercontent.com/u/11852762?v=4",
    linkedIn: "https://www.linkedin.com/in/theo-gantzer",
    github: "https://github.com/theogz",
  },
  okal: {
    name: "Okal Otieno",
    title: "Solution Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09ATLV5RNX-f840cb7fa121-512",
    linkedIn: "https://www.linkedin.com/in/okalotieno",
    github: "https://github.com/okal",
  },
  z: {
    name: "Zeïd Marouf",
    title: "Security Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09DVNRFDJL-bbc7ebca4159-512",
    linkedIn: "https://www.linkedin.com/in/zeidmarouf",
    github: "https://github.com/zmarouf",
  },
  rcs: {
    name: "Rémy-Christophe Schermesser",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/16667?v=4",
    linkedIn: "https://www.linkedin.com/in/r%C3%A9my-christophe-s-0204834/",
    github: "https://github.com/ElPicador",
  },
  pierre: {
    name: "Pierre Milliotte",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/39985796?v=4",
    linkedIn: "https://www.linkedin.com/in/pierre-milliotte-664962a4/",
    github: "https://github.com/pmilliotte",
  },
  alex: {
    name: "Alexandre Casanova",
    title: "Enterprise Account Executive",
    image: "https://avatars.githubusercontent.com/u/229972775?v=4",
    linkedIn: "https://www.linkedin.com/in/alexandre-casanova-a89927a5/",
    github: "https://github.com/AlexandreCasa",
  },
  neyla: {
    name: "Neyla Belmaachi",
    title: "Business Development Representative",
    image: "https://avatars.githubusercontent.com/u/129662164?v=4",
    linkedIn: "https://www.linkedin.com/in/neyla-belmaachi-4817b0166/",
    github: "https://github.com/neylabelmaachi",
  },
  leandre: {
    name: "Leandre Le Bizec",
    title: "Forward Deployed Engineer",
    image: "https://avatars.githubusercontent.com/u/95234460?v=4",
    linkedIn: "https://www.linkedin.com/in/leandre-lebizec/",
    github: "https://github.com/LeandreLeBizec",
  },
  iliasbet: {
    name: "Ilias Bettahi",
    title: "Support Engineer",
    image: "https://avatars.githubusercontent.com/iliasbet",
    linkedIn: "https://www.linkedin.com/in/iliasbet/",
    github: "https://github.com/iliasbet",
  },
  fabien: {
    name: "Fabien Celier",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/17087544?v=4",
    linkedIn: "https://www.linkedin.com/in/fabiencelier/",
    github: "https://github.com/fabiencelier",
  },
  chris: {
    name: "Christophe Jow",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/16521527?v=4",
    linkedIn: "https://www.linkedin.com/in/christophe-jow/",
    github: "https://github.com/Chrisjow",
  },
  gianna: {
    name: "Gianna Gard",
    title: "AI Deployment Strategist",
    image: "https://avatars.githubusercontent.com/u/235716301?v=4",
    linkedIn: "https://www.linkedin.com/in/gianna-gard/",
    github: "https://github.com/giga-dust",
  },
  ben: {
    name: "Ben Stoffel-Rosales",
    title: "Account Executive",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09JG1NEUFJ-f63cb1b46c78-512",
    linkedIn: "https://www.linkedin.com/in/bensr1/",
    github: "https://github.com/BenSR1",
  },
  astrid: {
    name: "Astrid Le Faucheur",
    title: "Solution Engineer",
    image: "https://avatars.githubusercontent.com/u/237970272?v=4",
    linkedIn: "https://www.linkedin.com/in/astrid-le-faucheur-7946ab209/",
    github: "https://github.com/astridlf",
  },
  margherita: {
    name: "Margherita Zama",
    title: "Customer Success",
    image: "https://avatars.githubusercontent.com/u/237991722?v=4",
    linkedIn: "https://www.linkedin.com/in/margheritazama/",
    github: "https://github.com/margherita-ops",
  },
  apinon: {
    name: "Alexandre Pinon",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/71273869?s=88&v=4",
    linkedIn: "https://www.linkedin.com/in/alexandre-pinon-60b5a71b7/",
    github: "https://github.com/alexandre-pinon",
  },
  jdfiquet: {
    name: "Jean-David Fiquet",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/6445595?s=88&v=4",
    linkedIn: "https://www.linkedin.com/in/jeandavidfiquet/",
    github: "https://github.com/id13",
  },
  reecebatch: {
    name: "Reece Batchelor",
    title: "Talent Acquisition",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09S9S8PQTX-64b0620a0f35-72",
    linkedIn: "https://www.linkedin.com/in/reece-a0730213bbd/",
    github: "https://github.com/reece-batchelor",
  },
  nsiegle: {
    name: "Nic Siegle",
    title: "Account Executive",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09SB8Q2DU6-65b85b4b1f83-72",
    linkedIn: "https://www.linkedin.com/in/nsiegle/",
    github: "https://github.com/nicdust",
  },
  seth: {
    name: "Seth Mazow",
    title: "Account Executive",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09SBL368JC-95d97a17fd2d-72",
    linkedIn: "https://www.linkedin.com/in/sethmazow/",
    github: "https://github.com/sethmazow",
  },
  bmurray: {
    name: "Bruno Murray",
    title: "Customer Success",
    image: "https://ca.slack-edge.com/T050RH73H9P-U09SGSRG0MA-2329071b8045-72",
    linkedIn: "https://www.linkedin.com/in/bruno-murray-2539682b9/",
    github: "https://github.com/bruno-murray",
  },
  ambra: {
    name: "Ambra Zhang",
    title: "Chief of Staff",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A1YTZATCP-4f46317bbf0d-512",
    linkedIn: "https://uk.linkedin.com/in/ambrazhang/",
    github: "https://github.com/ambra-z",
  },
  elia: {
    name: "Elia Kemp",
    title: "Solutions Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A2CA90QCE-af4cacd4fec8-512",
    linkedIn: "https://www.linkedin.com/in/eliakemp/",
    github: "",
  },
  sarah: {
    name: "Sarah Breen",
    title: "Forward Deployed Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A2EBECJEN-6c9022987019-512",
    linkedIn: "https://www.linkedin.com/in/smb2268/",
    github: "https://github.com/smb2268",
  },
  matthieu: {
    name: "Matthieu Mourey",
    title: "Finance",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A2T982L2V-bc6d5d8f965d-512",
    linkedIn: "https://www.linkedin.com/in/matthieumourey/",
    github: "https://github.com/matthieu-mourey",
  },
  josh: {
    name: "Josh Cohen",
    title: "Account Executive",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A6U9Y7ER1-6031f3f55d28-512",
    linkedIn: "https://www.linkedin.com/in/josh-cohen-3b415348/",
    github: "",
  },
  remy: {
    name: "Rémy Frenoy",
    title: "Software Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A6X8L7CPP-6ee891885467-512",
    linkedIn: "https://www.linkedin.com/in/rfrenoy/",
    github: "https://github.com/rfrenoy",
  },
  matteo: {
    name: "Matteo Trabattoni",
    title: "Software Engineer",
    image: "https://avatars.githubusercontent.com/u/31540320?v=4",
    github: "https://github.com/matteotrab",
    linkedIn: "https://linkedin.com/in/matteo-trabattoni",
  },
  mshanley: {
    name: "Meaghan Shanley",
    title: "Talent Acquisition",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A7XBPR8R5-8c1884c1cfea-512",
    linkedIn: "https://www.linkedin.com/in/meaghanshanley/",
    github: "https://github.com/meaghan-shanley",
  },
  aandrews: {
    name: "Anya Andrews",
    title: "Solution Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AA4ENGC0H-68f70aecf325-512",
    linkedIn: "https://www.linkedin.com/in/anya-andrews/",
    github: "",
  },
  fmossard: {
    name: "François Mossard",
    title: "Partnership Account Manager",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AA4ELHZPB-05594a3227af-512",
    linkedIn: "https://www.linkedin.com/in/francois-mossard/",
    github: "https://github.com/francois-blip",
  },
  iberaud: {
    name: "Iris Beraud",
    title: "Business Operations",
    image: "https://avatars.githubusercontent.com/u/256072453?v=4",
    linkedIn: "https://www.linkedin.com/in/iris-beraud/",
    github: "https://github.com/iris-beraud",
  },
  mgarnier: {
    name: "Maxence Garnier",
    title: "GTM Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0A9NJ8RC85-f6afba1f2122-512",
    linkedIn: "https://www.linkedin.com/in/maxence-garnier/",
    github: "",
  },
  dchristenhuis: {
    name: "Davis Christenhuis",
    title: "SEO Writer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0ACAJ2PNA2-25335cd55dd4-512",
    linkedIn: "https://www.linkedin.com/in/davis-christenhuis/",
    github: "",
  },
  mboudon: {
    name: "Martin Boudon",
    title: "Growth Marketing",
    image: "https://avatars.githubusercontent.com/u/259041606?v=4",
    linkedIn: "https://www.linkedin.com/in/martin-boudon/",
    github: "https://github.com/martindust",
  },
  akabbadj: {
    name: "Ali Kabbadj",
    title: "AI Deployment Strategist",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AD6UBJEPJ-17ea7e1e7d3f-512",
    linkedIn: "https://www.linkedin.com/in/ali-kab/",
    github: "https://github.com/kabbykabs",
  },
  lguy: {
    name: "Lily Guy",
    title: "Customer Success",
    image: "https://avatars.githubusercontent.com/u/263479686?v=4",
    linkedIn: "https://www.linkedin.com/in/lily-guy/",
    github: "https://github.com/lilyg222",
  },
  agaly: {
    name: "Arthur Galy",
    title: "Business Operations",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AK0QJE0M6-c5fa772de63c-512",
    linkedIn: "https://www.linkedin.com/in/arthur-g-707565110/",
    github: "",
  },
  sbernat: {
    name: "Simon Bernat",
    title: "Account Executive",
    image: "https://avatars.githubusercontent.com/u/265247911?v=4",
    linkedIn: "https://www.linkedin.com/in/simon-bernat-5a5604156/",
    github: "https://github.com/simon-dust",
  },
  lacuna: {
    name: "Lilibeth Acuña",
    title: "Partnership Operations",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AKZT589QR-e1f26b534228-512",
    linkedIn: "https://www.linkedin.com/in/lilibethacuna/",
    github: "",
  },
  egomesdamota: {
    name: "Emilie Gomes da Mota",
    title: "Finance Operations",
    image: "https://avatars.githubusercontent.com/u/200744908?v=4",
    linkedIn: "https://www.linkedin.com/in/emilie-gomes-da-mota-58b264199/",
    github: "https://github.com/Emilie-GDM",
  },
  srhumeur: {
    name: "Stephanie Rhumeur",
    title: "Executive Assistant",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AMW9B8SRE-bbd256ba10ef-512",
    linkedIn: "https://www.linkedin.com/in/stephanie-r-4091b84a/",
    github: "",
  },
  caupiais: {
    name: "Clément Aupiais",
    title: "Product Designer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AM218ESR0-c266c1998762-512",
    linkedIn: "https://www.linkedin.com/in/clementaupiais/",
    github: "https://github.com/ClementAupiais",
  },
  thervier: {
    name: "Thibault Hervier",
    title: "Software Engineer",
    image: "https://ca.slack-edge.com/T050RH73H9P-U0AQAB1TPPB-0b1dcdfbf307-512",
    linkedIn: "https://www.linkedin.com/in/thibault-hervier/",
    github: "https://github.com/thervier",
  },
};

export const TEAM_AVATAR_URLS: string[] = Object.values(PEOPLE).map(
  (p) => p.image
);
