const GDRIVE_FULL_SYNC_QUEUE_VERSION = 6;
const GDRIVE_INCREMENTAL_SYNC_QUEUE_VERSION = 5;
export const GDRIVE_FULL_SYNC_QUEUE_NAME = `google-queue-fullsync-v${GDRIVE_FULL_SYNC_QUEUE_VERSION}`;
export const GDRIVE_INCREMENTAL_SYNC_QUEUE_NAME = `google-queue-incremental-v${GDRIVE_INCREMENTAL_SYNC_QUEUE_VERSION}`;
