apiVersion: v1
kind: Service
metadata:
  name: connectors-service
spec:
  selector:
    app: connectors
    name: connectors-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: ClusterIP
