apiVersion: v1
kind: Service
metadata:
  name: core-secondary-service
  annotations:
    cloud.google.com/backend-config: '{"default": "core-backendconfig"}'
spec:
  selector:
    app: core-secondary
    name: core-secondary-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
