apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"metabase-backendconfig"}}'
spec:
  selector:
    app: metabase
    name: metabase-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
