import type { APIErrorType } from "@app/types/error";
import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

export const UNKNOWN_API_ERROR_MESSAGE: MessageDescriptor = msg`Something went wrong.`;

/**
 * @cc [owner:Nils-Fedrigo,label:error-handling;product] one-translation-per-api-error-type
 * Every `APIErrorType` MUST have an entry: adding a type to `API_ERROR_TYPES` without a
 * translation here MUST fail the typecheck. Each entry MUST describe the error on its own,
 * without relying on the server `message` — the UI appends that message only when the server
 * sends one.
 */
export const API_ERROR_MESSAGES: Record<APIErrorType, MessageDescriptor> = {
  // Authentication.
  not_authenticated: msg`You need to sign in to continue.`,
  sso_enforced: msg`Your workspace requires you to sign in with SSO.`,
  missing_authorization_header_error: msg`The request is missing its credentials.`,
  malformed_authorization_header_error: msg`The request credentials are malformed.`,
  invalid_basic_authorization_error: msg`The request credentials are invalid.`,
  invalid_oauth_token_error: msg`Your session is invalid. Sign in again.`,
  expired_oauth_token_error: msg`Your session has expired. Sign in again.`,
  invalid_api_key_error: msg`The API key is invalid.`,
  invalid_sandbox_token_error: msg`The sandbox token is invalid.`,
  user_authentication_required: msg`You need to sign in as a user to do this.`,
  // Generic.
  internal_server_error: msg`Something went wrong on our side.`,
  invalid_request_error: msg`The request is invalid.`,
  invalid_rows_request_error: msg`Your data is incomplete.`,
  unprocessable_entity: msg`The request could not be processed.`,
  method_not_supported_error: msg`This action is not supported.`,
  content_too_large: msg`The content is too large.`,
  rate_limit_error: msg`Too many requests. Wait a moment and try again.`,
  service_unavailable: msg`The service is temporarily unavailable. Try again later.`,
  invalid_pagination_parameters: msg`The pagination parameters are invalid.`,
  // Users, workspaces and memberships.
  user_not_found: msg`The user was not found.`,
  workspace_not_found: msg`The workspace was not found.`,
  workspace_in_different_cell: msg`This workspace is hosted in another region.`,
  workspace_auth_error: msg`You don't have permission to do this in this workspace.`,
  workspace_can_use_product_required_error: msg`Your workspace doesn't have access to this product.`,
  workspace_user_not_found: msg`The user is not a member of this workspace.`,
  personal_workspace_not_found: msg`Your personal workspace was not found.`,
  membership_not_found: msg`The membership was not found.`,
  membership_revoked: msg`Your access to this workspace has been revoked.`,
  invitation_not_found: msg`The invitation was not found.`,
  invitation_already_sent_recently: msg`An invitation was already sent recently. Wait before sending another one.`,
  user_cap_reached: msg`Your workspace has reached its maximum number of members.`,
  no_seat: msg`No seat is available for this user.`,
  group_not_found: msg`The group was not found.`,
  // Plans, subscriptions and billing.
  plan_limit_error: msg`You've reached a limit of your plan.`,
  plan_message_limit_exceeded: msg`You've reached the message limit of your plan.`,
  credits_exhausted: msg`Your workspace has run out of credits.`,
  stripe_invalid_product_id_error: msg`The selected product is invalid.`,
  subscription_payment_failed: msg`The subscription payment failed.`,
  subscription_not_found: msg`The subscription was not found.`,
  subscription_state_invalid: msg`The subscription is not in a valid state for this action.`,
  trial_restriction: msg`This is not available during the trial.`,
  coupon_not_found: msg`The coupon was not found.`,
  coupon_not_redeemable: msg`The coupon can't be redeemed.`,
  coupon_already_redeemed: msg`The coupon has already been redeemed.`,
  // Data sources and connections.
  data_source_error: msg`The data source returned an error.`,
  data_source_not_found: msg`The data source was not found.`,
  data_source_view_not_found: msg`The data source view was not found.`,
  data_source_auth_error: msg`You don't have permission to access this data source.`,
  data_source_quota_error: msg`The data source has reached its storage limit.`,
  workspace_quota_error: msg`Your workspace has reached its storage limit.`,
  data_source_document_not_found: msg`The document was not found.`,
  data_source_not_managed: msg`This data source is not managed by a connection.`,
  table_not_found: msg`The table was not found.`,
  connector_not_found_error: msg`The connection was not found.`,
  connector_update_error: msg`The connection could not be updated.`,
  connector_update_unauthorized: msg`You don't have permission to update this connection.`,
  connector_oauth_connection_not_found: msg`The authorization for this connection was not found.`,
  connector_oauth_target_mismatch: msg`The authorized account doesn't match the one used by this connection.`,
  connector_oauth_user_missing_rights: msg`The authorized account is missing the required permissions.`,
  connector_oauth_user_must_be_admin: msg`The authorized account must be an admin.`,
  connector_provider_not_supported: msg`This connection provider is not supported.`,
  connector_credentials_error: msg`The connection credentials are invalid.`,
  connector_credentials_not_found: msg`The connection credentials were not found.`,
  connector_operation_in_progress: msg`An operation is already in progress on this connection. Try again later.`,
  // Files.
  file_not_found: msg`The file was not found.`,
  file_too_large: msg`The file is too large.`,
  file_type_not_supported: msg`This file type is not supported.`,
  file_is_empty: msg`The file is empty.`,
  // Apps, runs, providers and datasets.
  run_error: msg`The run failed.`,
  run_not_found: msg`The run was not found.`,
  app_not_found: msg`The app was not found.`,
  app_auth_error: msg`You don't have permission to access this app.`,
  provider_auth_error: msg`The provider rejected the credentials.`,
  provider_not_found: msg`The provider was not found.`,
  dataset_not_found: msg`The dataset was not found.`,
  dust_app_secret_not_found: msg`The secret was not found.`,
  // Agents.
  agent_configuration_not_found: msg`The agent was not found.`,
  agent_inaccessible: msg`You don't have access to this agent.`,
  agent_group_permission_error: msg`You don't have permission to edit this agent.`,
  agent_message_error: msg`The agent encountered an error.`,
  agent_memory_not_found: msg`The agent memory was not found.`,
  agent_suggestion_not_found: msg`The suggestion was not found.`,
  batch_suggestion_not_found: msg`The suggestions were not found.`,
  assistant_saving_error: msg`The agent could not be saved.`,
  global_agent_error: msg`This default agent can't be changed this way.`,
  model_disabled: msg`This model is disabled.`,
  template_not_found: msg`The template was not found.`,
  chat_message_not_found: msg`The message was not found.`,
  // Conversations.
  conversation_not_found: msg`The conversation was not found.`,
  conversation_access_restricted: msg`You don't have access to this conversation.`,
  conversation_agent_running: msg`An agent is still running in this conversation.`,
  conversation_with_unavailable_agent: msg`This conversation uses an agent that is no longer available.`,
  conversation_context_usage_not_found: msg`The conversation context usage was not found.`,
  user_already_participant: msg`The user is already a participant in this conversation.`,
  message_not_found: msg`The message was not found.`,
  message_deletion_not_authorized: msg`You don't have permission to delete this message.`,
  // Tools, actions and MCP servers.
  action_unknown_error: msg`The action failed for an unknown reason.`,
  action_api_error: msg`The action failed.`,
  action_failed: msg`The action failed.`,
  unexpected_action_response: msg`The action returned an unexpected response.`,
  action_not_found: msg`The action was not found.`,
  action_not_blocked: msg`This action is not waiting for approval.`,
  mcp_auth_error: msg`The tool requires authentication.`,
  invalid_mcp_server_id: msg`The tool ID is invalid.`,
  mcp_server_not_found: msg`The tool was not found.`,
  mcp_server_connection_not_found: msg`The tool connection was not found.`,
  mcp_server_view_not_found: msg`The tool is not available in this space.`,
  plugin_not_found: msg`The plugin was not found.`,
  plugin_execution_failed: msg`The plugin failed to run.`,
  recommendation_not_found: msg`The recommendation was not found.`,
  // Skills, sandboxes and frames.
  skill_not_found: msg`The skill was not found.`,
  skill_github_repository_not_found: msg`The GitHub repository was not found.`,
  sandbox_function_not_found: msg`The sandbox function was not found.`,
  sandbox_function_invocation_not_found: msg`The sandbox function call was not found.`,
  frame_runtime_unavailable: msg`The frame runtime is unavailable.`,
  fast_function_called_tools: msg`This function can't call tools.`,
  // Spaces and projects.
  space_already_exists: msg`A space with this name already exists.`,
  space_not_found: msg`The space was not found.`,
  project_task_not_found: msg`The task was not found.`,
  project_metadata_not_found: msg`The project details were not found.`,
  activation_work_area_not_found: msg`The work area was not found.`,
  // Triggers and webhooks.
  trigger_not_found: msg`The trigger was not found.`,
  webhook_source_not_found: msg`The webhook source was not found.`,
  webhook_source_view_auth_error: msg`You don't have permission to access this webhook source in this space.`,
  webhook_source_auth_error: msg`You don't have permission to access this webhook source.`,
  webhook_source_view_not_found: msg`The webhook source is not available in this space.`,
  webhook_source_view_triggering_agent: msg`This webhook source is still used by an agent trigger.`,
  webhook_source_misconfiguration: msg`The webhook source is misconfigured.`,
  webhook_processing_error: msg`The webhook could not be processed.`,
  webhook_storage_error: msg`The webhook could not be stored.`,
  wakeup_not_found: msg`The wake-up was not found.`,
  // Keys.
  key_not_found: msg`The API key was not found.`,
  insufficient_key_scope: msg`The API key doesn't have the required scope.`,
  // Labs.
  transcripts_configuration_not_found: msg`The meeting transcripts configuration was not found.`,
  transcripts_configuration_default_not_allowed: msg`This meeting transcripts configuration can't be the default.`,
  transcripts_configuration_already_exists: msg`A meeting transcripts configuration already exists.`,
  // Feature flags.
  feature_flag_not_found: msg`The feature flag was not found.`,
  feature_flag_already_exists: msg`The feature flag already exists.`,
  // WorkOS.
  workos_organization_not_found: msg`The identity provider organization was not found.`,
  workos_server_error: msg`The identity provider returned an error.`,
  workos_multiple_sso_connections_not_supported: msg`Multiple SSO connections are not supported.`,
  workos_multiple_directories_not_supported: msg`Multiple directories are not supported.`,
  // Search.
  elasticsearch_error: msg`Search is temporarily unavailable.`,
  // Client-side errors from the Dust API client.
  unexpected_error_format: msg`The server returned an unexpected error.`,
  unexpected_response_format: msg`The server returned an unexpected response.`,
  unexpected_network_error: msg`A network error occurred. Check your connection and try again.`,
};
