#!/bin/bash

if [ -z "$ENABLE_AUTO_SYNC_ON_PULL" ]
then
  echo "You can enable dust-apps auto sync by setting ENABLE_AUTO_SYNC_ON_PULL"
  exit 0
fi

current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" = "main" ]
then
    ./front/admin/copy_apps.sh
fi

exit 0
