#!/bin/sh

# Check if the current branch is 'main'
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" = "main" ]; then
    # Check if the flag is set
    if [ -z "$ALLOW_MAIN_COMMIT" ]; then
        echo "Error: Committing to 'main' is not allowed. Use ALLOW_MAIN_COMMIT=1 to override."
        exit 1
    fi
fi

if [ -z "$ENABLE_GGSHIELD_ON_COMMIT" ]
then
  echo "You can enable secret check by setting ENABLE_GGSHIELD_ON_COMMIT and installing ggshield"
else
  if command -v ggshield 2>&1 >/dev/null;  then
    ggshield secret scan pre-commit "$@"
  else
    echo "ggshield is not installed. Please install ggshield to enable secret check"
  fi
fi

# If env var DUST_LINT_ON_COMMIT = 1, run the linter
if [ -z "$DUST_LINT_ON_COMMIT" ]; then
    echo "Please set DUST_LINT_ON_COMMIT if you want to locally run the lint, type check etc.. before committing."
    exit 0
fi

# Get the root path of the git repository
root_path=$(git rev-parse --show-toplevel)

# List the directories to check for changes
directories=("front" "connectors")

# For each directory, check if any files have changed
for directory in "${directories[@]}"; do
    if git diff --cached --name-only | grep -qE "^$directory/"; then
        # Run the linter on root_path concatenated with the directory
        if ! npm run lint:test-filenames --if-present --prefix $root_path/$directory; then
            echo "Linting test-filenames failed. Please fix the issues before committing."
            exit 1
        fi
        if ! npm run tsc --if-present --prefix $root_path/$directory; then
            echo "Type checking failed. Please fix the issues before committing."
            exit 1
        fi
        
        # Check for changes in front/pages/api/v1/ only when processing the front/ directory
        if [ "$directory" = "front" ]; then
            if git diff --cached --name-only | grep -qE "^front/pages/api/v1/"; then
                if ! npm run docs:check --if-present --prefix $root_path/$directory; then
                    echo "Documentation check failed. Please fix the issues before committing."
                    exit 1
                fi
            fi
        fi

        if ! npx lint-staged; then
            echo "Formatting check failed. Please fix the issues before committing."
            exit 1
        fi
    fi
done

# Proceed with the commit
exit 0
