apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: viz-backendconfig
spec:
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 600
  timeoutSec: 30
  customResponseHeaders:
    headers:
      - "Strict-Transport-Security: max-age=86400"
      - "X-Content-Type-Options: nosniff"
      - "Referrer-Policy: strict-origin-when-cross-origin"
      - "Permissions-Policy: geolocation=(), microphone=(), camera=()"
