apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  DD_ENV: "prod"
  DD_SERVICE: "proxy"
  DD_LOGS_INJECTION: "true"
  DD_RUNTIME_METRICS_ENABLED: "true"
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    events {
      worker_connections 1024;
    }

    http {
      resolver 8.8.8.8 8.8.4.4 valid=300s;
      resolver_timeout 5s;
    
      server {
        listen 80;

        # forward proxy for CONNECT requests
        proxy_connect;
        proxy_connect_allow            all;
        
        location / {
          auth_basic "Proxy Authentication Required";
          auth_basic_user_file /etc/nginx/auth;

          proxy_pass $scheme://$host$request_uri;
          proxy_set_header Host $http_host;
          proxy_ssl_server_name on;
          proxy_ssl_session_reuse off;
        }
      }
    }

    stream {
      server {
        listen 1080;
        proxy_pass $remote_addr:$remote_port;
      }
    }
