[package]
name = "dfs-protocol"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
prost = "0.14"
tonic = { version = "0.14", features = ["tls-ring", "tls-native-roots"] }
tonic-prost = "0.14"
uuid = { version = "1", features = ["v7"] }

[build-dependencies]
tonic-prost-build = "0.14"

[dev-dependencies]
anyhow = "1.0"

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
expect_used = "deny"
unwrap_used = "deny"
