//! The numfmt golden table: `corpus/numfmt_cases.tsv` is the
//! spec; the engine must pass 100% of it. The table is generated by
//! `scripts/gen-numfmt-table.mjs` from SSF (pinned) + curated Excel-verified
//! cases; it is committed and reviewed, never auto-blessed.
//!
//! Comparison convention: trailing whitespace trimmed on both sides
//! (alignment padding is invisible in the DOM).

mod common;

use engine_core::numfmt::{builtin_format, format_number, format_text, EN_US};

#[test]
fn numfmt_golden_table_passes_100_percent() {
    let table =
        String::from_utf8(common::read_corpus_file("numfmt_cases.tsv")).expect("utf8 table");
    let mut total = 0usize;
    let mut failures: Vec<String> = Vec::new();

    for (line_no, line) in table.lines().enumerate().skip(1) {
        if line.trim().is_empty() {
            continue;
        }
        let cols: Vec<&str> = line.split('\t').collect();
        assert!(cols.len() >= 4, "line {}: bad column count", line_no + 1);
        let (raw_value, mut format, date1904, expected) =
            (cols[0], cols[1], cols[2] == "1", cols[3]);

        let resolved;
        if let Some(id) = format.strip_prefix("builtin:") {
            let id: u32 = id.parse().expect("builtin id");
            resolved = builtin_format(id).unwrap_or("General").to_string();
            format = &resolved;
        }

        let actual = match raw_value.parse::<f64>() {
            Ok(v) => format_number(v, format, date1904, &EN_US).text,
            Err(_) => format_text(raw_value, format, &EN_US).text,
        };

        total += 1;
        if actual.trim_end() != expected.trim_end() {
            failures.push(format!(
                "line {}: value={raw_value} format={format:?} expected={expected:?} actual={actual:?} ({})",
                line_no + 1,
                cols.get(4).unwrap_or(&"")
            ));
        }
    }

    assert!(
        total >= 500,
        "golden table shrank below the 500-case floor: {total}"
    );
    assert!(
        failures.is_empty(),
        "{}/{} numfmt golden failures:\n{}",
        failures.len(),
        total,
        failures.join("\n")
    );
}
