name: Deploy Region Resolver

on:
  workflow_dispatch:

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
  SERVICE: region-resolver
  IMAGE_NAME: region-resolver
  REGION: us-central1

concurrency:
  group: deploy_resolver
  cancel-in-progress: false

jobs:
  notify-start:
    runs-on: ubuntu-latest
    outputs:
      thread_ts: ${{ steps.build_message.outputs.thread_ts }}
    steps:
      - uses: actions/checkout@v3
      - name: Get short sha
        id: short_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Notify Build And Deploy Start
        id: build_message
        uses: ./.github/actions/slack-notify
        with:
          step: "start"
          component: "region-resolver"
          image_tag: ${{ steps.short_sha.outputs.short_sha }}
          channel: ${{ secrets.SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy:
    needs: [notify-start]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get short sha
        id: short_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: Build using Cloud Build
        run: |
          chmod +x ./k8s/cloud-build.sh
          ./k8s/cloud-build.sh \
            --working-dir=./ \
            --image-name=${IMAGE_NAME} \
            --dockerfile-path=./resolver/Dockerfile \
            --region=${REGION}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.REGION }}-docker.pkg.dev/${{ env.GCLOUD_PROJECT_ID }}/dust-images/${{ env.IMAGE_NAME }}:${{ steps.short_sha.outputs.short_sha }}"
