name: Deploy Oauth

on:
  workflow_dispatch:
    inputs:
      regions:
        description: "Regions to deploy to"
        required: true
        default: "us-central1"
        type: choice
        options:
          - "us-central1"
          - "europe-west1"
          - "all"
      check_deployment_blocked:
        description: "Check #deployment locks or force deploy"
        required: true
        default: "check"
        type: choice
        options:
          - "check"
          - "force (dangerous)"

concurrency:
  group: deploy_oauth
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      check_deployment_blocked: ${{ github.event.inputs.check_deployment_blocked }}
      component: oauth
      dockerfile_path: ./oauth.Dockerfile
      regions: ${{ github.event.inputs.regions }}
      working_dir: ./core/
    secrets: inherit
