name: Deploy Alerting Temporal

on:
  workflow_dispatch:
    inputs:
      regions:
        description: "Regions to deploy to"
        required: true
        default: "all"
        type: choice
        options:
          - "us-central1"
          - "europe-west1"
          - "all"

concurrency:
  group: deploy_alerting_temporal
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      check_deployment_blocked: false
      component: alerting-temporal
      dockerfile_path: ./Dockerfile
      regions: ${{ github.event.inputs.regions }}
      working_dir: ./alerting/temporal/
    secrets: inherit
