name: Deploy Alerting Temporal

on:
  workflow_dispatch:

concurrency:
  group: deploy_alerting_temporal
  cancel-in-progress: false

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short sha
        id: short_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Setup kubectl
        run: |
          gcloud container clusters get-credentials dust-kube --region us-central1

      - name: Build the image on Cloud Build
        run: |
          chmod +x ./k8s/cloud-build.sh
          ./k8s/cloud-build.sh alerting/temporal

      - name: Deploy the image on Kubernetes
        run: |
          chmod +x ./k8s/deploy-image.sh
          ./k8s/deploy-image.sh gcr.io/$GCLOUD_PROJECT_ID/alerting-deployment-image:${{ steps.short_sha.outputs.short_sha }} alerting-temporal-deployment

      - name: Wait for rollout to complete
        run: kubectl rollout status deployment/alerting-temporal-deployment --timeout=10m
