name: Deploy OpenAPI Docs

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run `openapi` command 🚀
        uses: readmeio/rdme@51a80867c45de15e2b41af0c4bd5bbc61b932804 # v10.6.2
        with:
          rdme: openapi upload front/public/swagger.json --version=v1.1 --key=${{ secrets.README_API_KEY }} --slug=dust-api-documentation.json
