name: Deploy Connectors

on:
  workflow_dispatch:

concurrency:
  group: deploy_connectors
  cancel-in-progress: false

env:
  GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short sha
        id: short_sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: "Authenticate with Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      - name: Setup kubectl
        run: |
          gcloud container clusters get-credentials dust-kube --region us-central1

      - name: Build the image on Cloud Build
        run: |
          chmod +x ./k8s/cloud-build.sh
          ./k8s/cloud-build.sh --image-name=connectors --dockerfile-path=./connectors/Dockerfile --working-dir=./ --dust-client-facing-url=https://dust.tt

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: true
          workload_identity_provider: "projects/357744735673/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "gh-charts-cd@dust-infra.iam.gserviceaccount.com"

      - name: Configure gcloud credentials
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Setup Helm and Helmfile
        uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-args: --version # Just to verify installation

      - name: Deploy the image on Kubernetes
        run: |
          chmod +x ./k8s/deploy-image.sh

          ./k8s/deploy-image.sh gcr.io/$GCLOUD_PROJECT_ID/connectors-image:${{ steps.short_sha.outputs.short_sha }} connectors-deployment

      - name: Deploy with Helmfile
        run: |
          helmfile diff --set connectors.image.tag=${{ steps.short_sha.outputs.short_sha }}
          helmfile apply --set connectors.image.tag=${{ steps.short_sha.outputs.short_sha }} --wait --timeout 600s

      - name: Wait for rollout to complete
        run: |
          echo "Waiting for rollout to complete"
          kubectl rollout status deployment/connectors-deployment --timeout=10m
