name: Revert Front Edge
on:
  workflow_dispatch:
    inputs:
      regions:
        description: "Regions to deploy to"
        required: true
        default: "all"
        type: choice
        options:
          - "us-central1"
          - "europe-west1"
          - "all"
      image_tag:
        description: "The image tag/SHA to deploy"
        type: string
        required: true

concurrency:
  group: revert_front_edge
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      check_deployment_blocked: ${{ github.event.inputs.check_deployment_blocked == 'check' }}
      component: front
      dockerfile_path: ./front/Dockerfile
      regions: ${{ github.event.inputs.regions }}
      working_dir: ./
    secrets: inherit
