name: SQL Migration required

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'front/lib/models/**'
      - 'connectors/src/lib/models/**'

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for file changes
        id: file_changes
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/main:refs/remotes/origin/main

          echo "Checking for changed files..."

          CHANGED_FILES=$(git diff --name-only origin/main ${{ github.sha }} -- 'front/lib/models/' 'connectors/src/lib/models/')
          if [ -n "$CHANGED_FILES" ]; then
            echo "Changed files found:"
            echo "$CHANGED_FILES"
            echo "modified=true" >> $GITHUB_OUTPUT
            echo "::warning ::Files in 'front/lib/models/' or 'connectors/src/lib/models/' have been modified."
          else
            echo "No changed files found."
            echo "modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Post a warning comment on PR
        if: ${{ steps.file_changes.outputs.modified == 'true' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: '⚠️ Warning: Files in `front/lib/models/` or `connectors/src/lib/models/` have been modified. A migration is required!',
            });